nodejs/build

setup/debian-wheezy-gcc/Dockerfile
setup/debian-wheezy-gcc/README.md
setup/debian-wheezy-gcc/deb-control.patch

This is a Dockerfile to make a Docker image based on `debian:weezy` that installs the source of GCC 4.9 from jessie but all of the dependencies from weezy. I've made a patch for the `debian/control` file to make it compile.
When you run the Docker image and pass it an `/opt/debs` volume (i.e. just something local) it'll do the full compile & test of GCC 4.9 and dump all the debs into that volume.
This only works with ***gcc-4.9-4.9.2*** which is what's in jessie right now but it's given me binaries which I've hosted in a repo at https://deb.nodesource.com/weezy-gcc49 and can be installed on a weezy server something like this:
```
apt-get install -y apt-transport-https curl
echo 'deb https://deb.nodesource.com/weezy-gcc49 weezy-gcc49 main' >> /etc/apt/sources.list
curl -s …
```

Dockerfile & instructions for generating debs for GCC 4.9 on weezy

---

setup/www/README.md
setup/www/ansible-inventory
setup/www/ansible-playbook.yaml
setup/www/ansible-vars.yaml
setup/www/host_vars/.gitignore
setup/www/host_vars/iojs-www.tmpl
setup/www/resources/.gitignore
setup/www/resources/github-webhook.conf
setup/www/resources/github-webhook.json
setup/www/resources/iojs.org

This PR adds an Ansible playbook to set up an iojs.org web server. It's already been run against host `104.236.136.193` which just needs an SSL certificate and an nginx restart.
The server is listening to a GitHub Webhook for [iojs/iojs.github.io](https://github.com/iojs/iojs.github.io) and any commits to master will trigger a sync to the served files, so it should be pretty autonomous.
@indutny you have root access to 104.236.136.193. the certificate chain goes in */etc/nginx/ssl/iojs_chained.crt* and the key in */etc/nginx/ssl/iojs.key*, nginx can be restarted with `service nginx restart`. If you want to change the server setup at all can you either edit these setup files or at least provide details in this repo about what you've done so we can have the setup scripted properly.

Added iojs.org web setup Ansible playbook

---

setup/windows/README.md

I'm not going to bother even attempting to do something automatic for this, Ansible could probably do it but the downloads make it tricky.
Manual setup instructions instead. Two new servers are now running according to these instructions and appear to be working just fine for both iojs and libuv.

Added manual Windows setup instructions

---

setup/ansible-inventory
setup/ubuntu10.04/README.md
setup/ubuntu10.04/ansible-playbook.yaml
setup/ubuntu10.04/ansible-vars.yaml
setup/ubuntu10.04/host_vars/.gitignore
setup/ubuntu10.04/resources/start.sh
setup/ubuntu12.04/README.md
setup/ubuntu12.04/ansible-playbook.yaml
setup/ubuntu12.04/ansible-vars.yaml
setup/ubuntu12.04/host_vars/.gitignore
setup/ubuntu12.04/resources/start.sh
setup/ubuntu14.04/README.md
setup/ubuntu14.04/ansible-playbook.yaml
setup/ubuntu14.04/ansible-vars.yaml
setup/ubuntu14.04/host_vars/.gitignore
setup/ubuntu14.04/resources/start.sh
setup/ubuntu14.10/README.md
setup/ubuntu14.10/ansible-playbook.yaml
setup/ubuntu14.10/ansible-vars.yaml
setup/ubuntu14.10/host_vars/.gitignore
setup/ubuntu14.10/resources/start.sh

* 14.10 64
* 14.04 64 & 32 + GYP version for libuv
* 12.04 64
* 10.04 64 & 32

Added Ubuntu host setup

---

setup/www/ansible-playbook.yaml

Hopefully this will let .xz files be downloaded properly.
The gzip one isn't super important, but nginx is just outdated on it.

www: add .xz & fix .gz mime-types

---

setup/www/host_vars/iojs-www.tmpl

For https://github.com/iojs/iojs.github.io/pull/26
If this was going out live, I'd recommend merging https://github.com/iojs/iojs.github.io/pull/26 first as it will handle redirecting to the new public/ directory.

www: sync from `public/` for iojs/website#26

---

README.md
setup/ansible-inventory
setup/smartos/README.md
setup/smartos/ansible-playbook.yaml
setup/smartos/ansible-vars.yaml
setup/smartos/host_vars/.gitignore
setup/smartos/resources/jenkins_manifest.xml

This PR is standing on the shoulders of @geek's great job in #60. Please review.

build: support smartos (with hosts from Joyent)

---

.gitignore
tools/nightly-builder/.gitignore
tools/nightly-builder/build-required.js
tools/nightly-builder/latest-build.js
tools/nightly-builder/latest-commit.js
tools/nightly-builder/nightly-builder.js
tools/nightly-builder/package.json
tools/nightly-builder/test.js
tools/nightly-builder/trigger-build.js

Probably R=@Fishrock123 but input welcome from others.
This app is to be used via cron to trigger nightly builds for both `nightly` and `next-nightly`. It finds the latest build and gets the commit sha from it, then it compares that commit sha of the appropriate git branch (`v1.x` for `nightly` and `next` for `next-nightly`). If they don't match then it triggers a build on Jenkins using all the appropriate parameters for the iojs+release+nightly including an authorization token that's in the job configuration.
Used it just now to build https://jenkins-iojs.nodesource.com/job/iojs+release+nightly/139/

added initial nightly-builder app

---

README.md

Just some quick changes to the companies and people listed on the README, the list hasn't changed since we started this in node-forward and @mikeal reminded me that the hardware providers list was wrong so I've fixed that now and updated the people list while I was at it. I think I have it right ..?

companies & people changes

---

tools/dist/dist-indexer/dist-indexer.js

Fixes: #94 
My linter has apparently been on strike and a stupid non-declared variable has crept in. This is now running on the server and index.tab and index.json appear to be fixed now.
/cc @springmeyer

lint dist-indexer.js and fix missing modVersion var

---

setup/windows/README.md

As described in detail in #142, old versions of Git for windows crash when running `git rebase`. The `git-for-windows/git` repository contains pre-releases of newer versions that work correctly.
The three Windows 2012r2 machines have already been updated.

win: download Git from git-for-windows releases

---

setup/ubuntu12.04/ansible-playbook.yaml

The version of git shipped with Ubuntu 12.04 is old, it cannot fetch from GitHub refs that were updated. This is an issue with Jenkins, since the test-commit job uses a reference that was updated by the push-merge-commit job.
/cc @nodejs/build

ubuntu: add git-core PPA to 12.04

---

setup/centos5/ansible-vars.yaml
setup/centos6/ansible-vars.yaml
setup/centos7/ansible-vars.yaml
setup/containers/ansible-vars.yaml
setup/debian8/ansible-vars.yaml
setup/fedora21/ansible-vars.yaml
setup/fedora22/ansible-vars.yaml
setup/linter/ansible-vars.yaml
setup/smartos/ansible-vars.yaml
setup/ubuntu12.04/ansible-vars.yaml
setup/ubuntu14.04/ansible-vars.yaml
setup/ubuntu14.10/ansible-vars.yaml
setup/ubuntu15.04/ansible-vars.yaml

I added myself to the `ssh_users` list in almost all Jenkins slaves.
Left out `armv7-wheezy`, `freebsd` and `raspberry-pi` because they are not listed in Digital Ocean or Rackspace and I don't have their IPs. Should I include them anyway?
I already have access to all machines but `debian8`.
cc @nodejs/build

Add joaocgreis to the ssh_users list in Jenkins slaves

---

setup/smartos/ansible-playbook.yaml
setup/smartos/ansible-vars.yaml

As seen recently in https://github.com/joyent/node/issues/25858 , DNS configuration is sensitive for the tests. The test machines should be configured to use Google DNS servers, and using other servers may cause tests to fail, as discussed in https://github.com/joyent/node/issues/8056 .
I changed the DNS configuration in the SmartOS slaves by editing `/etc/resolv.conf`. This PR makes this change permanent by adding it to the ansible playbook.
Fixes: https://github.com/joyent/node/issues/25858
Fixes: #155

smartos: use Google DNS servers

---

setup/www/resources/config/nodejs.org

This is necessary to land https://github.com/nodejs/node/pull/4111
@rvagg is this the correct way to add the redirect?

redirect for Windows Environment wiki page

---

setup/www/tools/dist-indexer/transform-filename.js

Adds support for `linux-ppc64le` in https://nodejs.org/download/release/index.tab and https://nodejs.org/download/release/index.json and also indirectly to the promotion script @ https://github.com/nodejs/node/blob/master/tools/release.sh run by releasers.
/cc @mhdawson

add linux-ppc64le to dist-indexer

---

setup/www/resources/config/iojs.org
setup/www/resources/config/nodejs.org
setup/www/resources/config/ssl-defaults.conf
setup/www/tasks/nginx.yaml

Minor refactor of the www config surrounding redirects:
- avoid `if {}` when possible
- share ssl defaults
- avoid extra http://www.foo.com -> http://foo.com -> https://foo.com when possible
Note: this is not tested; don't have access to my testing environment at the moment -- but I just wanted more eyes in case there are additional improvements to be made.

www: simplify ssl and redirects

---

setup/www/resources/config/open-file-cache.conf
setup/www/tasks/nginx.yaml

Avoid re-reading file handles when serving downloads (well, most things). This lessens the strain on nginx.

www: add a open file cache

---

setup/www/resources/scripts/build-site.sh

Refs:
- https://github.com/nodejs/nodejs.org/issues/712
- https://github.com/nodejs/nodejs.org/pull/713

www: Store gzip representations of common files on deploy

---

setup/ubuntu16.04/resources/jenkins.service.j2

ccache wasn't working because a newer version of systemd didn't accept multiline Environment declarations. Fix this by declaring it multiple times instead.

ubuntu16: fix environment declaration

---

setup/www/resources/config/nodejs.org

I happened to notice that (some of?) our blog content wasn't redirecting from http to https and I _believe_ this was the culprit. It's live now and the redirects appear to be working now. I can't find anything else to explain it, although this one doesn't really make sense to me either!

qualify /blog url with ^

---

setup/ansible-inventory
setup/ubuntu12.04/README.md

We were runnning short of ubuntu12 slaves which made the build slow down, especially during smoketests.

ubuntu12: add new slave

---

backup/backup_scripts/remove_old.sh

In an attempt to make our CI faster, reduce the amount of stored jobs from 30 days to 20 days.
Refs https://github.com/nodejs/build/issues/426.

backup: lower periodic history to 20 days

---

.gitignore
setup/ubuntu16.04/.gitignore
setup/ubuntu16.04/README.md
setup/ubuntu16.04/ansible-playbook.yaml
setup/ubuntu16.04/resources/jenkins.service.j2

A few fixups and some compatibility things for 16.04 to support the new C2's that are now in CI ("ubuntu1604-armv8"). Note that I'm using `server_jobs: 2` for these, they have 8 cores but not a ton of RAM and we've hit OOMs compiling with `-j4` already.
R=@jbergstroem

add support for Odroid C2 (ARMv7) with Ubuntu 16.04

---

setup/ansible-inventory
setup/github-bot/README.md
setup/github-bot/ansible-playbook.yaml
setup/github-bot/ansible-vars.yaml
setup/github-bot/resources/environment-file
setup/github-bot/resources/github-bot.service

Sooo, here's my first shot at creating an ansible setup for the bot. Has been run on the test host @jbergstroem created for this purpose, seems to be working nicely.
Primarly installs necessary binaries, checks out the application code from github.com, before starting the created systemd service which runs (and supervises) `npm start`.
As there's a big ansible refactor just around the corner, these changes doesn't need to be merged asap, but would be nice to get some feedback about obviously missing/wrong parts.

github-bot: ansible setup

---

setup/www/resources/config/nodejs.org

Japanese has been added to nodejs.org, these changes enabled the english fallback for pages the translation WG hasn't translated yet.
Refs: https://github.com/nodejs/nodejs.org/pull/900

www: enable fallback for Japanese locale

---

README.md

Refs: https://github.com/nodejs/build/issues/514

doc: add Gibson Fahnestock to members

---

setup/github-bot/ansible-playbook.yaml
setup/github-bot/ansible-vars.yaml
setup/github-bot/resources/deploy-github-bot.sh
setup/github-bot/resources/github-bot-deploy-webhook.json
setup/github-bot/resources/github-bot-deploy-webhook.service

This re-deploys the github-bot whenever new commits lands in the master branch. It's a simplified version of the nodejs.org setup, which roughly includes:
- A new web application needed as the GitHub webhook receiver, implemented with the [github-webhook npm package](https://www.npmjs.com/package/github-webhook).
- systemd service (`github-bot-deploy-webhook.service`) to run and monitor the webhook application.
- bash script (`deploy-github-bot.sh`) triggered by the webhook application which checks out the latest changes in the master branch and restarts the github-bot.service
Any thoughts more than welcome!
Refs https://github.com/nodejs/github-bot/issues/69

github-bot: auto deploy upon new commits

---

setup/github-bot/ansible-playbook.yaml
setup/github-bot/ansible-vars.yaml
setup/github-bot/resources/environment-file

These changes clones the nodejs/node repository required for the bot to automatically attempt backport of new PRs.
Refs https://github.com/nodejs/github-bot/pull/90
/cc @nodejs/github-bot

github-bot: clone nodejs/node repository

---

setup/TESTING_LOCALLY.md

For some reason, the previous Vagrantfile example didn't work anymore. When running `vagrant up` the root user was simply not able to do the initial login to the server anymore, it stalled at:
```
==> default: Waiting for machine to boot. This may take a few minutes...
default: SSH address: 127.0.0.1:2222
default: SSH username: root
default: SSH auth method: private key
default: Warning: Authentication failure. Retrying...
default: Warning: Authentication failure. Retrying...
default: Warning: Authentication failure. Retrying...
default: Warning: Authentication failure. Retrying...
```
Therefore the virtual machine setup procedure had to be manually aborted.
With these changes, we don't initially login with root anymore as that turned out to be quite brittle. We now use the traditional …

Update Vagrantfile in local ansible test guide

---

setup/github-bot/ansible-playbook.yaml

Needed for the attempt-backport functionality of the bot since it does
some git actions requiring author name and email, such as `git am`.
Seeing this when running locally:
```
TASK [Runtime dependencies | Config node repo author email] ***********************
changed: [github-bot]
[WARNING]: Consider using git module rather than running git
```
But as far as I see, manipulating config isn't possible with the [git module](http://docs.ansible.com/ansible/git_module.html). Found [git_config module](http://docs.ansible.com/ansible/git_config_module.html) tho, if we're fine with requiring ansible v2.1?
Refs: https://github.com/nodejs/build/issues/561

github-bot: config git author name and email

---

doc/meetings/build-wg-meetings-2016-12-20.md

doc: add minutes for build WG meeting 2016-12-20

doc: add minutes for build WG meeting 2016-12-20

---

setup/github-bot/resources/environment-file

We've had an issue with all logs written by the github-bot being deleted whenever the bot is re-deployed. That's especially bad when we want to debug issues happening a few days ago, which would be impossible if we've done a re-deploy in between.
The root cause of that issue is that we clone the github-bot repo onto the server and write logs to `./logs` of that cloned repo. Whenever we re-deploy we run `git clean -fdx` before updating the repo, resulting in any untracked files to be deleted.
By adding a `$LOGS_DIR` pointing to a directory *outside* the git repo,
will prevent logs being deleted cause of re-deploys.
~P.S. we haven't added support for `$LOGS_DIR` in the bot yet, will do that as soon as this lands.~

github-bot: add $LOGS_DIR env variable

---

setup/github-bot/ansible-playbook.yaml

Chore to keep playbook running smoothly without errors being generated.
Got this error when running the playbook:
```bash
$ ansible-playbook -i ../ansible-inventory ansible-playbook.yaml
...
TASK [Runtime dependencies | Clone node repo] **********************************
fatal: [infra-rackspace-debian8-x64-1]: FAILED! => {"changed": false, "failed": true, "msg": "Local modifications exist in repository (force=no)."}
```
Local changes to that nodejs/node repo is expected, as the github-bot continously tries to backport PR patches onto staging branches. Therefore simply avoiding this error by not trying to update that git repo at all when the playbook is run -- as long as it is present, we are happy.
Refs the ansible git module docs: http://docs.ansible.com/ansible/git_module.html#options

github-bot: dont update nodejs/node repo

---

setup/aix61/manualBootstrap.md

Setting the LIBPATH for curl breaks it for other programs (e.g. python), so we
need to only set it for the commands that need it.
cc/ @mhdawson

doc: update AIX curl instructions

---

setup/aix61/manualBootstrap.md

We currently need to manually add the IPV6 loopback address.
Fixes: https://github.com/nodejs/build/issues/721
cc/ @mhdawson

doc: add IPv6 localhost instructions

---

ansible/inventory.yml

Fixes: https://github.com/nodejs/build/issues/752
Not really sure why the user is `iojs` rather than root here, is that intended?

ansible: add requireio-osx1010-x64-1 to inventory

---

setup/windows/vcbt2015-ansible-playbook.yaml

The existing link to visual studio build tools 2015 is broken. Updated
with new link and tested on windows 7 and windows 10

ansible: update windows link to vcbt2015

---

setup/centos6/README.md
setup/centos6/ansible-playbook.yaml
setup/centos6/host_vars/_tmpl
setup/centos6/resources/jenkins.sysconfig
setup/centos6/resources/jenkins.sysconfig.j2

ref https://github.com/nodejs/build/issues/718
Also added these 2 release machines to ci-release and gave them a label `post-8-release` and added the following to the iojs+release scripting:
```bash
if [[ \
$OSTYPE =~ linux && \
$ARCH =~ x86_64|x64|i386|x86|ia32 && \
( \
( ${NODE_VERSION:0:1} -gt "7" && ! $NODE_LABELS =~ post-8-release ) || \
( ${NODE_VERSION:0:1} -lt "7" && $NODE_LABELS =~ post-8-release ) \
) \
]]; then
echo "Not building Node.js ${NODE_VERSION:0:1} on $NODE_NAME"
exit 0
fi
```

Update CentOS6 support, add support for release nodes

---

setup/www/resources/config/nodejs.org

This enables English fallback for files not translated to French, Catalan, and Galitian.
Refs: https://github.com/nodejs/nodejs.org/issues/1318

www: enable fallback for French, Catalan, and Galitian locales

---

ansible/inventory.yml
ansible/plugins/inventory/nodejs_yaml.py

/cc @mcollina 
fixes #791
In rotation @ https://ci.nodejs.org/computer/test-nearform_intel-ubuntu1604-x64-1/ and https://ci.nodejs.org/computer/test-nearform_intel-ubuntu1604-x64-2/ now and are part of node-test-commit-linux under the new ubuntu1604-intel-64 label (e.g. https://ci.nodejs.org/job/node-test-commit-linux/11267/nodes=ubuntu1604-intel-64/).
As they are intended ultimately for benchmarking work, this usage is temporary and they'll be moved out of that configuration when there's new work set up for them to do. In the meantime they are making themselves useful!

Add Intel/nearForm boxes to Ansible

---

README.md
doc/access.md
doc/process/jenkins_job_configuration_access.md

Initial stab at covering who has access to what.
Follow-on proposal: we could create sub-teams of @nodejs/build to list the groups of people who have access to things (which saves having lists of names in this document). I think it's just `nodejs/infra-admins` (which have access to `release-*` and `infra-*`) but I'm not sure.
Refs: https://github.com/nodejs/build/issues/798#issuecomment-316045678

doc: add a powers.md to document who has access

---

setup/github-bot/resources/environment-file

These $ENVs are needed for @nodejs-github-bot to kick off Jenkins builds based off PR comments. 
P.S. these are already present on the bot server in production.
Refs https://github.com/nodejs/github-bot/pull/128

github-bot: add Jenkins $ENVs to kick off builds for CITGM

---

README.md
doc/access.md
doc/process/joining_the_build_wg.md

Also adds a quick intro to joining, and also notes that you can request additional access to things as necessary.
I considered adding another section for [`Jenkins Admins`](https://github.com/orgs/nodejs/teams/jenkins-admins/members), but haven't done that yet. Opinions welcome!
Fixes: https://github.com/nodejs/build/issues/826

Add subteams

---

ansible/roles/baselayout/tasks/partials/repo/centos5.yml
ansible/roles/baselayout/tasks/partials/repo/centos6.yml
ansible/roles/baselayout/tasks/partials/repo/centos7.yml
ansible/roles/jenkins-worker/vars/main.yml

I just got caught by this setting up a replacement for test-packetnet-centos7-arm64-1 which has been borked a lot recently (seems to be some bad hardware problems because I tried to do a reboot again which has worked in the past but it's locked up and I've had to contact packet.net support about it—I've had more success in their non-CA datacenters so I switched to their NJ one for this).
I don't know what's changed but `ccache` isn't available for plain install on CentOS 7 on packet.net any more. Perhaps it's something new in CentOS 7.3 or perhaps packet.net used to bundle EPEL automatically but now doesn't. Anyway, it's now installing it manually in this PR and is confirmed working on the new test-packetnet-centos7-arm64-1.
btw there's a note in the CentOS 6 setup about adding EPEL, …

Add EPEL to centos7

---

ansible/roles/baselayout/tasks/main.yml

This allows for controlling core files limits per process (e.g per
tests).
Ref: https://github.com/nodejs/node/pull/14013

switch from global to per-process core dumps on SmartOS

---

setup/windows/README.md
setup/windows/vcbt2015-ansible-playbook.yaml
setup/windows/vs2013-ansible-playbook.yaml
setup/windows/vs2015-ansible-playbook.yaml

A few small updates, tested when deploying `test-rackspace-win2012r2-x64-8`:
- Use the new key names in host_vars
- Ignore certificates, necessary with new version of pywinrm
- Reboot indentation fix
- Use static imports for common
cc @refack @kunalspathak @piccoloaiutante

win: updates for Ansible 2

---

README.md

Makes it more obvious that we sort like that.
Takes inspiration from [the nodejs/node README](https://github.com/nodejs/node/blob/master/README.md#collaborators).

doc: list users by GitHub ID rather than name

---

README.md

Hi all, I have been asking for help a lot on the build IRC lately (regarding benchmark CI configurations and core CI jobs). Had a chat with @refack and I was suggested to join the working group. I'd love to get more involved.
cc @nodejs/build

Request to join the build WG

---

ansible/inventory.yml
ansible/roles/baselayout/vars/main.yml
ansible/roles/java-base/tasks/main.yml
ansible/roles/java-base/vars/main.yml

There's some stuff in here for ubuntu1204 and we may be removing that (see https://github.com/nodejs/build/issues/961)
fedora 22->24 are having some problems with fetching updates cause they are EOL, seem to be OK on DigitalOcean because I guess they have a local mirror.
Java updates as per notes in #775, this formalises the debian and ubuntu items in that list, the rest still need doing.
The fontconfig stuff in here should fix #937
Also worth noting that I've run these scripts across all the machines multiple times now, and unless something fails in CI, that means our scripts are idempotent! `ansible-playbook playbooks/jenkins/worker/create.yml --limit test-*ubuntu*-x*,test-*fedora*,test-*debian8-x*`

libfontconfig, java 8, other minor ansible fixes for fedora, debian, ubuntu

---

ansible/README.md

I actually needed to do this PYTHONPATH thing despite having installed
through `pip`, so worth documenting in the README.

ansible: document how to use ansible with brew

---

README.md

@nodejs/build we've been having private discussions with Intel about their hardware contributions and how best to acknowledge it—they have donated two physical boxes now hosted at nearForm, for benchmarking/perf work, which we are immensely thankful for of course. It raises some interesting questions about how far we go with putting marketing content into our README that I think we should discuss together. @mhdawson and I have been doing so privately in the context of this, and he has taken the lead primarily on updating this list and the associated graphic as well as our promotion of our providers across our various channels (this repo, twitter and in conference talks).
Keeping in mind that we entirely use donated resources and provide (soft) commitments to co-promote with our donors to …

doc: update intel text in providers list (meta: negotiating wording for donor descriptions & contributions)

---

setup/centos6/ansible-playbook.yaml
setup/centos6/ansible-vars.yaml
setup/centos6/resources/jenkins.sysconfig.j2
setup/centos6/resources/start.sh

Currently CentOS 6 machines use gcc 4.8 while Node.js requires "gcc and g++ 4.9.4 or newer". See #762.
`devtoolset-3` has gcc 4.9.1, too old.
`devtoolset-5` has "gcc (GCC) 5.3.1 20160406", that's still older than gcc 4.9.4.
`devtoolset-6` has "gcc (GCC) 6.3.1 20170216", good enough.
The CERN repo doesn't have `devtoolset` newer than 2, so I replaced that with Software Collections.

ansible: use gcc 4.9 on CentOS 6

---

ansible/roles/baselayout/vars/main.yml

Used by CitGM:
```
> phantomjs-prebuilt@2.1.16 install /home/iojs/build/workspace/citgm-smoker/nodes/fedora-latest-x64/citgm_tmp/4ad209ec-9e2f-4cc4-9d0f-772b05fb6f59/eslint/node_modules/phantomjs-prebuilt
> node install.js
PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /home/iojs/build/workspace/citgm-smoker/nodes/fedora-latest-x64/citgm_tmp/4ad209ec-9e2f-4cc4-9d0f-772b05fb6f59/npm_config_tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...
Received 22866K total.
Extracting tar contents (via spawned process)
Error extracting archive
Phantom installation failed { Error: Command failed: tar jxf /home/iojs/build/workspace/citgm-smoker/nodes/fedora-latest-x64/citgm_tmp/4ad209ec-9e2f- …
```

add `bzip2` to fedora baselayout

---

setup/www/resources/config/nodejs.org

Ref: https://github.com/nodejs/nodejs.org/issues/1349
I also removed all legacy redirects for foundation member logos, as they are now handled exclusively by the Foundation editorial team.

Rewrite Foundation resources to https://foundation.nodejs.org

---

setup/www/resources/config/nodejs.org

Ref: #1005 
@rvagg Sorry, had to fix an issue and optimized some rules. Please review:
- Fixed `^/en/foundation` overruling subsequent redirects
- Simplified some RegExp (just checking for beginning of a string)
- Added `/?$` to some rules to be more explicit

Fix Foundation redirects

---

ansible/README.md
ansible/inventory.yml
setup/github-bot/resources/environment-file

Providing `$JENKINS_WORKER_IPS` environment variable at startup will activate the whitelist implemented in the bot, validating who's allowed to pushed Jenkins job updates as inline PR statuses on github.com.
Refs https://github.com/nodejs/github-bot/pull/142
/cc @nodejs/github-bot

github-bot: add IPs of Jenkins workers

---

setup/ansible-inventory
setup/cross-compiler/README.md
setup/cross-compiler/ansible-playbook.yaml
setup/cross-compiler/ansible-vars.yaml
setup/cross-compiler/host_vars/.gitignore
setup/cross-compiler/resources/cc-armv6.sh
setup/cross-compiler/resources/cc-armv7.sh
setup/cross-compiler/resources/set-rpi-cc.sh

Currently supports Raspberry Pi 1. Based on Ubuntu 14.04.

setup: add cross compiling machine

---

ansible/inventory.yml
setup/github-bot/resources/environment-file

cc @rvagg, this broke because of new jenkins workspace machine being added

ansible: update for new jenkins-workspace machine

---

README.md

Been doing a bunch of work on the bot related to pull request status
lights, and would be helpful to have elevated permissions. For example,
Ansible permissions were needed to roll out
https://github.com/nodejs/build/pull/1054.
cc @phillipj

doc: add maclover7 to github bot admin list

---

jenkins/scripts/coverage/README.md
jenkins/scripts/coverage/gcovr-patches.diff
jenkins/scripts/coverage/generate-index-html.py
jenkins/scripts/coverage/patches.diff

Tried to copy over original Git history, so that way there's a papertrail.
Will update Jenkins once this lands.
cc @addaleax (primary author) @cjihrig @Trott

Add coverage generation files from nodejs/testing

---

README.md

Anything stored in GitHub will still be available in the Git history.
Fixes: https://github.com/nodejs/build/issues/926

doc: note that release config is removed after 6m

---

jenkins/scripts/node-update-v8-canary.sh

Used in https://ci.nodejs.org/view/All/job/node-update-v8-canary
cc/ @targos

jenkins: add node-update-v8-canary script

---

ansible/inventory.yml
ansible/roles/docker/tasks/main.yml
ansible/roles/docker/templates/alpine34.Dockerfile.j2
ansible/roles/docker/templates/alpine35.Dockerfile.j2
ansible/roles/docker/templates/alpine36.Dockerfile.j2
ansible/roles/docker/templates/alpine37.Dockerfile.j2
ansible/roles/docker/templates/ccache_config.j2
ansible/roles/docker/templates/jenkins.service.j2
ansible/roles/docker/templates/ubuntu1604.Dockerfile.j2
ansible/roles/docker/templates/ubuntu1604_sharedlibs.Dockerfile.j2
ansible/roles/docker/templates/ubuntu1804.Dockerfile.j2

These are operational in CI now, see https://ci.nodejs.org/job/node-test-commit-linux-linked/1131/ for master and https://ci.nodejs.org/job/node-test-commit-linux-linked/1133/ for v4.x.
Next up libuv, cares and nghttp2 .. maybe http-parser, but I'm not sure anyone's actually using that shared functionality.

docker: add openssl 1.0.2 and zlib

---

jenkins/scripts/node-update-v8-canary.sh

The job should fail if compilation fails or node is deeply broken.
@gibfahn Can you help changing the job config to execute this script?

jenkins: check node build in node-update-v8-canary

---

ansible/roles/baselayout/vars/main.yml

otherwise there's no symlinks for `g++` and `c++` in /usr/lib64/ccache and it gets bypassed even when using devtoolset-2 binaries
fixed on the hosts that need it

ansible: install gcc-c++ on centos6 so ccache picks it up properly

---

setup/github-bot/resources/environment-file

Updating one of the jenkins worker IPs has it has changed.
Seeing quite a lot of these in the bot logs:
```bash
WARN bot: Ignoring, not allowed to push Jenkins updates (req_id=4d597e22-8cf3-47ed-915d-a2c35116dd78, ip=147.75.70.237)
```
Refs https://github.com/nodejs/build/commit/78bdb8596ef2c336d54d0ee180247488e6722c6f
/cc @rvagg

github-bot: update jenkins worker IP

---

setup/www/resources/config/nodejs.org

The URLs are recommended by the security.txt spec available at https://securitytxt.org.
The security.txt file was added to the static directory in a separate PR: nodejs/nodejs.org#1589.

Serve security.txt file from the static directory

---

jenkins/scripts/node-test-commit-diagnostics.sh
jenkins/scripts/node-test-commit-pre.sh

They can't handle the -p option, and give the following error:
```console
$ netstat -anp
netstat: option requires an argument -- p
Usage:  netstat [-AaLlnW] [-f address_family | -p protocol]
netstat [-gilns] [-f address_family]
netstat -i | -I interface [-w wait] [-abdgRtS]
netstat -s [-s] [-f address_family | -p protocol] [-w wait]
netstat -i | -I interface -s [-f address_family | -p protocol]
netstat -m [-m]
netstat -r [-Aaln] [-f address_family]
netstat -rs [-s]
```

Update diagnostics script to handle FreeBSD and macOS

---

doc/non-ansible-configuration-notes.md

Even after custom compiles if openssl+libcurl+git centos5 isn't quite right, it turns out that we need a more modern version of ssh too otherwise github rejects git@ connections `no kex alg`. So I've also added instructions for compiling a new version of openssh to the list and this appears to work.

doc: openssh required on centos5 for git to access private repos

---

setup/www/resources/config/nodejs.org

Turns out node was linking to nodejs.org/en/docs/inspector.
This fixes the redirect as well.
Ref: nodejs/nodejs.org#1619

nginx: Redirect old inspector docs (node executable)

---

ansible/inventory.yml
ansible/roles/baselayout/tasks/main.yml
ansible/roles/baselayout/vars/main.yml
ansible/roles/jenkins-worker/tasks/main.yml
ansible/roles/jenkins-worker/templates/jenkins_manifest.xml.j2
ansible/roles/jenkins-worker/vars/main.yml

I've provisioned 2 test and 1 release smartos 17 machines and this is the required changes for ansible to get it set up. The only iffy bit that I bet there's a better answer for is the gcc7 links into /opt/local/bin, it's strange that there aren't links by default and there must be some kind of equivalent to debian style "alternatives". It works at least.
I've got rules in place to make Node >=10 binaries build on smartos 17, 64-bit only from 10 onward like for linux.
[VersionSelectorScript.groovy](https://github.com/nodejs/build/blob/rvagg/VersionSelectorScript.groovy/jenkins/scripts/VersionSelectorScript.groovy) now has the following:
```groovy
if (builderLabel.indexOf('smartos14') == 0 && nodeMajorVersion >= 8)
return false
if (builderLabel.indexOf('smartos15') == 0 && nodeMajorVersion …
```

ansible: smartos17

---

ansible/roles/baselayout/vars/main.yml

Certain versions of node require binutils version 2.26 (https://github.com/nodejs/build/issues/1229)
This won't affect the default installation of binutils.
To use it, add the following to PATH.
/usr/lib/binutils-2.26/bin/
fyi, @mhdawson

install binutils-2.26 on ubuntu

---

ansible/roles/baselayout/files/debian8-ubuntu-trusty-apt-preferences
ansible/roles/baselayout/tasks/partials/repo/debian8.yml
ansible/roles/baselayout/vars/main.yml

Same as https://github.com/nodejs/build/pull/1235 but for Debian 8, unfortunately I have to pull in trusty-updates for jessie but set the priority low for all of the packages from there so we only pull in binutils-2.26 and nothing else.

ansible: binutils-2.26 for debian8 using trusty-updates

---

setup/www/tasks/user.yaml
setup/www/tools/promote/promote_nightly.sh
setup/www/tools/promote/settings

Node-ChakraCore will release its version 10 tomorrow simultaneously with Node-V8, hence RC builds are necessary for testing. This adds the necessary changes to `www`.
This is already in the server and the first build is available at https://nodejs.org/download/chakracore-rc/v10.0.0-rc.0/ .
This PR also removes two duplicate entries for `chakracore-nightly`.

Release Candidate support for Node-ChakraCore

---

ansible/roles/bootstrap/tasks/partials/debian7.yml
ansible/roles/package-upgrade/tasks/partials/apt.yml

move common `apt` task out of debian specific task

---

jenkins/scripts/VersionSelectorScript.groovy

Following on from https://github.com/nodejs/build/issues/1153
node-version-jenkins-plugin is now installed on ci.nodejs.org and is being used in node-test-commit-linux-arm, node-test-commit-linux-containered and node-test-commit-linux to select the right builders to run. So we have some ARM and containered specific options in here. The script also has a "buildType"  so that it can do slightly different things for release as for test (and other), e.g. centos6 shouldn't be used for Node 4 in release but it should be used for everything for test.

added VersionSelectorScript.groovy to select builders for Node version

---

jenkins/scripts/node-update-v8-canary.sh

The `update-v8` command was moved to that project.

jenkins: use node-core-utils to update V8 canary

---

setup/github-bot/resources/environment-file

Refs: https://github.com/nodejs/github-bot/pull/173
Refs: https://github.com/nodejs-private/secrets/pull/19
@phillipj, or anyone else on the infra team, would you be able to roll this (and the secrets PR) out together? I don't have access to the github-bot server

github-bot: add node jenkins variables

---

doc/services.md

A thorough explanation of everything the Build WG is responsible for,
and where configuration lives.
Up next will be a soup-to-nuts guide on how to operate our Jenkins
cluster.
cc @Trott @nodejs/build

doc: add services.md

---

ansible/playbooks/jenkins/worker/create.yml
ansible/roles/linux-perf/tasks/main.yml
ansible/roles/linux-perf/vars/main.yml

Ansible role to install Linux perf on Ubuntu by cloning the Linux source
code and building tools/perf to avoid Kernel mismatch errors.
I wasn't sure which playbook should call this role, so I'm submitting only 
the role for now.
Tested on Ubuntu 16.04 from DigitalOcean.
Ref: https://github.com/nodejs/build/issues/1274

ansible: add role to install Linux perf on Ubuntu

---

jenkins/scripts/VersionSelectorScript.groovy

`pi1-docker` builds are failing on ci-release for 10+ (i.e. nightly/master too). The reason it's failing is that the v10 and master branches aren't available in the git shared reference repo, which is updated @ https://ci.nodejs.org/view/All/job/git-nodesource-update-reference/ (at least I'm fairly sure this is related). I'll update that _but_ it shouldn't even be running on ci-release because we use the cross-compiler for Node 10+ now for armv6 and armv7, no pi1-docker necessary. I thought we took this out of action already but perhaps we've been trying to push releases with this for some time now? I'm not sure about the history here and why we're in a failing state now, I'm pretty certain that this wasn't happening when we first release 10.0.0, maybe it was a slip-up in …

jenkins: don't run pi1-docker for releases on 10+

---

ansible/inventory.yml
ansible/roles/bootstrap/tasks/partials/raspberry-pi.yml
ansible/roles/jenkins-worker/tasks/partials/raspberry-pi.yml
ansible/roles/jenkins-worker/templates/rpi_rc.local.j2
ansible/roles/jenkins-worker/vars/main.yml

* migrated the remaining pi's to the new dockerized setup
* mounted /boot/ on all of the nfs-root pi's so any updates get pushed back into the tftp nfs server
* minor fixes
interesting thing happened with this though, one of the Pi's, the last of the Pi 1 B+'s (number 14 according to how I number them, and one of the most recently purchased ones so it's not ancient) test-requireio_davglass-debian9-armv6l_pi1p-1 won't stay running while nfs booted. I've updated firmware, tried using a "next" branch bootloader, all sorts of things but I can't stop it from doing a kernel panic fairly soon after starting up. So I've left it with a classic SD card setup, but it's the only one out of all of them. Pretty strange. Good chance to get these scripts working for both nfs-booted and SD card booted …

ansible: rpi updates, completed conversions to new format

---

doc/access.md

jenkins-release-admins has admin access to ci-release.nodejs.org,
not jenkins-admins.

doc: correct the access documentation of jenkins

---

jenkins/pipelines/node-linter.jenkinsfile

Works as a pipeline-ified version node-test-linter. When this lands, will
convert node-test-commit to call this pipeline, instead of node-test-linter.

jenkins: add node-linter

---

ansible/roles/jenkins-worker/tasks/main.yml

Adds an `unload` from `launchctl`, so the Jenkins agent on OSX will
always restart.
cc @gdams

ansible: restart OSX agent

---

ansible/README.md
ansible/playbooks/create-github-bot.yml
ansible/roles/github-bot/tasks/main.yml
ansible/roles/github-bot/templates/deploy-github-bot.sh.j2
ansible/roles/github-bot/templates/environment-file.j2
ansible/roles/github-bot/templates/github-bot-deploy-webhook.json.j2
ansible/roles/github-bot/templates/github-bot-deploy-webhook.service.j2
ansible/roles/github-bot/templates/github-bot.service.j2
ansible/roles/github-bot/vars/main.yml

This is a migrated version of the playbook that lives in `setup/github-bot`.
I have tested this on the production server, and works good.
I will be removing the `setup/github-bot` directory in a later PR, to avoid a smaller diff.
cc infra admins: @gibfahn @jbergstroem @joaocgreis @mhdawson @rvagg 
cc @phillipj

ansible: introduce create-github-bot playbook

---

README.md

One member would like to be pinged on SmartOS only things, and the other
has been removed due to inactivity. Both already are gone from
the `nodejs/build` and `nodejs-private/build` GitHub teams

doc: update members list

---

ansible/roles/github-bot/tasks/main.yml
ansible/roles/github-bot/templates/deploy-github-bot.sh.j2

Turns out #1382 was not the right fix, the issue was that the `iojs`
user did not have proper privileges to run the command, not the command
itself.

github-bot: fix privilege for iojs user

---

jenkins/pipelines/node-linter.jenkinsfile

* break down directive into single commands
* don't fail if `lint-md-build` doesn't exist
* replace `sed` with `awk`

jenkins: linter refactor & fix for 6.x

---

ansible/roles/jenkins-worker/tasks/main.yml

ansible_processor_vcpus is known to be busted on DigitalOcean for FreeBSD so we have to have a sensible fall-back
I haven't tested this on another type of machine yet, that probably needs to be done before merging!

ansible: make server_jobs work on FreeBSD in DigitalOcean

---

ansible/inventory.yml
ansible/roles/baselayout/tasks/main.yml
ansible/roles/java-base/tasks/main.yml
ansible/roles/package-upgrade/tasks/partials/brew.yml

FYI @mhdawson this machine currently has the test keys on in rather than release so this will need changing. I had to fixup a few bugs in the playbook but this has now been run on the machine so it should be good to add to ci-release.

add release-macstadium-macos10.11-x64-1

---

ansible/inventory.yml

This machine no longer exists so should be removed from the inventory.

ansible: remove test-ibm-aix61-ppc64-1 from inventory

---

jenkins/pipelines/post-build-status-update.jenkinsfile

* Add timeout to `post-build-status-update`
* Switch from shelling out `curl` to `httpRequest`
---
Jenkins got stuck on a status update [job](https://ci.nodejs.org/job/post-build-status-update/464751/) (it run for 1:27 hours), so I changed the script ad-hoc.
Please review.

ci-change: timeout in post-build-status

---

jenkins/pipelines/llnode-pipeline.jenkinsfile
jenkins/scripts/common/colors.sh
jenkins/scripts/common/getLLDB.sh
jenkins/scripts/common/getNode.sh
jenkins/scripts/common/helpers.sh
jenkins/scripts/llnode-continuous-integration.sh

The llnode CI isn't working right now, but hopefully by committing this
we can then iterate in GitHub.
This also makes the node download script runnable manually, and adds docs for it.
@joyeecheung I was thinking if we land this, you can raise a PR to build, and build the jobs directly from your PR. Thoughts?

jenkins: add llnode pipeline and shell scripts

---

jenkins/scripts/select-compiler.sh

Allow NODE_MAJOR_VERSION to be set externally

jenkins: refactor to allow external node version

---

doc/non-ansible-configuration-notes.md

found this in my commit queue, discovered a few weeks back when the dist.libuv.org cert didn't renew. It turns out that `--manual` doesn't allow for auto-renewal with certbot, you have to use `--nginx`, which is unfortunate, but it works and is apparently safe for our config.

www: letsencrypt --manual doesn't allow auto-renew, use --nginx

---

jenkins/scripts/VersionSelectorScript.groovy

14.04 ends its standard support lifetime in April 2019.
However, they have announced that they're doing an extended-LTS (paid) for 14.04 like they did for 12.04. Word is that extended-LTS turned out to be quite profitable for them so it's no surprise.
No EOL date for that yet afaik but I think we can assume it'll be another 3 years.
So an argument could be made that we should continue to test our builds on 14.04 until then. However, without support from Canonical (I've tried, to no avail), we won't get access to the extended LTS repos and we persist the support burden on the Build team. The latter concerns me the most so I'm in favour of a slightly more aggressive pruning policy than we've adopted in the past.

jenkins: remove ubuntu 14.04 from Node 12+

---

ansible/plugins/inventory/nodejs_yaml.py

Old style exceptions are syntax errors in Python 3 but new style exceptions work as expected in both Python 2 and Python 3.  @rvagg Your review please?

Old style exception --> new style for Python 3

---

ansible/inventory.yml

Lost access to existing smartos15 host, something's up with ssh keys, maybe related to their custom ssh SDC setup 🤷‍♂️. New host provisioned and seems to be working fine. I'll delete the old one when I can confirm Node 6 * 8 build OK (in progress).
A couple of problems encountered:
1. I can't use Python 3 with this, roles/baselayout/tasks/ccache.yml does some jinja2 stuff that doesn't work:
```
- name: "ccache : extract ccache latest version"
set_fact:
ccache_latest: "{{ ccache_html_content.stdout | regex_findall('ccache-[0-9]+.[0-9]+(?:.[0-9]+)*.tar.gz') | map('regex_replace', 'ccache-') | map('regex_replace', '.tar.gz') | list | latest_version }}"
```
yields:
```
fatal: [release-joyent-smartos15-x64-1]: FAILED! => {"msg": "Unexpected templating type error occurred on ({{ …
```

ansible: new smartos15 release host

---

ansible/roles/baselayout/vars/main.yml

ansible: python3 for freebsd (for linting)

---

doc/jenkins-guide.md

So that it also displays nicely in the job page.
Before:
After:

doc: update the security embargo banner style

---

setup/www/tools/promote/expected_assets/v11.x

Refs: https://github.com/nodejs/node/pull/22405
Refs: https://github.com/nodejs/node/pull/25019

assets: additional asset for v11.x

---

jenkins/scripts/VersionSelectorScript.groovy

See: https://github.com/nodejs/node/pull/26209#issuecomment-469777736

jenkins: openssl1.1.0 not supported on node.js 12+

---

ansible/roles/bootstrap/tasks/partials/raspberry-pi.yml
ansible/roles/bootstrap/vars/main.yml
ansible/roles/java-base/tasks/main.yml
ansible/roles/jenkins-worker/tasks/partials/docker-host.yml
ansible/roles/jenkins-worker/tasks/partials/raspberry-pi.yml
ansible/roles/jenkins-worker/vars/main.yml

two things in one while trying to get RPi reprovisions done:
1. there's new code from earlier this month in 85c9a8635cbf35569f7e6a222608313ef8527f1c that does an AIX-specific check for Java _only_ if running AIX, then later it checks the contents of that check to determine if it should install Java, also checking if running AIX but it does it in that order. So if you're not running AIX, it won't run the new check for Java but it will require the results of that check. Switched ordering of conditional to fix.
2. Brought nfs mounting of /boot/ of the RPis much earlier in the setup process so it's before the initial `apt-get upgrade`. Assets from an upgrade impacting /boot/ can leave the system out of sync, e.g. booting on an older kernel and not having the /lib/modules/x.x.x for it anymore. …

AIX & RPi fixes

---

setup/www/tools/promote/check_assets.js

Manually edited #1673 into the file in question with vim and it made a newline at the end and check_assets.js borked on it. I made it originally with an editor that didn't append that last line so this wasn't a problem.

www: check_assets.js should allow for blank lines in expected assets list

---

ansible/inventory.yml

we were asked to move off a "beta" region that we'd made these instances in, so we're back to us-east-1 for these, they're confirmed working in ci and ci-release

ansible: new instances for release smartos15 and test smartos17

---

.gitignore
tools/jenkins-status/jenkins-status.js
tools/jenkins-status/package-lock.json
tools/jenkins-status/package.json

First commit:
fix jenkins-status script
The script is broken and has been for a long time (since we made GitHub
auth mandatory to view stuff). This fixes it if and only if you have
node-core-utils configured to interact with Jenkins. Obviously, there is
room for improvement, but this takes it from "does not work at all" to
"ok, it works now at least if you've configured node-core-utils".
The alternative to maintaining the script is removing it. Seems like it
is/could be useful so keep it and land this, yeah?
Second commit:
make jenkins-status.js verbose
Last commit:
apply standard linting to jenkins-status.js
There are no tests or linting for jenkins-status.js. The code style
seems to mostly conform to `standard` so let's add standard linting.

Fix jenkins status

---

ansible/roles/github-bot/tasks/main.yml

It's been a while since we setup the github-bot initially and a few Node.js major releases has been cut since then..
Thought we better settle on current LTS for now.
/cc @nodejs/github-bot

github-bot: update Node.js from 6 -> 10

---

ansible/inventory.yml

I've turned this off in DO (not destroyed) to see if anyone/anything yelps. It's an InfluxDB + Grafana server that @jbergstroem set up some time ago but I don't believe we ever hooked it up to collect stats for us. I've also turned off an old www server that I believe is redundant now.
Please yelp if you have a reason either of these shouldn't be destroyed.

ansible: remove infra "collector"

---

ansible/README.md
ansible/host_vars/test-marist-zos13-s390x-template
ansible/inventory.yml
ansible/playbooks/jenkins/worker/create.yml
ansible/roles/baselayout/tasks/ccache.yml
ansible/roles/baselayout/vars/main.yml
ansible/roles/gcc/tasks/main.yml
doc/non-ansible-configuration-notes.md
doc/ssh.md
jenkins/scripts/select-compiler.sh

Machines updated: Update linux s390 gcc

---

jenkins/scripts/select-compiler.sh

Depends on https://github.com/nodejs/build/pull/1755

Use devtoolset-6 for s390x on node gt 11.x

---

jenkins/scripts/VersionSelectorScript.groovy

Unfortunately I need this in before I can hook centos7 up to ci-release and get the nightlies working again. If I hook up centos7 before this goes in then it'll try building other release lines. Review would be great but I might have to expedite this one tomorrow regardless.

jenkins: exclude centos7 for release < Node 12

---

jenkins/scripts/VersionSelectorScript.groovy

We still need `centos7-arm64-gcc48` for node 8

jenkins: more specific centos7 exclude

---

jenkins/scripts/VersionSelectorScript.groovy

Ref #1730
We need to switch to Linux for creation of our generic tarballs and 12 is the time to get it done. Here's my strategy and I'd like some sanity checking before I put it into effect for nightlies.
* Current strategy piggy-backs the `osx1010-release-tar` and `osx1011-release-tar` labels, these are also used for creating the `darwin` binary tarballs so we'll leave them as they are
* I've added labels `osx1010-release-sources` and `osx1011-release-sources` to the existing osx release machines, I've also added `centos7-release-sources` to the new centos7-64 release machine.
* I'll add all 3 of these new labels to iojs+release and VersionSelectorScript here should take care of selecting the right one.
* The iojs+release job has a dedicated block for doing this work, it comes under a …

jenkins: new "release-sources" labels for source, headers, docs

---

ansible/roles/cross-compiler/files/cc-selector.sh
jenkins/scripts/VersionSelectorScript.groovy

I now have GCC 6.5.0 and GCC 8.3.0 @ https://github.com/rvagg/rpi-newer-crosstools, which is already cloned to /opt/raspberrypi/rpi-newer-crosstools/ on the cross compiler machines (it needs an update). This update allows workers with new labels like "cross-compiler-armv7-gcc-6" to select GCC 6 for ARMv7. It still allows ARMv6 even though we're dropping that for Node 12, and we also don't need GCC 8 support yet but we get some flexibility here for experimentation.
I'd appreciate some sanity checking on the VersionSelectorScript before I merge this to try and avoid the problems with centos7 that I caused yesterday. Note the labels we currently use: https://ci.nodejs.org/view/All/job/node-cross-compile/, we'll also add "cross-compiler-armv7-gcc-6" to that list.

ARM cross compiler GCC 6 for Node >= 12

---

ansible/inventory.yml
ansible/roles/baselayout/tasks/ccache.yml
ansible/roles/baselayout/vars/main.yml
ansible/roles/jenkins-worker/meta/main.yml
ansible/roles/jenkins-worker/tasks/main.yml
ansible/roles/jenkins-worker/vars/main.yml
jenkins/scripts/VersionSelectorScript.groovy

Got the machines provisioned, won't be active until we get the versionselectorscript changes in place though.
Picked up a couple of strange removals from #1723, probably just typos or debugging changes /cc @sam-github.

ansible,jenkins: smartos18 in ci and ci-release

---

jenkins/scripts/VersionSelectorScript.groovy

This one will remove Debian 8 from the ARMv7 mix for Node 12+. This is for node-test-commit-arm on the Scaleway ARMv7 machines, not the Raspberry Pi machines.

jenkins: exclude debian8 from armv7 tests for node 12+

---

ansible/roles/cross-compiler/vars/main.yml

a piece missing from #1776, this has been done on the 3 cross compiler machines.

ansible: gcc-6 host compiler packages for cross machines

---

ansible/inventory.yml
ansible/roles/jenkins-worker/templates/jenkins_manifest.xml.j2
ansible/roles/jenkins-worker/vars/main.yml

2 things in here:
1. Change the default `JOBS` on smartos to 4 since we are mostly using 4-cpu machines there (this is needed because ansible has trouble determining the number of CPUs on smartos). I've re-run ansible on smartos17 and smartos18 machines and restarted them so this is in effect. It should deal with at least some of the slowness (/cc @refack).
2. Reprovisioned test-smartos18-2 and release-smartos18-1 because, yet again, I didn't put the right ssh keys in authorized_keys and our Ansible scripts blow away the SmartConnect stuff that SmartOS uses by default so they became inaccessible.

ansible: default JOBS to 4 on smartos, reprovision 2 smartos18 machines

---

ansible/inventory.yml
ansible/roles/baselayout/tasks/partials/repo/centos7.yml
ansible/roles/baselayout/vars/main.yml

two things in one:
1. add centos7 machine for ci-release for node 12
2. fix up baselayout to set up scl for installing devtoolset-6, everything else is in place but this piece is missing but it will conflict with https://github.com/nodejs/build/pull/1763

ansible: release-centos7 and enable scl for devtoolset-6

---

ansible/inventory.yml
ansible/roles/baselayout/tasks/partials/repo/centos7.yml
ansible/roles/baselayout/vars/main.yml
ansible/roles/java-base/tasks/main.yml
jenkins/scripts/VersionSelectorScript.groovy
jenkins/scripts/select-compiler.sh

- Add the repository for devtoolset-6.
- Do not use the "ius" repository, it doesn't support ppc64, and was not
necessary.
Fixes: https://github.com/nodejs/build/issues/1705

Add support for Centos7/ppc64

---

ansible/plugins/inventory/nodejs_yaml.py

[flake8](http://flake8.pycqa.org) testing of https://github.com/nodejs/build on Python 3.7.1
$ __flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics__
```
./ansible/plugins/inventory/nodejs_yaml.py:213:44: F632 use ==/!= to compare str, bytes, and int literals
delimiter = "_" if host.count('-') is 3 else "-"
^
./ansible/plugins/inventory/nodejs_yaml.py:268:8: F632 use ==/!= to compare str, bytes, and int literals
if len(info) is not 5:
^
2     F632 use ==/!= to compare str, bytes, and int literals
2
```

Use ==/!= to compare str, bytes, and int literals

---

ansible/inventory.yml
ansible/playbooks/create-unofficial-builds.yml
ansible/roles/docker/tasks/main.yml
ansible/roles/nginx/files/logrotate
ansible/roles/nginx/tasks/main.yml
ansible/roles/nginx/templates/unofficial-builds.nodejs.org.conf.j2
ansible/roles/unofficial-builds/files/deploy-unofficial-builds.sh
ansible/roles/unofficial-builds/files/nodejs-periodic.service
ansible/roles/unofficial-builds/files/nodejs-periodic.timer
ansible/roles/unofficial-builds/files/unofficial-builds-deploy-webhook.service
ansible/roles/unofficial-builds/tasks/main.yml
ansible/roles/unofficial-builds/templates/unofficial-builds-deploy-webhook.json.j2
ansible/roles/unofficial-builds/vars/main.yml

A new initiative, can be seen at http://github.com/nodejs/unofficial-builds/ and https://unofficial-builds.nodejs.org/
The intention is _not_ for this to be owned by Build, I don't think Build needs more work to do. I've outlined some thoughts on what it needs in order to succeed @ https://github.com/nodejs/unofficial-builds/issues/1 - and failure is left open as an option.
Anyway, this is just the single server that runs it all and it's here because they're all here. It's similar to github-bot in that respect.

ansible: unofficial-builds

---

ansible/roles/docker/templates/ubuntu1604.Dockerfile.j2
ansible/roles/docker/templates/ubuntu1604_sharedlibs.Dockerfile.j2
ansible/roles/docker/templates/ubuntu1804.Dockerfile.j2

https://pypi.org/project/tap2junit says that __tap2junit__ is compatible with legacy Python but says nothing about Python 3 compatibility.  Related to #1674

build: add python3-pip to ubuntu.Dockerfiles

---

jenkins/scripts/VersionSelectorScript.groovy

Stop doing releases on ppcle-ubuntu from 13.x onwards. For now, we still
run tests on ubuntu. We'll consider switching 12.x to use centos7
instead of ubuntu for building releases once we see the nightlies
working well on 13.x.

scripts: stop using ubuntu for 13.x ppcle releases

---

setup/aix61/resources/S20jenkins

Currently, it is inherited from the user that started Jenkins, which can
be `TERM=dumb` in some ssh environments. That value of TERM breaks some
of the terminal related tests, so ensure a consistent TERM value.
Fixes: https://github.com/nodejs/node/issues/28064

aix: set jenkins TERM to a consistent value

---

ansible/roles/baselayout/vars/main.yml
ansible/roles/jenkins-worker/tasks/partials/tap2junit/macos.yml

Been trying to figure this out on macos and it's a bit of a mess. The python formulas in brew have changed so I had to do a lot of manual manipulation to get everything set up the right way. I think this config should do it properly from scratch now though. I've run this against some existing 10.12 and 10.11 and it seems to work OK.
I've also gone around and made `tap2junit` work on them all, or at least `tap2junit -h` doesn't error. They're installed against python2 though so it's going to need work.
Here's the state of `python`, `python2`, `python3`, `pip`, `pip2` and `pip3` installed under /usr/local/bin:
```
$ parallel-ssh -h /tmp/macos.hosts -t 600 -i '/usr/local/bin/python --version > /tmp/pyver 2>&1 && /usr/local/bin/python2 --version >> /tmp/pyver 2>&1 && /usr/local/bin/python3 …
```

ansible: macos python2 & python3

---

ansible/roles/jenkins-worker/templates/aix.rc2.j2

AIX is PPC64 big endian (not little endian (LE)).
I'm not sure these even need to be set (I'd normally expect `ARCH` to come from the Jenkins job configuration). 
I've been asked to validate the AIX ansible scripts here and noticed this while re-familiarizing myself with them (and I even reviewed the original PR this landed in and missed this 😞).

ansible: fix AIX environment variables

---

ansible/roles/baselayout/tasks/partials/repo/centos7.yml
ansible/roles/baselayout/vars/main.yml
ansible/roles/jenkins-worker/tasks/partials/tap2junit/centos7.yml

Installs python3 in /opt/python-3.7/bin, as python3:
% /opt/python-3.7/bin/python3 --version
Python 3.7.3

Centos7 python 3.7

---

jenkins/scripts/select-compiler.sh

Start using devtoolset-6 to compile 10.x instead of gcc-4.9.
This will fix problems where gcc-4.9 builds either don't run on older
RHEL, or will run, but only after installing the gcc-4.9 runtime
libraries.
This has the effect of increasing the quality of platform coverage.

jenkins: 10.x/s390 building with devtoolset-6

---

ansible/ansible.cfg

Updating the jump host command, `-W` isn't working anymore due to some restrictions I've placed on the jump host but `nc` will work just fine now. Further to #1889.
This is not replacing `{{ ansible_ssh_private_key_file }}` in the .ssh/config output of playbooks/write-ssh-config.yml and hasn't been for a while but I don't know why. Would appreciate some help tracking this down if someone has time.

update arm jump host proxycommand

---

tools/build-p-ssh-hosts.sh

I'm exploring what of the nodejs/build inventory I can actually ssh into. I should have test and release access, but I don't have infra.
@rvagg I use parallel-ssh and hosts files pretty frequently, I suspect you do, too. I've been keeping my configs locally, but it might be worth sharing them.
1. How do you deal with hosts that throttle ssh connections? I have been seeing that a bunch... p-ssh fails to connect, but it works if I try manually :-(. Very frustrating. I'm currently attempting a work-around with `parallel-ssh -o pass -e fail -h ../release -h ../test -p 1 "echo CONNECTED && sleep 10"` which is quite slow. It occurs to me that randomizing the input host order might help, too.
2. should I replace all the `{{ ... }}` with the explicit path to my node test ssh key?
3. should I be …

tools: build parallel-ssh config files

---

jenkins/scripts/VersionSelectorScript.groovy

13.x has been releasing on centos7-ppcle for months. Start releasing
12.x on centos7-ppcle now. 10.x and below is not changed.
We get a supported operating system and expanded platform support:
1. The current release system, ubuntu14.04, has been EOL since April.
2. The devtoolset-6 compiler tools are available on centos7, and allow
building binaries that run on MORE old linux libc versions than the
current binaries build with gcc.

jenkins: release 12.x on centos7-ppcle

---

jenkins/scripts/VersionSelectorScript.groovy

We are intending to start building 10.x PPC releases on centos7 instead
of ubuntu. To prepare for this, start running the tests on centos7.

jenkins: test 10.x on centos7-ppc

---

jenkins/scripts/select-compiler.sh

10.x uses gcc-4.9 currently on ubuntu, but devtoolset-6 is a better
choice because it creates binaries that will run on older systems than
those created by ubuntu/gcc-4.9.
Since gcc-4.9 doesn't exist on centos7, ci is failing test builds
on centos7 for 10.x. Using devtoolset-6 will fix the failing builds.

jenkins: use devtoolset-6 on 10.x centos7-ppcle

---

jenkins/scripts/VersionSelectorScript.groovy

ci is passing tests with 10.x on centos7-ppcle, see #1918, so start
building releases on it.
@nodejs/lts

jenkins: release 10.x on centos7-ppcle

---

.flake8
.gitignore
ansible/plugins/inventory/nodejs_yaml.py
ansible/plugins/library/remmina_config.py
ansible/plugins/library/ssh_config.py
jenkins/scripts/coverage/generate-index-html.py
setup/www/tools/metrics/country-lookup.py

As requested at https://github.com/nodejs/build/pull/1399#issuecomment-522687404, this PR cherrypicks key modifications from #1399 to improve the Python 3 compatibility of our build process.
* __git checkout refack/pipenv+python3 -- .flake8 .gitignore ansible/plugins/library/remmina_config.py ansible/plugins/library/ssh_config.py setup/www/tools/metrics/country-lookup.py jenkins/scripts/coverage/generate-index-html.py__
* __code ansible/plugins/inventory/nodejs_yaml.py__
* cherrypick some change but not others
* sync __valid["arch"]__ with https://github.com/nodejs/node/blob/master/configure.py
* __flake8 .__  # placate flake8

ansible: improve Python 3 compatibility

---

.github/workflows/push.yml

Use GitHub Actions to lint Python code with flake8 on both Python 2 and Python 3.

build: on push GitHub Action to lint Python code

---

jenkins/scripts/select-compiler.sh

Because devtoolset setup works by putting the devtoolset bin/ on the
front of PATH the compiler is called directly instead of via the ccache
wrappers.
Change select-compiler.sh to explicitly use ccache, as it does for s390x.

jenkins: use ccache with devtoolset on ppc64le

---

setup/www/resources/config/nodejs.org

**Needs review and #1935**
I notice we have `https://nodejs.org/static/apple-touch-icon.png` or `https://nodejs.org/static/favicon.png`. This patch attempts to handle those requests and redirect them to the existent files.

Nodejs org redir

---

ansible/roles/baselayout/tasks/partials/repo/debian8.yml
ansible/roles/bootstrap/tasks/partials/debian8.yml

I reprovisioned test-rackspace-debian8-x64-1 due to some odd descripancies pointed out in https://github.com/nodejs/citgm/pull/751, I had to fix a few minor things to get it to run fully in ansible now that debian8 is EOL. I'm unsure if the descripancies are entirely sorted out, it's difficult to determine but maybe a citgm run or two could tell.
We should probably phase debian8 out, but I wasn't brave enough to just pull the rug unanimously, so restoring support was probably worthwhile.

ansible: update debian8 support

---

ansible/roles/baselayout/tasks/main.yml
ansible/roles/baselayout/vars/main.yml
ansible/roles/jenkins-worker/templates/start.j2

I'm not sure of the backstory here, this path was introduced in the original PRs:
Ref: https://github.com/nodejs/build/pull/971
Ref: https://github.com/nodejs/build/pull/1347
But afaik /usr/localopt has never been a thing. /usr/local/opt is where this stuff is at.
The macos machines all seem to be set up to have /usr/localopt in start.sh and /etc/paths, but because /usr/local/opt is in there I believe it just _mostly works_.
https://github.com/nodejs/build/issues/1955 reports slow release builds on macos, but that's because there's no ccache. I tried running the playbook but it failed at doing something in /home, so there's more work to be done on that. I don't even know if it installs ccache by `brew` but I did that manually for now to get it going.

ansible: macos: /usr/localopt->/usr/local/opt & install ccache

---

ansible/roles/package-upgrade/files/install-xcode.sh

The install-xcode script originates from this blog post - https://derflounder.wordpress.com/2015/02/02/installing-the-xcode-command-line-tools-on-10-7-x-and-later/
Which is hosted in github here - https://github.com/rtrouton/rtrouton_scripts/blob/master/rtrouton_scripts/install_xcode_command_line_tools/install_xcode_command_line_tools.sh
Under the MIT license here - https://github.com/rtrouton/rtrouton_scripts/blob/master/LICENSE
Ive edited the script to have the copyright inside and a link to the original repo. Let me know if I need to add anything else or if the format is wrong.

Add copyright notice to install-xcode.sh

---

jenkins/scripts/VersionSelectorScript.groovy

Ref: https://github.com/nodejs/build/issues/1970
GCC is always really difficult to upgrade on Debian. Jessie only has less than 12 months till EOL and trying to maintainer a newer toolchain on it is just going to waste cycles. I think it's for the good of Build that we just ditch it for >= 13.x since its natural state violates our building minimums in BUILDING.md (but not our running conditions).
@nodejs/build

jenkins: exclude Debian 8 from testing Node >= 13

---

ansible/roles/baselayout/tasks/main.yml
ansible/roles/baselayout/tasks/partials/repo/ubuntu1604.yml
ansible/roles/baselayout/vars/main.yml
jenkins/scripts/select-compiler.sh

Ref: https://github.com/nodejs/build/issues/1970
This will build Node >=13 with GCC 7 on Ubuntu 16.04 and the default GCC 5 compiler below that.
I've tried out the ansible config on one of the ubuntu1604-x64 machines and it works fine, leaves the default compiler as 5 but 7 is available.
I've not tested the select-compiler.sh script that's included here, we've not used it beyond the IBM machines but it's probably time to get some of the logic out of Jenkins and into GitHub for the other machines. Some sanity checking before I attempt to test it out would be helpful.

ansible,jenkins: install gcc-7 on ubuntu1604 machines, use on node>12

---

jenkins/scripts/select-compiler.sh

Continuing from #1975, the select-compiler.sh addition didn't work for node-test-commit-v8-linux because `$node` is `benchmark-ubuntu1604-intel-64`, so this turns it into a regex. Also, the top of the script in Jenkins for that job had `#/bin/bash` so it was still running Dash and `[[` was causing errors. I added the missing `!` and hopefully that doesn't disrupt anything.

jenkins: expand ubuntu1604 test to benchmark machines

---

ansible/inventory.yml
ansible/roles/baselayout/vars/main.yml
ansible/roles/jenkins-worker/vars/main.yml
doc/node-test-commit-matrix.md
jenkins/scripts/VersionSelectorScript.groovy
tools/build-p-ssh-hosts.sh

Hasn't been needed since Node 6. The last 32-bit SmartOS and saves 5 machines.

Remove SmartOS 14 from CI

---

ansible/aix61-standalone/manualBootstrap.md

See: https://github.com/nodejs/build/issues/1957

Describe exact size of /tmp required for AIX 6.1

---

ansible/inventory.yml
ansible/roles/baselayout/vars/main.yml
ansible/roles/java-base/tasks/main.yml
ansible/roles/java-base/vars/main.yml
ansible/roles/jenkins-worker/vars/main.yml
doc/node-test-commit-matrix.md
jenkins/scripts/VersionSelectorScript.groovy

It's still active for Node 8 testing, which will cease at the end of the year. 12.04 has been out of standard support since 2017 and even left extended (paid) support earlier this year. It's not been as painful as Debian or CentOS but let's remove it anyway.

Remove Ubuntu 12.04 from CI

---

ansible/inventory.yml
ansible/playbooks/jenkins/worker/create.yml
ansible/roles/baselayout/vars/main.yml
ansible/roles/jenkins-workspace/tasks/main.yml

Ref: https://github.com/nodejs/build/issues/2001
Also included this is a reprovisioned jenkins-workspace-1, it started having problems 2 weeks back and has locked up twice now. I just made a new one and re-attached the big network block device we're using for /home from the old one so it's good to go.
I've run this against the hosts, I've also switched the label for the linter job in Jenkins from `linter` to `jenkins-workspace` so they've already taken over duty from the FreeBSD 10 machines which we need to retire.
The script has changed, a few old bits are removed and the BSD-compatibility is gone too:
```sh
#!/bin/bash -ex
if [[ "$NODEJS_MAJOR_VERSION" -ge "12" ]]; then
make lint-py-build PYTHON=python3 || true
make lint-py PYTHON=python3
fi
make lint-py-build PYTHON=python2 || true …
```

ansible: prepare jenkins-workspace machines for linting duty

---

README.md
doc/access.md

Coming out of #2005 and a discussion amongst infra via email, I thought it would be good to put down more of the reasoning behind the levels of access so it's clear to us what that is and hopefully clear to all how we deal with granting additional access (and that there is reasoning and a path for individuals who invest their time and skills here).
Some big changes but my hope is that this is you can be told to read if you want to become a member and it will all be clear how we work organisationally.
The bottom line is that we need to expand our people resources here and some of that expansion involves elevated access. But the path to elevated access is _really_ tricky because we're dealing with security, stability, legal concerns and even concerns that are difficult to quantify like …

doc: major update to acess.md

---

README.md

Two teams lacked ncu-team annotation, I added them, their memberships            
were broadly consistent already, though the Release team has more                
members than the README recognized.                                              
No one has _lost_ membership in the syncing, other than @gibfahn, which          
he requested, see https://github.com/nodejs/build/issues/2022                    
I created an Emeriti category and put him in it.

doc: run `ncu-team sync README.md`

---

ansible/www-standalone/resources/scripts/dist-perms
ansible/www-standalone/tasks/site-setup.yaml

After 5 days change ownership of downloadable resources to `root`, this locks them down and they can't be modified in any way by releasers. I'd like to change this to a shorter window but will wait till after Node 8 is EOL since Node 8 still has a Raspberry Pi builder so has reasonable delays in getting all assets promoted.

www: dist-perms cron.daily script to fix ~dist permissions

---

ansible/www-standalone/resources/scripts/dist-perms

Ref: https://github.com/nodejs/build/pull/2020#issuecomment-549964893
`-mindepth 2` excludes the top directories, including `/home/dist/nodejs/release/` which is what's caused the problem with 13.1.0.

www: fix /dist permissions fixer, ignore top-level directories

---

ansible/www-standalone/resources/scripts/dist-perms

Fixes: https://github.com/nodejs/build/issues/2032
Getting a little complicated but hopefully that's enough. There's symlinks that are changed with `nodejs-latest-linker` but this should just match files and directories so they should be fine.

www: don't change perms of index.(tab|json)

---

ansible/www-standalone/tools/metrics/country-lookup.py

The problem with these is that you can put a syntax error in between the try: and except: and it will be extremely difficult to spot.  This is discussed in PEP8, Zen of Python, and many other places.

Python: Avoid bare exceptions in country-lookup.py

---

jenkins/scripts/select-compiler.sh

Fix the `select-compiler.sh` script for `node-test-commit-v8-linux` which runs on
`benchmark-ubuntu1604-intel-64`.
Refs: https://github.com/nodejs/build/pull/1985
Refs: https://github.com/nodejs/build/pull/1994
Seen in https://ci.nodejs.org/view/All/job/node-test-commit-v8-linux/nodes=benchmark-ubuntu1604-intel-64,v8test=v8test/2622/console that gcc 6 wasn't picked:
```console
09:50:09 ++ echo 'Setting compiler for Node version 14 on x64'
09:50:09 Setting compiler for Node version 14 on x64
09:50:09 ++ case $nodes in
09:50:09 + rm deps/v8/test/mjsunit/d8-os.js
09:50:09 rm: cannot remove 'deps/v8/test/mjsunit/d8-os.js': No such file or directory
09:50:09 + true
09:50:09 + ./configure
09:50:11 Node configure: Found Python 3.5.2...
09:50:11 WARNING: C++ compiler (CXX=g++, 5.5.0) too old, …
```

fix select-compiler.sh for V8 CI

---

jenkins/scripts/select-compiler.sh

Fixes: https://github.com/nodejs/node/issues/30363
Guesswork, as I don't have access to [infra-softlayer-ubuntu1404-x64-2](https://ci.nodejs.org/computer/infra-softlayer-ubuntu1404-x64-2/).
Doesn't work yet: https://github.com/nodejs/node/issues/30363#issuecomment-553926151

add `benchmark` to select-compiler.sh

---

jenkins/scripts/node-test-commit-diagnostics.sh

resolves https://github.com/nodejs/build/issues/1859 using https://github.com/nodejs/build/issues/1859#issuecomment-507563309
This gets around AIX not having pgrep but does imply that all other build machines that use this script have perl installed which me and @sam-github are not sure of.

jenkins: edit test-commit-diagnostics.sh to solve missing pgrep

---

ansible/inventory.yml

The good people at Joyent have manually moved unencrypted.nodejs.org, which also serves as backup-www in our load balancer pool. It's up and running in a new location because the old datacenter is being closed. DNS and load balancer have this new change and it appears to be in good order.
The second infra server, "backup", is still to be moved, will keep this PR open until that one has a new IP and is confirmed working.

ansible: move IP of {unencrypted,backup-www}.nodejs.org

---

README.md

@sam-github and I think that @mmarchini's webpage showing the health of the last 100 builds should be linked in the top level readme (providing they are ok with it being there) to have more visibility to the general health of our CI.

doc: add mmarchini's build health webpage to README.md

---

ansible/aix61-standalone/resources/S20jenkins

Some of the builds were taking the 20 CPUS to mean run with JOBS=20, but
the machines don't have enough memory to run at that kind of build
concurrency. Throttle to 4. Some jobs were doing this already, but by
setting it in the global env, it should be inherited by all jobs.

ansible: set JOBS to 4 for AIX

---

doc/non-ansible-configuration-notes.md

Tried to use the notes in non-ansible-configuration-notes.md and couldn't make heads or tails of it, so decided to format them first to make them readable

doc: clean up GCC tarball notes on AIX

---

jenkins/scripts/coverage/generate-index-html.py

We are now collecting combined coverage on codecov.io for Windows and Linux (@Trott plans to also add additional coverage for other Linux runtimes).
What's nice about this project, is that it will allow us to eventually hit 100% coverage on the Node.js project, despite some code paths being conditional on platform.

feat: add link to codecov.io

---

ansible/aix61-standalone/manualBootstrap.md
ansible/inventory.yml
ansible/plugins/inventory/nodejs_yaml.py
ansible/roles/baselayout/vars/main.yml
jenkins/scripts/select-compiler.sh

This is a draft pass at adding new AIX72 to our test ci.
Ive edited the anisble to install the packages that use to be done manually.
One machine is commented out as I dont have access atm and so its not currently ansibled yet
Finally Ive cleaned up and edited the manual steps .md with additions needed and ive also split it into 6.1 and 7.2 install steps as both have some differences.
These machines aren't ready yet as I dont have CI access so they are missing the jenkins secret.

ansible: add new AIX7.1 machines to CI

---

ansible/ansible.cfg
ansible/inventory.yml
ansible/roles/baselayout/vars/main.yml
ansible/roles/docker/vars/main.yml
ansible/roles/java-base/tasks/main.yml
ansible/roles/java-base/vars/main.yml
ansible/roles/jenkins-worker/templates/rpi_wheezy.Dockerfile.j2
ansible/roles/jenkins-worker/vars/main.yml
doc/non-ansible-configuration-notes.md

Raspbian Stretch to Raspbian Buster. I also discovered that a sound driver update sometime this year was the cause of boot instability, so that's now disabled at boot and they're running much smoother now.
Have updated the additional docs in here for Pi's to be current and make the setup (somewhat) reproducable.
arm-fanned is back online now after its hiatus, still ironing out some minor hiccups though.
Ref: https://github.com/nodejs/build/issues/1840
Ref: https://github.com/nodejs/node/issues/30786

pi: reprovision all Pi's with Raspbian Buster, add docs

---

ansible/roles/jenkins-worker/templates/aix.rc2.j2

This was causing build failures on the new AIX 7.1 machines as they couldnt perform a git pull.
ive updated the machines with this and have restarted the agents but will need someone to kick off a test build of node-test-commit-aix71 to ensure it worked.

ansible: remove hardcoded cert location for AIX jenkins

---

ansible/ansible.cfg
ansible/inventory.yml
ansible/playbooks/jenkins/worker/create.yml
ansible/roles/baselayout/tasks/main.yml
ansible/roles/baselayout/vars/main.yml
ansible/roles/java-base/vars/main.yml
ansible/roles/jenkins-worker/meta/main.yml
ansible/roles/jenkins-worker/tasks/main.yml
ansible/roles/jenkins-worker/tasks/partials/tap2junit/rhel7.yml
ansible/roles/jenkins-worker/vars/main.yml
ansible/roles/package-upgrade/vars/main.yml
doc/node-test-commit-matrix.md
doc/non-ansible-configuration-notes.md
jenkins/pipelines/llnode-pipeline.jenkinsfile
jenkins/xml/citgm-smoker.xml
tools/build-p-ssh-hosts.sh

READY FOR REVIEW
This is to replace the current s390x machines with 5 machines in the new datacentre - 1 release, 4 test

Reprovision s390x machines

---

ansible/MANUAL_STEPS.md
ansible/aix61-standalone/manualBootstrap.md

They used to be part of the legacy AIX6.1 manualBootstrap.md. Since
AIX7.2 is current, and runs from top-level ansible playbooks, move
them to MANUAL_STEPS.md.

ansible: manual AIX7.2 install instructions moved

---

ansible/aix61-standalone/manualBootstrap.md

This might not ever be done again, since AIX6.1 isn't needed for 10.x and up, https://github.com/nodejs/node/blob/v10.x/BUILDING.md#supported-platforms-1, but worth documenting anyway.

ansible: aix6.1 ccache needs recreation on ramdisk

---

ansible/roles/baselayout/vars/main.yml
ansible/roles/jenkins-worker/tasks/main.yml

fixes: https://github.com/nodejs/build/issues/2080#issuecomment-567280766
Not ready for merging yet - not able to update the iptables on the machines themselves.
They don't have a running iptables.service so I don't know how to restart iptables to apply the rules

ansible: add back the firewall rules for rhel7_s390x

---

README.md

He is employed full-time by IBM in my team to work on Node.js community build infrastructure, and I am mentoring him.
He has setup and has ongoing "special access" to maintain 3 sets of build machines:
- https://github.com/nodejs/build/issues/2054
- https://github.com/nodejs/build/issues/2081
- https://github.com/nodejs/build/issues/1695
He doesn't have the ability to run CI jobs (much less configure CI jobs), so he can't complete the rhel7-s390x or aix7.1-ppc64 setup or nearform macmini setup, I have to run all the jobs for him.
Criteria: https://github.com/nodejs/build/blob/master/doc/access.md#build-working-group-membership
History:
- Continous involvement in build-wg since joining our team
- nodejs/build PRs: 10 close, 2 open: …

Proposal to add AshCripps as member of build-wg

---

jenkins/scripts/VersionSelectorScript.groovy

v14 testing is looking green so this pr will enable testing on v13.
Ive also included changes to allow for releasing 14 from 7.1. LMT if anyone feels this is too soon/incorrect.
refs: #2110

jenkins: use AIX7.1 for 13.x and 14.x

---

ansible/roles/baselayout/vars/main.yml

This installs a dependency needed by V8
refs: https://github.com/nodejs/build/issues/2080#issuecomment-569428811

ansible: rhel: add gconf2-devel package to ansible scripts

---

ansible/MANUAL_STEPS.md

Needed for V8 jobs. Description is incomplete wrt. how to build them
initially, but better than the previous state of no docs at all.
@AshCripps is going to look at ansiblizing this, and the existence of documented manual steps will help understand what needs to be ansibled.

ansible: rhel7-s390x manual ninja/v8 build step

---

jenkins/scripts/VersionSelectorScript.groovy

*NO* changes made to actual exclusion lines, just reordered, and
comment cleanups.
Some of the names ("s390x") didn't have the OS, it was just implied by
the architecture (to those in the know), and some used a specific distro
as the OS name, but the platform support is wider than just what distro
we build on.

jenkins: rename sections to "OS + ARCH"

---

jenkins/scripts/VersionSelectorScript.groovy

revert #2113 
Ive also fixed AIX61 to use the correct operator.
@rvagg @sam-github

jenkins: remove the gt operator from VersionSelectorScript

---

jenkins/pipelines/node-linter.jenkinsfile
jenkins/pipelines/node-test-pull-request-lite-pipeline.jenkinsfile

fixes: #1631 
example output (`master`):
```
18:38:04  + python tools/getnodeversion.py
18:38:05  [Pipeline] sh
18:38:09  + NODE=node PYTHON=python3 gmake lint-py
18:38:09  PYTHONPATH=tools/pip python3 -m flake8 . \
18:38:09  	--count --show-source --statistics --select=E901,E999,F821,F822,F823 \
18:38:09  	--exclude=.git,deps,lib,src,test/fixtures,tools/*_macros.py,tools/gyp,tools/inspector_protocol,tools/jinja2,tools/markupsafe,tools/pip
18:38:18  0
18:38:19  [Pipeline] sh
18:38:22  + NODE=node gmake lint-ci
18:38:22  Running JS linter...
18:39:43  Running C++ linter...
18:40:19  PYTHONPATH=tools/pip python -m flake8 . \
18:40:19  	--count --show-source --statistics --select=E901,E999,F821,F822,F823 \
18:40:19  	--exclude=.git,deps,lib,src,test/fixtures,tools/*_macros.py,tools/gyp,tools/ …
```

pipelines: add lint-py to linter pipeline

---

ansible/inventory.yml
ansible/roles/jenkins-worker/tasks/main.yml
ansible/roles/jenkins-worker/tasks/partials/scaleway-armv7.yml
ansible/roles/package-upgrade/tasks/partials/apt.yml

Ref: https://github.com/nodejs/build/issues/2066
This adds a 4G swap and does a safe-upgrade instead of a dist-upgrade in an attempt to avoid too much tinkering with the kernel. I've also "fixed" the `jobs_env` logic, it's been overwriting the `jobs_variants` setting in roles/jenkins-worker/tasks/main.yml.

ansible: reprovision all scaleway test hosts

---

ansible/roles/java-base/tasks/main.yml

The java being used for the jenkins agent is a java 8 with a HotSpot JVM which does not have JIT compiler. In order to speed up the jenkins processes running on the machine I propose switching to an AdoptOpenJDK/OpenJ9 JVM which does have a JIT. This PR will make that change.
(May require further adjustments to the `jenkins-worker` directories if the full path has to be encoded somewhere)
Current output from one of the build machines shows it using the Zero VM
```
[linux1@test-ibm-rhel7-s390x-3 ~]$ /usr/bin/java -version
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
OpenJDK 64-Bit Zero VM (build 25.232-b09, interpreted mode)
[linux1@test-ibm-rhel7-s390x-3 ~]$
```
Looking for reviews on the concept - the code hasn't been tested yet ;-) Am tempted to do a bit …

use adoptopenjdk on Linux/s390x as it has a JIT

---

jenkins/scripts/coverage/generate-index-html.py
jenkins/scripts/coverage/styles.css

This unties the site from the upstream CSS
**I need some help actually copying the CSS file. Any help welcome.**
Preview: <https://relaxed-ptolemy-556131.netlify.com/>
Refs https://github.com/nodejs/nodejs.org/pull/2635
TODO:
Note that the CSS is only the required. Which means that if more elements are added at some point, their rules should be added manually here again.

coverage: add the needed CSS from the main site

---

jenkins/scripts/coverage/generate-index-html.py

Remove copy of styles from script, added it instead to
the job that runs/generates the coverage output

coverage: remove copy of styles

---

doc/windows-visualstudio-supported-versions.md

It seems to me that it will grow without bounds, and anyone interested in historical Node.js releases can look into the git history to find it.
Just tidying up, no strong feelings, so we can leave the info if its still useful.

doc: remove information on EOL Node.js versions

---

.github/workflows/push.yml

Renames jobs in the current GitHub Actions workflow to be more descriptive. The plan is to add a further job to lint yaml (continuation of https://github.com/nodejs/build/pull/1476 but as a workflow instead of Travis CI) but this is a standalone change.

workflow: update job names, use checkout@v2

---

.github/workflows/stale.yml

Setup to mark stale after 90 days, and close 15 days after marked stale
unless the issue is commented on, or has the `stale` label removed.
Fixes: https://github.com/nodejs/build/issues/2190
-----
Draft - awaiting some comment on https://github.com/nodejs/build/issues/2190 to agree this is useful. I've never configured a GH action before, I'd appreciate a review by someone who has!

workflow: add stale action

---

ansible/roles/docker/templates/ubi81.Dockerfile.j2
jenkins/scripts/VersionSelectorScript.groovy

Adds a dockerfile for UBI 8.1.
From what I can tell the ansible changes would all be to the test inventory.xml in secrets (and not here in this repo). @nodejs/build-infra do I need to cleanly shutdown all the running containers (as per https://github.com/nodejs/build/blob/97b004a672d17820976ea8eac91b4dde8a6a4697/ansible/MANUAL_STEPS.md#Docker-hosts) in a container host before re-ansibling it (once I've added the new container to the inventory)?
Refs: https://github.com/nodejs/build/issues/2176

ansible: add container for UBI 8.1

---

ansible/MANUAL_STEPS.md

libiconv.a is not in ../bin, its in ../lib/ (of course). Found this on
ci-release, where symlink pointed to the non-existent ../bin/libiconv.a

ansible: fix typo in libiconv fixup

---

ansible/roles/baselayout/vars/main.yml
jenkins/scripts/select-compiler.sh

Install `cmake` on AIX from the [AIX Toolbox for Linux Applications](https://www.ibm.com/support/pages/aix-toolbox-linux-applications-downloads-alpha).
Refs: https://github.com/nodejs/build/issues/2097
Refs: https://github.com/libuv/libuv/pull/2731
cc @AshCripps @sam-github

ansible: add cmake for AIX

---

jenkins/scripts/VersionSelectorScript.groovy

This lands on top of #2199, after we get that one landed landed, https://github.com/nodejs/node/pull/31459 landed and a few nightlies out without any problems.
See timeline in https://github.com/nodejs/build/pull/2199#issuecomment-594253577

 jenkins: osx10.15 release for 13.x 

---

ansible/playbooks/jenkins/worker/create.yml

forgot this second bit, it's needed so `node` doesn't get removed after it's installed, we need it on these workspace machines to run the linter
we need to find a better way of doing this than listing the machines, using the label might be good if we can work out a way to

jenkins: exclude new jenkins-workspace machines from removing `node`

---

ansible/roles/baselayout/vars/main.yml

refs: https://github.com/nodejs/build/issues/2175
So far ive only added it to 10.15 as older macs can build libuv on gyp whereas 10.15 can't at this time.
Tested on test-nearform-macos10.15-x64-3 and its working
```
administrator@test-nearform-macos10 ~ % cmake -version
cmake version 3.16.5
CMake suite maintained and supported by Kitware (kitware.com/cmake).
administrator@test-nearform-macos10 ~ %
```

ansible: add cmake to macos

---

jenkins/scripts/VersionSelectorScript.groovy

I think ive got this right, once https://github.com/nodejs/node/pull/32454 lands it doesnt make
sense to test master on 10.11 anymore with the deployment target set to
10.13. So setting the versionselector to not test 14.x+ on osx10.11
refs: https://github.com/nodejs/node/pull/32454

jenkins: stop testing 14.x on OSX10.11

---

ansible/www-standalone/tools/metrics/public-index.html

The directory for metrics was moved in 0a1b2e9ad35ba7aab215e799529781a3522e00ce.

ansible: update link to metrics directory

---

ansible/inventory.yml
ansible/roles/baselayout/tasks/main.yml
ansible/roles/baselayout/tasks/partials/repo/centos6.yml

I had to rebuild this machine, it wasn't connected to Jenkins and I couldn't ssh into it and force reboot didn't do anything.. Later I noticed the IP address we had wasn't the one for the machine. I don't _think_ it got changed when I ordered a rebuild in SoftLayer, but I'm also not sure what the deal is with this new address anyway because it wasn't in ci-release's firewall.
Anyway, rebuild resulted in yaks to shave, see ansible changes here.

ansible: fix up release-centos6

---

jenkins/scripts/VersionSelectorScript.groovy

This lands on top of #2202, after we get https://github.com/nodejs/node/pull/31459 backported to 12.x and 10.x which happens after we successfully get a 13.x release or two out.
See timeline in https://github.com/nodejs/build/pull/2199#issuecomment-594253577

jenkins: osx10.15 release for all versions 

---

README.md

Fixes: https://github.com/nodejs/build/issues/2220

doc: add sam-github to release admins

---

ansible/roles/baselayout/tasks/partials/repo/centos7.yml
ansible/roles/baselayout/vars/main.yml
jenkins/scripts/VersionSelectorScript.groovy
jenkins/scripts/select-compiler.sh
tools/build-p-ssh-hosts.sh

Refs: https://github.com/nodejs/build/issues/2242

ansible: install devtoolset-8 on centos7

---

ansible/www-standalone/tasks/site-setup.yaml

Ref: #2264
Just slowing things down a bit. Not fixing anything specific but being more cautious because a hypothetical potential for cache invalidation _every minute_. I can't see a means by which this could be caused, but slowing down the checks in cron will help. Will comment about implications of each thing inline.
This is active on nodejs.org right now but can be easily changed if there's feedback here.

www: less agressive nightly promotion & CDN cache purge

---

ansible/www-standalone/resources/scripts/build-site.sh
ansible/www-standalone/resources/scripts/cdn-purge.sh.j2
ansible/www-standalone/resources/scripts/queue-cdn-purge.sh
ansible/www-standalone/tools/promote/_promote.sh
ansible/www-standalone/tools/promote/resha_release.sh

Ref: #2264
We don't have logs of our calls to Cloudflare's cache purge API calls we make when we promote new /download/ assets or publish new website content, so this is adding such logging. Along the way, I think I've found one possible "bug" that may provide a partial explanation to our outage problems, but I'll explain that in #2249 
Additional comments inline.

www: log cdn purge calls

---

jenkins/scripts/select-compiler.sh

https://github.com/nodejs/build/pull/2262 mistakenly added a
duplicated case that prevented the previously existing logic from
being executed. Merge the two centos cases for ppcle Linux.
Refs: https://github.com/nodejs/node/pull/32768#issuecomment-612156432

jenkins: fix compiler selection for ppcle Linux

---

jenkins/scripts/VersionSelectorScript.groovy

Also remove redundant release sources for Node 10
Ref: https://github.com/nodejs/node/issues/32755
Explanation:
Hello foot-gun.
#2203 switched our release builds for osx to 10.15, which changed this whole block to prevent 10.10 and 10.11 for release builds.
Unfortunately, we have overlapping regexes that weren't noticed. Below this section is the "release-sources" labels. We used to build tarballs with osx all the way up to Node 11 when we switched to centos for Node 12. Node 10 is osx1010 and Node 11 was osx1011, so we have "release-sources" labels for those.
When we excluded `^osx1010` and `^osx1011` from `releaseType` we also excluded `osx1010-release-sources` from Node 10.
So the 10.20.0 iojs+release build has this:
```
20:27:22 Skipping centos7-release-sources for Node.js 10
20:27:22 …
```

jenkins: don't skip osx release sources build for 10.x

---

jenkins/scripts/VersionSelectorScript.groovy

jenkins: drop smartos builds from release for 14+

---

ansible/roles/baselayout/tasks/partials/repo/centos7.yml
ansible/roles/baselayout/vars/main.yml

It install python 3.6.8.
Ansible's previously built python3 wasn't capable of running node's
./configure, it lacked sufficient capabilities (like bzip2).

Use system python3 on centos7-ppc64

---

ansible/MANUAL_STEPS.md

Fix a typo in the extracting xcode step

doc: fix typo in macos release steps

---

ansible/roles/docker/templates/alpine311.Dockerfile.j2

Haven't actually done anything with this beyond messing with the files, so just a heads-up for now (and invitation if someone else wants to do this, @richardlau?). I don't even know if these will build properly, but the last couple of versions of Alpine have been stable enough that we haven't had to change anything so I'm hopeful.
Next steps:
- Stop containers via systemd
- Remove systemd unit, then run `systemctl daemon-reload`
- Remove images (`docker rmi ...`)
- Run `docker system prune -fa` to clean up dangling images.

alpine: remove Alpine 3.9, add 3.11

---

ansible/roles/jenkins-worker/tasks/main.yml

Add ansible tasks to install cmake on z/OS.
Downloads z/OS cmake port from https://github.com/fjeremic/CMake, unpacks, builds and installs into `/u/iojs/local`.
Ran the new tasks on both `test-marist-zos13-s390x-1` and `test-marist-zos13-s390x-2` via
```
ansible-playbook --limit test-marist-zos13-s390x-* playbooks/jenkins/worker/create.yml --start-at-task "install cmake - create directory - part 1"
```
Updated the paths in [libuv-test-commit-zos-cmake](https://ci.nodejs.org/job/libuv-test-commit-zos-cmake/) to point to `/u/iojs/local/bin` and ran a test build: https://ci.nodejs.org/job/libuv-test-commit-zos-cmake/63/ (ran on both `test-marist-zos13-s390x-1` and `test-marist-zos13-s390x-2`).
I'm not able to run the entire unaltered `playbooks/jenkins/worker/create.yml` playbook on z/OS. …

ansible: add tasks to install cmake on z/OS

---

jenkins/scripts/VersionSelectorScript.groovy
jenkins/scripts/select-compiler.sh

All references to `aix61-ppc64` and `ppcle-ubuntu1404` have been removed 
from the test and release CI's so it should be safe to remove them from the
`select-compiler.sh` and `VersionSelectorScript.groovy` scripts.
Refs: https://github.com/nodejs/build/issues/2159
Refs: https://github.com/nodejs/build/issues/2273
cc @nodejs/platform-aix @nodejs/platform-ppc

jenkins: remove aix61-ppc64 and ppcle-ubuntu1404

---

README.md

Since changing it to run on nodejs.org the link doesn't work anymore

doc: Update the CI health dashboard link

---

ansible/inventory.yml
ansible/plugins/inventory/nodejs_yaml.py

Finally got the firewall set up so heres the draft PR whilst I finish setup. 
Couple things need doing.

ansible: add 1015 orka test macs

---

ansible/www-standalone/tasks/tools.yaml

Not sure why this is so far out of sync but this switches out 13.x-staging nightly for 14.x-staging. But to be honest I'm not sure of the value of these current-staging nightlies. @nodejs/release do you want to weigh in here? Would they be missed if we dropped them? Do you know of anyone even using these non-master nightlies (did you even know they existed?).

ansible,www: switch from 13.x nightly to 14.x nightly

---

ansible/inventory.yml

They have already been removed from ci and ci-release.

ansible: remove ubuntu1404 machines

---

ansible/plugins/inventory/nodejs_yaml.py

Add new provider [`iinthecloud`](https://iinthecloud.com/) and sort providers alphabetically.
I've split this out of https://github.com/nodejs/build/pull/1923 because we need to add the new provider
before we can add the secrets for the IBM i machines to the secrets 
repo (refs https://github.com/nodejs/build/pull/2253#discussion_r411809473 for when we added `orka`).

ansible: add iinthecloud provider

---

ansible/MANUAL_STEPS.md
ansible/ansible.cfg
ansible/host_vars/test-iinthecloud-ibmi72-ppc64_be-1
ansible/inventory.yml
ansible/playbooks/jenkins/worker/create.yml
ansible/roles/baselayout/tasks/main.yml
ansible/roles/baselayout/vars/main.yml
ansible/roles/java-base/tasks/main.yml
ansible/roles/jenkins-worker/tasks/main.yml
ansible/roles/jenkins-worker/tasks/partials/tap2junit/ibmi.yml
ansible/roles/jenkins-worker/templates/ibmi_start.j2
ansible/roles/jenkins-worker/vars/main.yml
ansible/roles/package-upgrade/tasks/partials/yum.yml
ansible/roles/package-upgrade/vars/main.yml
jenkins/scripts/select-compiler.sh

Supercedes and addresses PR #1700 
Addresses part of issue #1697 
TODO items remaining are (at least):

Add IBM i initial playbooks

---

ansible/inventory.yml

10.14 macs are a bit of a bottleneck in CI at the moment so adding a third one to hopefully help alleviate the bottleneck

ansible: add a third 10.14 mac

---

jenkins/scripts/node-test-commit-pre.sh

If `node-test-commit-diagnostics.sh` exists locally (e.g. we are in
a checked out copy of the build repository then call the local version
from `node-test-commit-pre.sh`, otherwise download and execute the
latest from GitHub (as we had been doing before this change).
Refs: https://github.com/nodejs/build/issues/2330

jenkins: call checked out script if available

---

jenkins/scripts/VersionSelectorScript.groovy

I want to propose moving the build of 10.x release sources off osx onto linux with the rest of the release lines.
This will allow us to migrate off of our old macstadium vsphere (https://github.com/nodejs/build/issues/2315) as this is our only dependency upon osx 10.10.
Im not 100% sure if this is possible to test before merging.

jenkins: move 10.x release sources off osx

---

ansible/roles/docker/templates/alpine312.Dockerfile.j2
ansible/roles/docker/templates/ubuntu1804_sharedlibs.Dockerfile.j2
jenkins/scripts/VersionSelectorScript.groovy

Alpine 3.12 doesn't come with a Python 2 option and Node 10 and 12's `configure` don't seem to like Python 3 so I've added an exclusion to VersionSelectorScript. I've also had to symlink `python3` as `python` in those packages because we still force `PYTHON=python` in the commit-linux job.

Container upgrade: Alpine 3.12, OpenSSL 1.1.1g, remove OpenSSL 1.0.2 and FIPS

---

ansible/roles/baselayout/tasks/main.yml

On Centos 7 there are two cmake packages, cmake and cmake3. The
cmake package is cmake 2.x -- we install cmake3 as the projects
we build, e.g. libuv, require cmake 3.x. The cmake3 package
creates binaries that all have a 3 suffix, e.g. `cmake3`.
Node.js addons tested via CITGM that use cmake look for a cmake
binary without the version suffix, e.g. `cmake`. Add symlinks
so the binary names without the version suffix resolve to the
installed binaries for cmake (cmake, cpack and ctest).

ansible: add symlinks to cmake3 on centos7_ppc64

---

doc/jenkins-guide.md

The agent restart command line should be run with `sudo` otherwise you will be prompted
for the password for the `iojs` user:
```
$ /etc/rc.d/rc2.d/S20jenkins start
iojs's Password:
...
```

doc: add sudo to AIX Jenkins agent restart command

---

ansible/inventory.yml

These hosts are long gone but still linger in our inventory

ansible: remove old aix61 hosts

---

ansible/MANUAL_STEPS.md

When I ran this for the orka release machine, base64 needed `-D` instead of `-d` to decrypt

doc: fix typo in macos release notes

---

ansible/roles/java-base/tasks/main.yml
ansible/roles/java-base/vars/main.yml
ansible/roles/jenkins-worker/templates/aix.rc2.j2
ansible/roles/jenkins-worker/vars/main.yml

Fixes: https://github.com/nodejs/build/issues/2393
Replace several duplicated tasks for installing Java from builds provided by AdoptOpenJDK with a set of common tasks.
Remove hardcoded Java release specific paths.
Thanks to @sxa for pointing me at the [AdoptOpenJDK API](https://github.com/adoptopenjdk/openjdk-api-v3) which these changes use to fetch the latest release for Java version being installed.
<details>
<summary>An example use of the API</summary>
https://api.adoptopenjdk.net/v3/assets/feature_releases/8/ga?architecture=ppc64le&image_type=jre&jvm_impl=openj9&os=linux&project=jdk&heap_size=normal&page_size=1&sort_method=DEFAULT&sort_order=DESC&vendor=adoptopenjdk
```json
[
{
"binaries": [
{
"architecture": "ppc64le",
"download_count": 0,
"heap_size": "normal",
"image_type": "jre", …
```

ansible: refactor install AdoptOpenJDK Java tasks

---

ansible/roles/baselayout/tasks/main.yml
ansible/roles/java-base/tasks/main.yml
ansible/roles/java-base/vars/main.yml
ansible/roles/jenkins-worker/templates/ibmi_start.j2
ansible/roles/jenkins-worker/vars/main.yml

Install OpenJDK Java via the yum repository for IBM i.
Have run against `test-iinthecloud-ibmi72-ppc64_be-1` and `test-iinthecloud-ibmi72-ppc64_be-2`.
Had to pass `-Djava.net.preferIPv4Stack=true` to the Jenkins agent start command to get the agent to start up (otherwise the agent would fail to start with `java.net.SocketException: Protocol driver not attached.`).
cc @ThePrez

ansible: install openjdk via yum for IBM i

---

ansible/ansible.cfg
ansible/inventory.yml
ansible/roles/baselayout/tasks/main.yml
ansible/roles/baselayout/vars/main.yml
ansible/roles/jenkins-worker/tasks/partials/tap2junit/macos.yml
ansible/roles/jenkins-worker/vars/main.yml
jenkins/scripts/VersionSelectorScript.groovy

This pr will add the DTKs kindly donated to us by macstadium and any edits needed to playbooks.
refs: https://github.com/nodejs/TSC/issues/886
@nodejs/build-infra can the ips be added to the test jenkins firewall please.

Add Apple silicon macs

---

jenkins/scripts/VersionSelectorScript.groovy

These mac versions are no longer in our CI so removing
them from the versionselectorscript

jenkins: remove old macos from versionselector

---

ansible/ansible.cfg
ansible/inventory.yml
ansible/roles/jenkins-worker/tasks/main.yml
ansible/roles/jenkins-worker/templates/git-wrapper.j2
ansible/roles/jenkins-worker/vars/main.yml

The location of some installed tools has changed in the z/OS 2.4 VMs
we've been given from marist compared to the existing z/OS 2.2 VMs.
Refs: https://github.com/nodejs/build/issues/2435

ansible: changes for z/OS 2.4 VMs

---

README.md

September 30 was my last day at IBM and my last day as a full-time
Node.js contributor.
I'm joining Deno Land Inc. and don't expect to have time to participate
in the Build WG.

doc: move bnoordhuis to emiriti

---

ansible/roles/baselayout/tasks/main.yml

The `nodejs.org` is uneeded and at least on AIX it causes tests to fail by resolving to an incorrect IP
refs: https://github.com/nodejs/build/issues/2447

ansible: remove `.nodejs.org` from hostname on AIX and mac

---

doc/jenkins-guide.md

AIX often has much bigger disks than is being used - add some basic
steps to increase the size of the disk without limiting the amount of
builds that can run on the machine

doc: add some AIX specific troubleshooting

---

ansible/inventory.yml
ansible/roles/jenkins-worker/vars/main.yml

The new z/OS 2.4 VMs look to be in good working order so remove the
old z/OS 2.2 VMs that the new ones replace.
Closes: https://github.com/nodejs/build/issues/2435
I've gone through the Jenkins configs and removed any references to the old VMs.

ansible: remove z/OS 2.2 VMs

---

ansible/MANUAL_STEPS.md

This wasn't obvious to me although it really should've been so just documenting here.

doc: add untar steps to xlC install steps

---

ansible/roles/github-bot/tasks/main.yml

It's about time we bump Node.js the @nodejs-github-bot is running (for obvious reasons).
CI says it's good to go and with pretty decent test coverage, it feels less than risky to go ahead and update Node.js on the server.
Refs https://github.com/nodejs/github-bot/pull/287
/cc @nodejs/github-bot

github-bot: update Node.js from 10.x -> 14.x

---

jenkins/scripts/windows/node-compile-windows.cmd

Required for testing overlapped I/O on windows (#29412)

jenkins: add overlapped-checker.exe to binary.tgz

---

ansible/roles/bootstrap/tasks/partials/debian8.yml

Running playbooks using the `bootstrap` role on machines running debian8 failed when in check mode:
```
$ ansible-playbook --check playbooks/create-github-bot.yml
TASK [bootstrap : check for apt-transport-https] ****************************************************************************************************************************************
skipping: [infra-rackspace-debian8-x64-1]
TASK [bootstrap : install apt-transport-https] ******************************************************************************************************************************************
fatal: [infra-rackspace-debian8-x64-1]: FAILED! => {"msg": "The conditional check 'has_apt_transport.rc == 1' failed. The error was: error while evaluating conditional (has_apt_transport.rc == 1): 'dict object' has no …
```

ansible: fix needed to run debian8 bootstrap in check mode

---

ansible/ansible.cfg
ansible/inventory.yml
ansible/roles/jenkins-worker/tasks/partials/tap2junit/macos10.14.yml
ansible/roles/jenkins-worker/templates/start.j2

The Orka macOS 10.14 do not have a system Python installed in
`/usr/bin`. Amend the ansible scripts to use the brew installed
Python 3 on those hosts.
Fixes: https://github.com/nodejs/build/issues/2512
cc @AshCripps

ansible: fix scripts for Orka macOS 10.14 hosts

---

ansible/roles/docker/templates/jenkins.service.j2
ansible/roles/jenkins-worker/templates/docker-jenkins.service.j2

Since Docker 20.10.0 @ 2020-12-08, port binding has been made unrestricted.
This change undoes that by ensuring that <1024 are privileged. Node.js' test
suite assumes that binding to a lower port will result in a privilege failure
so we need to create an environment suitable for that assumption.
Ref: https://github.com/nodejs/node/issues/36847

ansible,docker: ensure <1024 are privileged ports

---

ansible/inventory.yml

Our DOU expired at the end of 2020 so these machines have now been
removed. The machines have already been replaced.

ansible: remove reference to old AIX71 machines

---

jenkins/scripts/select-compiler.sh

It appears that either Jenkins and/or the JDK on AIX is setting the
`LIBPATH` environment variable which is breaking `gcc`/`g++`. Some
jobs already `unset LIBPATH` -- now do this consistently in the
`select-compiler.sh` script.
This should allow us to avoid having to do the rather horrible manual 
hack in https://github.com/nodejs/build/blob/master/ansible/MANUAL_STEPS.md#fix-missing-shared-objects
Refs: https://github.com/nodejs/build/issues/2534
cc @nodejs/platform-aix

jenkins: unset LIBPATH on AIX 7.1

---

ansible/roles/baselayout/tasks/main.yml
ansible/roles/baselayout/vars/main.yml

Recent versions of the AIX Toolbox curl package no longer create
symlinks in `/usr/bin`. Some jobs in the CI expect to be able to
run `curl` from the PATH.
Explicitly install the curl package (previously it was installed
as a dependency of git) and create symlinks into `/usr/bin`.
Fixes: https://github.com/nodejs/build/issues/2536
cc @nodejs/platform-aix

ansible: fix curl: not found errors on AIX

---

ansible/MANUAL_STEPS.md

Unsetting `LIBPATH` in `select-compiler.sh` (https://github.com/nodejs/build/pull/2535) is cleaner than attempting to delete and relink `libiconv.a`.
Refs: https://github.com/nodejs/build/issues/2534

ansible: remove AIX libiconv.a hack

---

jenkins/scripts/VersionSelectorScript.groovy

We still want to test on the earlier AIX but not release on it

jenkins: replace AIX71 upper limit with releaseType

---

ansible/roles/jenkins-workspace/tasks/main.yml

Fixes: https://github.com/nodejs/build/issues/2504
/cc @richardlau

ansible: update Node.js from 12.x -> 14.x

---

ansible/roles/baselayout/vars/main.yml

I've run this on all of our test/release AIX 7.1 and 7.2 hosts. It installs Python 3 (3.7.9 at this time) into `/opt/freeware/bin`, e.g. `/opt/freeware/bin/python3`. Crucially it leaves the existing Python 2 installation alone (so `python` still runs Python 2). 
On the AIX 7.2 machines there is already a Python 3.6.12 installation in `/opt/bin/python3`. We end up with three versions of Python installed (2.7.18, 3.6.12 and 3.7.9) but they're in different directories and the python3 binary we pick up depends on the path. If we've run through select-compiler.sh and prepend `/opt/freeware/bin` to the path `python3` will be 3.7.9. https://github.com/nodejs/build/blob/f95880c7e40a1d547afdbfeb9376c476bd6cd5e7/jenkins/scripts/select-compiler.sh#L103
I haven't found a CI job that will actually use …

ansible: add python3 to AIX hosts

---

ansible/roles/baselayout/vars/main.yml
ansible/roles/jenkins-worker/tasks/partials/tap2junit/ibmi.yml

Refs: https://github.com/nodejs/build/issues/2507
Unlike the AIX packages in https://github.com/nodejs/build/pull/2564, on IBM i installing the `python3` package overwrites `/QOpenSys/pkgs/bin/python` so that it points to Python 3 (3.6.12). However prior to running these changes on the IBM i machines (https://github.com/nodejs/build/issues/2507#issuecomment-791472742) `test-iinthecloud-ibmi72-ppc64_be-1` already had `python3` installed but `test-iinthecloud-ibmi72-ppc64_be-2` did not so we had a discrepancy anyway where one host's `python` pointed to Python 3 and the other to Python 2. Applying these changes to the two test machines has made them consistent and `python` points to the Python 3 installation.
Currently https://ci.nodejs.org/job/node-test-commit-ibmi/ is only run daily on the …

ansible: install Python 3 on IBM i

---

ansible/inventory.yml

Refs: https://github.com/nodejs/build/issues/2552
cc @mhdawson @jbergstroem 
Some oddities:
- ~I can't find a replacement for `test-joyent-ubuntu1804_docker-x64-1` in the table in https://github.com/nodejs/build/issues/2552. It also looks like all the hosts in https://ci.nodejs.org/search/?q=test-joyent that are containers (i.e. have the word "container" in their node names) are offline.~ Removed in this PR.
- It looks like `test-joyent-ubuntu1604_arm_cross-x64-1` and `release-joyent-ubuntu1604_arm_cross-x64-1` were removed from the inventory in https://github.com/nodejs/build/pull/2290/files#diff-6faf346b88ef5cbd5f6733c35ef37f0884f3fcc946a55c5b811843b652421f6d and possibly did not need to be migrated as we now cross compile in docker containers. The build history for …

ansible: update Joyent hosted IP addresses

---

ansible/roles/baselayout/vars/main.yml

The inventory changes are from https://github.com/nodejs/build/pull/2568 (so I can get the correct IP addresses to run the playbook against) and can be ignored.
Latest available Python 3 on SmartOS 17 appears to be Python 3.6.4, while on SmartOS 18 it is Python 3.7.1.
SmartOS 17:
```
python36-3.6.4 =     Interpreted, interactive, object-oriented programming language
python35-3.5.4nb1    Interpreted, interactive, object-oriented programming language
python34-3.4.7nb1    Interpreted, interactive, object-oriented programming language
```
SmartOS 18:
```
python37-3.7.1       Interpreted, interactive, object-oriented programming language
python36-3.6.7       Interpreted, interactive, object-oriented programming language
python35-3.5.6       Interpreted, interactive, object-oriented programming …
```

ansible: add Python 3 to SmartOS hosts

---

ansible/roles/docker/templates/alpine311.Dockerfile.j2

I've reansibled:
- test-digitalocean-ubuntu1804-docker-x64-1
- test-digitalocean-ubuntu1804-docker-x64-2
- test-softlayer-ubuntu1804-docker-x64-1
with these changes and restarted the alpine containers. The alpine 3.11 containers now container Python 3.8.2 in `/usr/bin/python3`.
Refs: https://github.com/nodejs/build/issues/2507

ansible: add Python 3 to alpine 3.11 container

---

ansible/roles/docker/templates/ubuntu1804_sharedlibs.Dockerfile.j2
jenkins/scripts/VersionSelectorScript.groovy

Add OpenSSL 3.0.0 alpha13 to the sharedlibs container. Add an entry to
the VersionSelectorScript to build against it with Node.js 15 onwards.
Update OpenSSL 1.1.1g to 1.1.1k.
Refs: https://github.com/nodejs/build/issues/2584

ansible,jenkins: add OpenSSL 3.0.0 to sharedlibs container

---

ansible/inventory.yml
ansible/playbooks/jenkins/worker/create.yml
ansible/plugins/inventory/nodejs_yaml.py
ansible/roles/baselayout/tasks/main.yml
ansible/roles/baselayout/tasks/partials/ccache/macos.yml
ansible/roles/java-base/tasks/main.yml
ansible/roles/java-base/vars/main.yml
ansible/roles/jenkins-worker/templates/start.j2
ansible/roles/jenkins-worker/vars/main.yml
ansible/roles/package-upgrade/tasks/partials/brew.yml

Update the ansible scripts to support apple silicon and add the three new M1 macs donated to us by macstadium.
@nodejs/build-infra can I get `207.254.38.74` added to the release ci firewall and `207.254.38.86` + `207.254.38.89`  to the test ci firewall please?
*The commented lines will be readded this branch is quite old so I had some bugs to iron out*

Add M1 macs 

---

ansible/roles/baselayout/vars/main.yml

Installs Python 3.8, enabled via `. /opt/rh/rh-python38/enable`.
Refs: https://github.com/nodejs/build/issues/2507
Currently Node.js 14 and later will build with Python 3. This maps to where we currently use gcc 8 to compile on arm64:
https://github.com/nodejs/build/blob/6882ed52582172c1b74eb67278b29e8aeb723495/jenkins/scripts/VersionSelectorScript.groovy#L26-L27

ansible: add Python 3 to centos7-arm64 hosts

---

jenkins/scripts/VersionSelectorScript.groovy

Ref: https://github.com/nodejs/build/issues/2445
I was looking at this today and I think it's actually all in place, even in our CIs we have labels for this to work. It's just a matter of turning it on and trying it out ...

armv7: enable gcc-8 for armv7 cross-compile

---

jenkins/scripts/VersionSelectorScript.groovy

enable building the pkg from 16 onwards with only the osx11 machine, enable building the release tar for osx11 on 16.

jenkins: enable building releases with osx11

---

ansible/roles/docker/templates/ubuntu1804_arm_cross.Dockerfile.j2
ansible/roles/docker/templates/ubuntu1804_sharedlibs.Dockerfile.j2

Builds on #2614, it turns out we didn't have gcc-8 ready in the cross compiler containers for host builds.
Also had to do the openssl-3-a14 update because a13 was having "not gzip content" errors (I couldn't replicate locally but upgrading to yesterday's release did the trick). I'm afraid this might have introduced new TLS failures from the one test run I've done so far. https://ci.nodejs.org/job/node-test-commit-linux-containered/26388/#showFailuresLink (test-crypto-dh-stateless & test-crypto-dh).
I'm also watching for some potential new failures from the gcc-8 armv7 builds, more runs need to shake out flakys. We'll also need to keep an eye on nightlies for the release version.
This is live now across the 4 containers in ci and 1 in ci-release.

docker: update containers - gcc8 for cross, openssl3-a14

---

ansible/inventory.yml

Removed:
release-requireio-osx1010-x64-1
release-scaleway-ubuntu1604-armv7l-1
release-scaleway-ubuntu1604-armv7l-2
test-requireio_rvagg-ubuntu1404-arm64_odroidxu-1
test-requireio_rvagg-ubuntu1404-arm64_odroidxu-2
test-requireio_rvagg-ubuntu1404-arm64_odroidxu3-1
test-requireio-osx1010-x64-1
Refs: https://github.com/nodejs/build/issues/2531

ansible: remove obsolete entries

---

jenkins/scripts/VersionSelectorScript.groovy

Ubuntu 16.04 does not have new enough gcc/g++/Python versions to
meet the minimum for Node.js 16 and is out of LTS support at the
end of April 2021.

jenkins: stop testing on ubuntu1604-64 for Node.js 16

---

ansible/roles/baselayout/tasks/main.yml
ansible/roles/baselayout/tasks/partials/repo/ubuntu1604.yml
ansible/roles/baselayout/vars/main.yml

The benchmarking machines used for testing V8 and benchmarking are
still Ubuntu 16.04 so will need updating to a more recent Python 3
to continue being able to build Node.js 16.

ansible: add Python 3 PPA for Ubuntu 16.04

---

ansible/roles/jenkins-worker/templates/rpi_stretch.Dockerfile.j2
ansible/roles/jenkins-worker/vars/main.yml

This also changes the base image to balenalib/rpi-raspbian:stretch.
The old one is no longer maintained.

ansible,docker: install Python 3.9 in Stretch RPi's

---

ansible/inventory.yml
ansible/playbooks/jenkins/host/create.yml
ansible/playbooks/jenkins/host/iptables.yml

Replace `infra-softlayer-ubuntu14-x64-1` as `ci-release` with
`infra-ibm-ubuntu1804-x64-1`.
Refs: https://github.com/nodejs/build/issues/2626

ansible: update `ci-release` in inventory

---

ansible/inventory.yml

@nodejs/build-infra can I get `83.147.191.75` added to the test ci and `83.147.191.76` added to the release ci

ansible: add extra M1 macs

---

ansible/inventory.yml

Remove:
test-mininodes-ubuntu1604-arm64_odroid_c2-1
test-mininodes-ubuntu1604-arm64_odroid_c2-2
test-mininodes-ubuntu1604-arm64_odroid_c2-3
test-scaleway-ubuntu1804-armv7l-2
test-scaleway-ubuntu1804-armv7l-3
Refs: https://github.com/nodejs/build/issues/2531

ansible: remove obsolete hosts

---

ansible/roles/docker/templates/ubuntu1804_sharedlibs.Dockerfile.j2

This commit update the version of OpenSSL 3.0 to use the quictls/openssl
fork. This for will be used until upstream OpenSSL includes support for
the QUIC protocol. At that point we can switch back to using upstream
again.

ansible: update OpenSSL 3.0 to use quictls/openssl

---

ansible/roles/baselayout/vars/main.yml

This is no longer in the CI so it should be alright to remove it.
Refs: https://github.com/nodejs/build/pull/2607

ansible: remove debian7

---

ansible/roles/package-upgrade/tasks/partials/apt.yml

Ansible's builtin `apt` task has had an `autoremove` option since
version 2.1 of the builtin. Using the builtin task rather than
directly running `apt` will correctly set the `DEBIAN_FRONTEND`
environment variable to `noninteractive` to prevent user prompts
from packages which would otherwise cause `apt` to wait for user
input (which will never come when run via Ansible).
Hosts at scaleway were removed from the inventory so there are no
longer any matching hosts.

ansible: fixes for apt package upgrades

---

ansible/www-standalone/resources/scripts/build-site.sh

The nodejs.org website build uses `fibers` which is broken on Node.js 16
due to an incompatibility with the version of V8 that it contains.
Switch the Docker image used to build the website from `node:latest` to
`node:lts` to buy some time for the website to migrate off `fibers`.
---
This is live -- I edited the script on the www server, tested it and then synced the changes into this PR via:
```
ssh www cat /home/nodejs/build-site.sh > build-site.sh
```
Fixes: https://github.com/nodejs/build/issues/2123#issuecomment-829551740

www: use `docker:lts` in `build-site.sh`

---

backup/README.md
backup/rsnapshot.conf

The first commit updates the copy of `rsnapshot.conf` we have in this repository with what is currently deployed on the backup server, taken via:
```
ssh backup cat /opt/local/etc/rsnapshot.conf > rsnapshot.conf
```
(FWIW it looks like we no longer take mysql dumps from the benchmark machine -- I think this was part of https://github.com/nodejs/build/issues/2485 with the de-chartering of the benchmarking WG (https://github.com/nodejs/TSC/pull/955).)
The second commit is a proposed change (not yet made) to also backup `/etc` from both CI servers. This will include nginx and telegraf (for grafana) configuration. Currently the whole of `/etc` is around 7mb on each server. I've left the existing Jenkins backup where it is to not disturb the diffs to the existing backups since those are large. …

backup: update rsnapshot configuration

---

ansible/www-standalone/tools/metrics/public-index.html

Give a new link to where the current summaries are currently stored. This pr is meant to be a stop gap so people can access the data if they want until someone has time and patience to redesign the website and backfill the gaps in the data.

metrics: Point to new metrics link

---

jenkins/scripts/VersionSelectorScript.groovy

I like to propose we stop testing 16.x on AIX71 - we list support as for AIX72 only and we only build the 16.x releases on AIX 72 meaning the binaries wont even run on AIX71.
cc @richardlau @mhdawson

jenkins: stop testing 16.x on AIX71

---

ansible/roles/docker/templates/ubuntu1804_sharedlibs.Dockerfile.j2

Tested locally, no new test failures with current nodejs/node master. In the process of deploying to our containers.

ansible: update to OpenSSL 3.0.0-alpha16+quic

---

ansible/roles/baselayout/tasks/main.yml
ansible/roles/baselayout/vars/main.yml
ansible/roles/jenkins-worker/tasks/partials/tap2junit/freebsd.yml
ansible/roles/jenkins-worker/templates/freebsd.initd.j2

- Update `python` to point to `python2` (for consistency with other
platforms in our CI; use `python3` for Python 3).
- Use `py38-pip` to match the version of Python 3 installed.
- Create a `pip3` symlink as Ansible's `pip` task fails without it.
- `-slaveLog` Jenkins agent parameter has been obsoleted. Use the
`-o` parameter to `daemon` to redirect stdout/stderr to the log file.
Refs: https://github.com/nodejs/build/issues/2531

ansible: fixes for freebsd

---

ansible/roles/bootstrap/tasks/partials/fedora.yml

Tasks registering variables in Ansible will alway set the variable
regardless of any `when` clause(s). This means if more than one task
registers the same variable, the last one "wins". Fix the bootstrap
role on Fedora by correctly registering `has_libselinux` in both
`fedora30` and non-`fedora30` cases.
Refs: https://github.com/nodejs/build/issues/2531
Fixes this error:
```
TASK [bootstrap : install libselinux-python bindings] ******************************************************************************************************
fatal: [test-digitalocean-fedora30-x64-2]: FAILED! => {"msg": "The conditional check 'os in (\"fedora30\") and has_libselinux.rc == 1' failed. The error was: error while evaluating conditional (os in (\"fedora30\") and has_libselinux.rc == 1): 'dict object' has no …
```

ansible: fix multiple register vars on Fedora

---

ansible/roles/baselayout/vars/main.yml
ansible/roles/docker/templates/ubuntu1804.Dockerfile.j2
ansible/roles/docker/templates/ubuntu1804_sharedlibs.Dockerfile.j2
jenkins/scripts/select-compiler.sh

Baseline gcc/g++ compiler version for Node.js 16 and above is 8. The
default `gcc` and `g++` packages on Ubuntu 18.04 install version 7.
Moves `gcc-6` and `g++-6` out of the common `ubuntu` packages into
`ubuntu1604` -- it doesn't seem worth installing a lower version of
GCC to the default for Ubuntu 18.04.
Update `select-compiler.sh` to select GCC 8 for Node.js 16 and later.
Refs: https://github.com/nodejs/build/issues/2445

ansible: add gcc-8 to Ubuntu 18.04 hosts/containers

---

ansible/plugins/inventory/nodejs_yaml.py

python3 is the default for python3 now with python pointing to python2.
This script fails on machines without python2 installed but as its
now EOL we should prefer python3

ansible: use python3 in nodejs_yaml

---

tools/host-map/host-map.mjs
tools/host-map/package.json

I've put together a little tool to visualize where our CI hosts are and highlight platforms which are spread across more than one provider. It parses the output of [`ansible/plugins/inventory/nodejs_yaml.py`](https://github.com/nodejs/build/blob/master/ansible/plugins/inventory/nodejs_yaml.py) so is dependent on this repository.
e.g. without the highlighting:
```
$ node . test
platform                |azure|do|ibm|iitc|joyent|macstadium|marist|msft|nf|orka|osuosl|packet|requireio|rs
--------                |-----|--|---|----|------|----------|------|----|--|----|------|------|---------|--
aix71-ppc64             |     |  |  2|    |      |          |      |    |  |    |      |      |         |  
aix72-ppc64             |     |  |   |    |      |          |      |    |  |    |     4|      | …
```

tools: add host-map tool

---

jenkins/scripts/select-compiler.sh

The `centos7-release-sources` part of the `iojs+release` job builds
the `node` binary and should select the compiler to use based on the
Node.js version being built. Put this logic in `select-compiler.sh`
(as is done for other platforms).
Refs: https://github.com/nodejs/build/issues/2671
Refs: https://github.com/nodejs/build/issues/2481
I'll also need to update the CI job to call `select-compiler.sh` (currently it directly enables devtoolset-6).

jenkins: add centos7-release-sources to select-compiler.sh

---

ansible/plugins/inventory/nodejs_yaml.py

For AWX we need to use the nodejs_yaml.py script to parse the inventory
however the file expects to be run from within the `ansible`
subdirectory.
As Adoptium use AWX and the same format script as us this PR uses their
solution to fix the problem.
refs: https://github.com/adoptium/infrastructure/pull/1730

ansible: provide absolute path in nodejs_yaml.py

---

ansible/roles/docker/templates/ubuntu1804_sharedlibs.Dockerfile.j2

Add versions of ICU to the sharedlibs containers. Intended to be used
to build and test Node.js against a system ICU:
e.g. for ICU 65
```
$ export PKG_CONFIG_PATH=$ICU65DIR/lib/pkgconfig
$ export LD_LIBRARY_PATH=$(pkg-config --variable=libdir icu-i18n)
$ export CONFIG_FLAGS='--with-intl=system-icu --verbose'
$ make run-ci
```

ansible: add ICU to sharedlibs containers

---

jenkins/scripts/select-compiler.sh

Selects gcc/g++ 8 on the benchmark machines when building Node.js 16
or later.
Fixes: https://github.com/nodejs/build/issues/2681

jenkins: use gcc 8 on the benchmark machines

---

ansible/MANUAL_STEPS.md
ansible/inventory.yml
ansible/roles/build-test-v8/meta/argument_specs.yml
ansible/roles/build-test-v8/meta/main.yml
ansible/roles/gn/meta/argument_specs.yml
ansible/roles/gn/tasks/main.yml
ansible/roles/jenkins-worker/tasks/main.yml
ansible/roles/ninja/meta/argument_specs.yml
ansible/roles/ninja/tasks/main.yml

Add `build-test-v8` meta-role for installing prerequisites for V8
building/testing. Add roles to build `gn` and `ninja` binaries from
source and call those from the `build-test-v8` role for Linux on
ppc64/s390x.
This removes a previously manual step from the Linux PPC/s390x setup (docs also updated).
I've deployed this onto
- test-ibm-rhel7-s390x-1
- test-ibm-rhel7-s390x-2
- test-ibm-rhel7-s390x-3
- test-ibm-rhel7-s390x-4
- test-osuosl-centos7-ppc64_le-1
- test-osuosl-centos7-ppc64_le-2
to update the version of `gn` (the version we'd previously manually compiled is now too old, see https://github.com/nodejs/node/pull/38990#issuecomment-858764907). 
We're now updated to:
```
[iojs@test-osuosl-centos7-ppc64--le-1 build-tools]$ ./ninja --version
1.10.2
[iojs@test-osuosl-centos7-ppc64--le-1 …
```

ansible: build gn from source on Linux PPC/s390x

---

ansible/roles/baselayout/vars/main.yml

Fixup copy/paste error and install g++-8 on Ubuntu 16.04.
Refs: https://github.com/nodejs/build/pull/2660

ansible: install g++-8 on Ubuntu 16.04

---

ansible/roles/bootstrap/tasks/partials/centos.yml
ansible/roles/bootstrap/tasks/partials/centos6.yml
ansible/roles/bootstrap/tasks/partials/debian9.yml
ansible/roles/bootstrap/tasks/partials/fedora.yml
ansible/roles/bootstrap/tasks/partials/freebsd.yml
ansible/roles/bootstrap/tasks/partials/ubuntu1604.yml
ansible/roles/bootstrap/tasks/partials/ubuntu1804.yml
ansible/roles/bootstrap/tasks/partials/zos.yml
ansible/roles/java-base/tasks/main.yml

In some places we use the Ansible `raw` task to execute a command on
the remote machine. Typically this is done to check for the presence
of a file. Ansible itself has no way of knowing if the command we are
executing makes modifications to the system so does not run `raw` tasks
when `ansible-playbook` is run with `--check`. Some of our subsequent
tasks rely on the `raw` task having previous run (to create a variable)
so the playbook currently errors with messages such as:
`'dict object' has no attribute ...`
when run in `--check` mode.
Mark `raw` tasks that do not make modifications with `check_mode: no`
(which means "don't check if `--check` was set and just execute the
command"). This allows us to run the playbook with `--check` first to
see what Ansible thinks would change without …

ansible: allow running playbook in check mode

---

ansible/roles/github-bot/templates/deploy-github-bot.sh.j2
ansible/roles/github-bot/templates/github-bot-deploy-webhook.json.j2

The nodejs/github-bot' default branch just changed to `main`. That also means our deploy procedure has to change accordingly, to listen for commits and pull from `main` as opposed to `master`.
Refs https://github.com/nodejs/github-bot/issues/302

github-bot: update deploy procedure after default branch change

---

ansible/MANUAL_STEPS.md

Document a manual step that has been run on our AIX 7.1 CI hosts to
remove the `en1` network interface containing an IPv6 link local
address.
Refs: https://github.com/nodejs/node/issues/39143
cc @AshCripps

ansible: remove `en1` interface on AIX 7.1

---

ansible/roles/baselayout/tasks/main.yml
ansible/roles/baselayout/vars/main.yml
jenkins/scripts/select-compiler.sh

Two build side fixes required together with https://github.com/nodejs/node/pull/39326 to address the currently broken C++ coverage.
- **ansible: downgrade to Python 3.7 on Ubuntu 16.04**
On Ubuntu 16.04 the `python3-pip` package is not compatible with
Python 3.8 and later. Downgrade Python 3 to Python 3.7 which is
new enough for building current Node.js (Python 3.6 or later) but
still compatible with the `python3-pip` package.
- **jenkins: set GCOV on Ubuntu to match CC/CXX**
Code coverage runs `gcov` but this needs to match the version of
gcc/g++ used.
Refs: https://github.com/nodejs/node/issues/39303
Refs: https://github.com/nodejs/node/pull/39326

Fixes for Ubuntu 16.04 to fix C++ coverage

---

ansible/roles/baselayout/vars/main.yml
ansible/roles/java-base/tasks/main.yml
ansible/roles/ninja/tasks/main.yml

V8 CI needs `glib2-devel` installed.
Also a commit to fix running in check mode.
Fixes: https://github.com/nodejs/build/issues/2702
Refs: https://github.com/nodejs/node/pull/39373#issuecomment-878994383

ansible: install glib2-devel on centos7-ppc64

---

ansible/playbooks/jenkins/worker/upgrade-jar.yml

When the certs expired on the main CI we had to upgrade the jenkins
agents to use the newer certs. When I tried this on the macs it failed
due to a hard coded `/home` which doesn't exist on mac. Used the create
playbook as the inspiration for this change.
I need to test this on mac before I can merge.

ansible: update `upgrade-jar.yml` to use a variable

---

ansible/inventory.yml
ansible/playbooks/create-awx.yml
ansible/playbooks/jenkins/worker/clear-workspace.yml
ansible/playbooks/jenkins/worker/restart-agent.yml
ansible/roles/awx/tasks/main.yml
doc/awx-setup.md

Currently a WIP, I have a server up and running created from this playbook I just need to:
I have also added a restart agent playbook which i will fill out with my OS/ARCHS which will be a sample that the build helpers can run themselves.
refs: https://github.com/nodejs/build/pull/1390 (Old PR)

ansible: add AWX install

---

ansible/roles/docker/templates/ubuntu1804_sharedlibs.Dockerfile.j2

Use the `maint/maint-*` branches of the ICU repository to build the
"system" ICU libraries. Node.js 12 requires patches on top of ICU 64
to pass intl tests which are present on the `maint/maint-64` branch
but not in the 64.2 release. These patches are present in the Node.js
source tree for `v12.x-staging` under [`tools/icu/patches`](https://github.com/nodejs/node/tree/v12.x-staging/tools/icu/patches) but these
are only applied when building ICU statically linked.

ansible: use `maint/maint-*` branches of ICU

---

ansible/roles/docker/templates/ubuntu1804_sharedlibs.Dockerfile.j2

This commit updates the version of quictls/openssl to 3.0.0-beta1. This
change will cause a test failure so it needs to be coordinated with
https://github.com/nodejs/node/pull/38753.

ansible: update to openssl-3.0.0-beta1

---

ansible/playbooks/jenkins/worker/clear-workspace.yml
ansible/playbooks/jenkins/worker/restart-agent.yml

Ensure a limit is set when running this potentially dangerous playbooks
which could cause a lot of damage if run against every machine in the
cluster

ansible: require a limit when running build helper tasks

---

ansible/roles/baselayout/tasks/main.yml

New versions of the `tar` package from the AIX Toolbox no longer
create the `/usr/bin/gtar` symlink. Ansible's `unarchive` task
attempts to find `gtar` before falling back to using `tar` but on
AIX `tar` is not the GNU version of `tar` and the `unarchive` task
is incompatible with it.
Similar to https://github.com/nodejs/build/issues/2536 / https://github.com/nodejs/build/pull/2537.

ansible: create `gtar` symlink on AIX

---

ansible/roles/docker/templates/ubuntu2004.Dockerfile.j2
ansible/roles/docker/templates/ubuntu2004_sharedlibs.Dockerfile.j2

Problem identified by @MylesBorins while building Node14 on the new Ubuntu 20.04 test system. (Fix went live yesterday, but this is the corresponding PR)

build,test: add python-is-python3 to ubuntu 20.04 dockerfiles

---

ansible/roles/docker/templates/centos7.Dockerfile.j2

"arm64 only" is due to the special way that I'm currently installing the devtoolset-6 packages in here for now. I feel this needs a better solution ...

build,test: Add CentOS7 Dockerfile (arm64 only for now)

---

doc/jenkins-guide.md

FYI GitHub's web UI has a button now with an auto-generated TOC but that doesn't help if you're reading the doc from a local checkout (e.g. via VSCode's markdown preview).
<details>
<summary>Screenshot of auto-generated TOC</summary>
</details>

doc: add TOC entry for Windows section

---

ansible/roles/docker/templates/centos7.Dockerfile.j2

[libuv-test-commit-linux](https://ci.nodejs.org/job/libuv-test-commit-linux) requires some additional packages which were not in the original CentOS7 dockerfile which is in use for the new aarch64 systems ([Ref issue](https://github.com/nodejs/build/issues/2729))
This has been deployed on the machines and those jobs can now run without prereq issues.

build,test: Add libuv prereqs to centos7 dockerfile

---

ansible/README.md

Sefl-explanatory - add a bit more information for people deploying docker host machines.

doc: flesh out a little more info on the docker-host playbook

---

ansible/www-standalone/tasks/site-setup.yaml

Fix the crontab so that `sync-benchmarking.sh` is only run once
every four hours and not every minute of every fourth hour.

www: run sync-benchmarking once every four hours

---

ansible/ansible.cfg
ansible/inventory.yml
ansible/roles/bootstrap/tasks/partials/fedora.yml

Update the two DigitalOcean Fedora 30 host to Fedora 34.
Refs: https://github.com/nodejs/build/issues/2527#issuecomment-911814447
> Reimaging was fairly painless but I ran into https://www.digitalocean.com/community/questions/fedora-33-how-to-persist-dns-settings-via-etc-resolv-conf (with Fedora 34) meaning our playbooks failed until I went onto the machine and fixed the DNS settings (as per https://www.digitalocean.com/community/questions/fedora-33-how-to-persist-dns-settings-via-etc-resolv-conf?answer=66950).
Deployed. Labels have been swapped so the existing Fedora 32 hosts are now `fedora-last-latest-x64` while the reimaged Fedora 34 hosts are now `fedora-latest-x64`.

ansible: update Fedora 30 hosts to Fedora 34

---

ansible/roles/baselayout/vars/main.yml
jenkins/scripts/select-compiler.sh

Node.js 16 requires a minimum gcc/g++ 8 compiler.

ansible: add gcc8 to SmartOS 18

---

ansible/roles/baselayout/vars/main.yml
jenkins/scripts/select-compiler.sh

This reverts commit 0eaed4617b672e33820c1ff3a88d2bca29e7333a.
Node.js builds with gcc8 on our SmartOS 18 hosts crash when running `torque`. Undo https://github.com/nodejs/build/pull/2754 to have passing builds again.
SmartOS is kind of outside my knowledge base, so I'd need help getting a suitable gcc 8.3 based environment.

Revert "ansible: add gcc8 to SmartOS 18 (#2754)"

---

ansible/roles/docker/templates/ubuntu1804_sharedlibs.Dockerfile.j2
ansible/roles/docker/templates/ubuntu2004_sharedlibs.Dockerfile.j2

Updates to latest OpenSSL 1.1.1 and 3.0.0. Not yet deployed as tests need to be updated in Node.js core to cope with error message changes between OpenSSL 3.0.0-alpha16 and 3.0.0-beta/final (e.g. we would need https://github.com/nodejs/node/pull/38512/commits/be21e9e74989d02ce71b88d667d20c044fd30c87 to land).
cc @danbev

update OpenSSL in sharedlib containers

---

jenkins/scripts/VersionSelectorScript.groovy

Unfortunately it turns out that the multijob plugin appears to have issues when resuming with subjobs that run the same job with different parameters. In preparation of converting the s390x LTO build from a second invocation of `node-test-commit-linuxone` (with `CONFIG_FLAGS` set to `--enable-lto`) to a second "platform", add the exclusion for Node.js versions earlier than 16 to the VersionSelectorScript.
Refs: https://github.com/nodejs/build/issues/2758

jenkins: skip LTO builds on Node.js < 16

---

ansible.cfg
ansible/plugins/inventory/nodejs_yaml.py
doc/ansible-testing.md

replacement of #2700.
After consulting with some ansible experts at Red Hat the best method to get AWX working is to move the `ansible.cfg` file to the root of the repo where AWX expects it.
What does this change? Nothing except for now we need to run our playbooks from the root directory instead - e.g. `ansible-playbook ansible/playbooks/playbook --limit "target"`
I think ive updated the doc but let me know if it appears elsewhere

ansible: move `ansible.cfg`

---

doc/disaster-recovery-plan.md

Initial version of a document containing pointers to how to recover critical parts of build infrastructure.
This is based on what we did to recover the release CI server last week (https://github.com/nodejs/build/issues/2626). It attempts to be descriptive rather than prescriptive because I don't expect we'll be able to predict the exact nature of a failure (should one occur).
The obvious takeaway for me after writing this is that we don't appear to have the nginx configuration for the two Jenkins servers backed up anywhere -- we were able to recover because @rvagg was able to rsync `/` from the old server in rescue mode. I'll look into what needs to be saved (maybe just rsnapshot all of `/etc/nginx`?) separately (mirroring updates to …

doc: add a disaster recovery plan

---

ansible.cfg
ansible/inventory.yml
ansible/roles/baselayout/tasks/main.yml
ansible/roles/baselayout/vars/main.yml
ansible/roles/jenkins-worker/tasks/partials/tap2junit/freebsd.yml

Updates our FreeBSD hosts from FreeBSD 11 to FreeBSD 12.
Refs: https://github.com/nodejs/build/issues/2768

ansible: update FreeBSD 11->12

---

ansible/playbooks/jenkins/host/iptables.yml
ansible/plugins/filter/filters.py

- Add a filter to skip over hosts that do not have an IP address, which
can happen if they have been removed from the main inventory but not
from secrets. Also filter out hosts that use hostnames instead of
numeric IP addresses (i.e. the Windows hosts).
Allow the proxy host look up when ansible is run in `--check` mode.
- Add filter for looking up IP addresses via `dig`. Add entries for
hosts that set their `ip` to a hostname instead of a numeric IP
address -- in the iptables rules we are adding these commented with
the supplied `ip` hostname rather than the name of the host.

ansible: update iptables playbook

---

jenkins/scripts/VersionSelectorScript.groovy

Current Ubuntu armv7l docker image is 20.04 and so needs to be excluded from Node 12.
I did this initially with another conditional but have modified it to try and catch all ubuntu2004 - can anyone see any issue with this (I don't think the 32/64 bit is necessarily significant?

Exclude ubuntu2004-armv7l execution on Node<12

---

ansible/inventory.yml

Repurpose unused test-softlayer-ubuntu1404-x86-1 as an additional
Ubuntu 18.04 x64 test host.

ansible: add test-ibm-ubuntu1804-x64-2

---

ansible/inventory.yml
ansible/roles/baselayout/vars/main.yml
ansible/roles/jenkins-worker/vars/main.yml
jenkins/scripts/VersionSelectorScript.groovy

Replace smartos17 hosts with smartos20.
Refs: https://github.com/nodejs/build/issues/2757
This has been deployed onto all the previous smartos17 hosts.

ansible: update smartos hosts

---

ansible/plugins/library/remmina_config.py

Add config and target data locations for Remmina packaged as a
Flatpak (e.g. for Fedora).
Enables `ansible/playbooks/write-ssh-config.yml` to write Remmina config on a system using Flatpaks.

ansible: add locations for Flatpak Remmina

---

GOVERNANCE.md
ansible/README.md
ansible/roles/package-upgrade/files/install-homebrew.sh
ansible/www-standalone/resources/config/nodejs.org
doc/jenkins-jobs.md
doc/resources.md

Minor housekeeping for repos that already did the the master -> main renames. Used HEAD so it's flexible for any future default branch changes

chore: master -> HEAD for renamed default branches

---

ansible/roles/docker/templates/ubuntu1804_sharedlibs.Dockerfile.j2
ansible/roles/docker/templates/ubuntu2004_sharedlibs.Dockerfile.j2
jenkins/scripts/VersionSelectorScript.groovy

Remove OpenSSL 1.1.0 as we no longer test against it in the CI.
Bump OpenSSL to OpenSSL 1.1.1m and OpenSSL 3.0.1+quic.
Refactor environment variables to allow CI to switch to using
more generic variable names for OpenSSL 3.

ansible: update OpenSSL versions

---

ansible/www-standalone/resources/config/logrotate-github-webhook
ansible/www-standalone/tasks/webhook.yaml

https://github.com/nodejs/build/issues/2760#issuecomment-1002242478
Long overdue. I've manually run this and it's 👌.
The main problem here is that I've put in a service stop and start. It's quite quick but this service is the parent of a docker build for the site. So if we happen to his this while the site is being built then there could be problems, so I'm not sure this is the best idea or approach.
I don't have time to go deeper into this but some thoughts:
* The service may not need to be stop & started, I don't recall if the log file is kept open or not, maybe this is a systemd redirect or maybe the service writes directly - someone could investigate this.
* We could add some kind of check to see whether it's running, not sure the best way to do this but we already have internal …

www,webhook: add logrotate for github-webhook

---

ansible/MANUAL_STEPS.md

Older versions of `gyp` in Node.js 12 and npm 6 (included in Node.js 12
and 14) cannot detect `Command Line Tools for Xcode` unless they have
been installed manually.
Refs: https://github.com/nodejs/build/issues/2728
Closes: https://github.com/nodejs/build/issues/2823

ansible: add CLT for Xcode macOS manual steps

---

ansible/inventory.yml
ansible/plugins/library/remmina_config.py
ansible/roles/visual-studio/tasks/partials/wixtoolset.yml

We changed the Azure subscription used for the CI machines, this PR updates the Ansible inventory. The new Windows ARM machines hosted by NearForm are also included (ref https://github.com/nodejs/build/issues/2540).
Two important changes were made:
- Removed VCBT2015 (not VS2015) machines and configurations, as the install package no longer works. Already removed from Jenkins as well. I believe testing with VS2015 provides enough coverage for a version so old.
- Only server images are supported on the new subscription, so I was not able to create Windows 10 machines. For now, I replaced it with Windows Server 2022. The server names don't yet reflect this everywhere, at least the VersonSelectorScript needs to be updated before the server names can change.
cc @nodejs/libuv, I swapped the …

Update Windows Inventory

---

README.md

Node.js Foundation doesn't exist anymore. We could replace instances of it in our README with OpenJS Foundation, but that wouldn't be accurate since we only provide infrastructure for Node.js Projects and libuv (afaik libuv isn't under OpenJSF either, which would also make our README inaccurate).

doc: s/Node.js Foundation/Node.js Project/g

---

ansible/MANUAL_STEPS.md
ansible/README.md
ansible/inventory.yml
ansible/playbooks/jenkins/worker/create.yml
ansible/roles/baselayout/tasks/main.yml
ansible/roles/baselayout/tasks/partials/repo/rhel8.yml
ansible/roles/baselayout/vars/main.yml
ansible/roles/bootstrap/handlers/main.yml
ansible/roles/bootstrap/tasks/main.yml
ansible/roles/bootstrap/tasks/partials/rhel8-s390x.yml
ansible/roles/bootstrap/tasks/partials/rhel8.yml
ansible/roles/gn/tasks/main.yml
ansible/roles/gn/vars/main.yml
ansible/roles/java-base/tasks/main.yml
ansible/roles/java-base/vars/main.yml
ansible/roles/jenkins-worker/handlers/main.yml
ansible/roles/jenkins-worker/tasks/main.yml
ansible/roles/jenkins-worker/vars/main.yml
ansible/roles/package-upgrade/vars/main.yml
ansible/roles/release-builder/files/ssh_config
ansible/roles/release-builder/meta/argument_specs.yml
ansible/roles/release-builder/meta/main.yml
ansible/roles/release-builder/tasks/main.yml
ansible/roles/release-builder/vars/main.yml
jenkins/scripts/VersionSelectorScript.groovy
jenkins/scripts/select-compiler.sh

Extend Ansible and Jenkins scripts for Red Hat Enterprise Linux 8.
TODO:

ansible: add RHEL 8 (initially s390x)

---

ansible/inventory.yml
ansible/roles/baselayout/tasks/main.yml
ansible/roles/baselayout/vars/main.yml
ansible/roles/bootstrap/tasks/partials/rhel7.yml
ansible/roles/build-test-v8/tasks/main.yml
ansible/roles/build-test-v8/tasks/partials/centos7.yml
ansible/roles/build-test-v8/tasks/partials/rhel7-s390x.yml
ansible/roles/build-test-v8/tasks/partials/rhel8.yml
ansible/roles/build-test-v8/tasks/partials/ubuntu1604.yml
ansible/roles/java-base/vars/main.yml
jenkins/scripts/select-compiler.sh

V8's `gclient.py` now requires `httplib2`. Install it on all the
machines that the V8 CI can run on.
Fixes: https://github.com/nodejs/build/issues/2880

ansible: add httplib2

---

ansible/inventory.yml
ansible/roles/baselayout/handlers/main.yml
ansible/roles/baselayout/tasks/main.yml
ansible/roles/baselayout/tasks/partials/ntp/chrony.yml
ansible/roles/baselayout/vars/main.yml
ansible/roles/build-test-v8/tasks/partials/rhel8-ppc64.yml
ansible/roles/build-test-v8/tasks/partials/rhel8-x64.yml
ansible/roles/java-base/tasks/main.yml
ansible/roles/jenkins-worker/tasks/main.yml
ansible/roles/package-upgrade/handlers/main.yml
ansible/roles/package-upgrade/handlers/partials/rhel8.yml
ansible/roles/package-upgrade/tasks/partials/dnf.yml
jenkins/scripts/VersionSelectorScript.groovy

Add new ppc64le RHEL 8 instances. Repurpose test-osuosl-centos7-ppc64_le-4
as an additional RHEL 8 instance.
Also ensure time synchronization via `chrony` on RHEL 8, and add a handler
to run when packages are updated to sync with Red Hat Subscription Manager.
Refs: https://github.com/nodejs/build/issues/2741
Refs: https://github.com/nodejs/build/issues/2815

ansible: add ppc64le RHEL 8 instances

---

ansible/roles/bootstrap/tasks/partials/rhel8-s390x.yml

The presence of `/etc/sysconfig/iptables.save` on our RHEL 8 s390x
instances is interfering with the loading of our iptables rules
when the system reboots.
Refs: https://github.com/nodejs/build/issues/2893#issuecomment-1067054317

ansible: remove `iptables.save` on rhel8-s390x

---

ansible/roles/docker/templates/ubuntu1804_sharedlibs.Dockerfile.j2
ansible/roles/docker/templates/ubuntu2004_sharedlibs.Dockerfile.j2

Otherwise, the tests using OpenSSL as a shared library would fail on CI.
Signed-off-by: Darshan Sen <raisinten@gmail.com>
cc @richardlau

ansible: update OpenSSL to 3.0.2+quic

---

ansible/roles/docker/templates/ubuntu1804_sharedlibs.Dockerfile.j2
ansible/roles/docker/templates/ubuntu2004_sharedlibs.Dockerfile.j2

Refactor the Docker templates so we only need to update the OpenSSL
1.1.1 version in one place. Update to OpenSSL 1.1.1n.

ansible: update OpenSSL to 1.1.1n

---

jenkins/scripts/VersionSelectorScript.groovy

We're starting to get upstream changes that require later glibc
than is available on CentOS 7. In addition, our nightly (and
eventually Node.js 18 onwards releases) binaries require later
glibc (2.28) which will not run on CentOS 7.
Refs: https://github.com/nodejs/build/issues/2815

jenkins: stop testing on centos7 for Node.js 18 onwards

---

ansible/roles/baselayout/tasks/main.yml
ansible/roles/java-base/tasks/main.yml
ansible/roles/jenkins-worker/templates/start.j2
ansible/roles/jenkins-worker/vars/main.yml
ansible/roles/package-upgrade/tasks/partials/brew.yml

Homebrew installs into a different path on M1 macs compared to x64.
Adjust the path to the ccache symlinks accordingly.
Refs: https://formulae.brew.sh/formula/ccache
cc @AshCripps

ansible: fix path to ccache symlinks on M1 macs

---

ansible/inventory.yml
ansible/playbooks/jenkins/worker/create.yml
ansible/roles/docker/tasks/main.yml
ansible/roles/docker/tasks/partials/repo/ubuntu2004.yml
ansible/roles/docker/templates/rhel8.Dockerfile.j2
ansible/roles/read-secrets/vars/main.yml
ansible/roles/release-builder/meta/argument_specs.yml
ansible/roles/release-builder/tasks/main.yml
jenkins/scripts/VersionSelectorScript.groovy

Adds two `c2.large.arm` Ampere eMag machines configured to run two
containers each:
- CentOS 7 container intended for Node.js earlier than 18
- RHEL 8 container intended for Node.js 18 and later
Add one RHEL 8 container to each of the Equinix test servers.

ansible: updates for Linux arm64

---

ansible/roles/docker/templates/ubuntu2004_armv7l.Dockerfile.j2

This dockerfile will be used on the aarch64 Altras to provide a faster way to build natively for arm32. We're already using a deployment of this for https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2004-armv7l after the experiments for #2775  and this will make it formal to make it easier to expand onto other machines.

ansible: add armv7l on aarch64 docker files

---

ansible/roles/jenkins-worker/tasks/main.yml

this was blocking me from even running the main worker/create playbook with ansible 2.x; the change here lets it play at least and makes warnings go away

ansible: make happy with latest ansible@2.x

---

ansible/roles/docker/files/cc-selector.sh
ansible/roles/docker/templates/debian10_armv7l.Dockerfile.j2
ansible/roles/docker/templates/rhel8_arm_cross.Dockerfile.j2
ansible/roles/jenkins-worker/templates/rpi_buster.Dockerfile.j2
ansible/roles/jenkins-worker/vars/main.yml
jenkins/scripts/VersionSelectorScript.groovy

Add a new RHEL 8 based container for cross compilation of armv7l
binaries for Node.js 18 using the recently added cross compiler
toolchain based on gcc 8 with glibc 2.28.
Adds a Debian 10 (Buster) container to the Pi's -- even though the Pi's
are running Debian 10 the tests are run in containers and prior to this
commit were running in Debian 9, which is on glibc 2.24.
---
The plan would be, at least initially, to continue testing older versions of Node.js in the stretch container but use the buster container for Node.js 18 onwards. Or do we think stretch is too old now we should move everything?

ansible: arm cross compiler updates for Node.js 18

---

jenkins/scripts/VersionSelectorScript.groovy

Refs: https://github.com/nodejs/node/pull/42666
Refs: https://github.com/nodejs/node/issues/42543#issuecomment-1094043762
cc @nodejs/platform-windows @nodejs/build @nodejs/v8-update 
---
This is the quick way to land https://github.com/nodejs/node/pull/42657 and get a clean CI for Node.js 18. The plan will be to reverse this as soon as possible when we're able to pick up a stable V8 which compiles on 32-bit Windows.

jenkins: temporarily exclude win32 for Node.js 18

---

jenkins/scripts/VersionSelectorScript.groovy

Full debug x64 builds have been unreliable in the CI in the sharedlibs
containers and were recently "turned off" by making the job a no-op.
However the job was still being started even if it didn't do anything
but pass -- this change prevents Jenkins from starting 
`sharedlibs_debug_x64` runs.
Refs: https://github.com/nodejs/build/issues/2837
---
cc @mhdawson 
We may end up reintroducing a "lighter" debug build (suggested in https://github.com/nodejs/node/issues/41209#issuecomment-1001261679) later but that would probably be better in its own job and not part of node-test-commit-linux-containered.

jenkins: only run sharedlibs_debug_x64 pre-18

---

jenkins/scripts/VersionSelectorScript.groovy

Run 32-bit Windows CI for Node.js 19 but skip (for now) on Node.js 18.
Introduce a new `gteLt` closure for exclusions between two versions.
Refs: https://github.com/nodejs/node/issues/42690
Refs: https://github.com/nodejs/node/pull/42740#issuecomment-1099282508
Refs: https://github.com/nodejs/build/pull/2921

jenkins: run win32 CI on Node.js 19

---

GOVERNANCE.md
README.md
doc/jenkins-guide.md

The Slack channel for the Build WG has been moved to #nodejs-build
on the OpenJS Foundation Slack instance.
Refs: https://openjs-foundation.slack.com/archives/C03BJP63CH0
Closes: https://github.com/nodejs/build/issues/2875

doc: update Build WG Slack channel

---

ansible/README.md

All links on git.io will stop redirecting after April 29, 2022.
- https://github.blog/changelog/2022-04-25-git-io-deprecation/

chore: remove git.io

---

doc/update-certificates.md

Add notes on website certificate renewal based on what was done
the last time we updated in January 2022.
Refs: https://github.com/nodejs/build/issues/2811
cc @nodejs/build-infra

doc: add certificate update notes

---

ansible/roles/docker/templates/ubuntu1804_sharedlibs.Dockerfile.j2
ansible/roles/docker/templates/ubuntu2004_sharedlibs.Dockerfile.j2

Refs: https://github.com/nodejs/node-v8/issues/223

ansible: add ICU 71 to `sharedlibs` images

---

ansible/roles/unofficial-builds/files/deploy-unofficial-builds.sh
ansible/roles/unofficial-builds/templates/unofficial-builds-deploy-webhook.json.j2

Opening up as a draft because the actual rename hasn't happened.

chore: update default branch for unofficial builds

---

ansible/playbooks/create-unofficial-builds.yml

Remove comment about creating local host_vars as the required
`github_deploy_webhook_secret` secret has been added to the
secrets repository.
Refs: https://github.com/nodejs/unofficial-builds/issues/35#issuecomment-1122259809

ansible: update create-unofficial-builds playbook

---

ansible/www-standalone/tasks/tools.yaml

Primary branch of https://github.com/nodejs/node has been changed
from `master` to `main`.
Refs: https://github.com/nodejs/node/issues/33864

ansible: update branch name for nightly builder

---

ansible/roles/jenkins-workspace/files/clean_binary_tmp.sh
ansible/roles/jenkins-workspace/tasks/main.yml

Fixes: https://github.com/nodejs/build/issues/2977
Refs: https://github.com/nodejs/node/issues/33864

ansible: update branch used in clean_binary_tmp.sh

---

ansible/inventory.yml

Machine was in the Works on Arm account and has been replaced by
two machines in the Node.js account at Equinix.
Refs: https://github.com/nodejs/build/pull/2910

ansible: remove release-equinix-centos7-arm64-1

---

ansible/MANUAL_STEPS.md
ansible/inventory.yml
ansible/playbooks/jenkins/worker/create.yml
ansible/roles/baselayout/tasks/main.yml
ansible/roles/baselayout/tasks/partials/ccache/aix.yml
ansible/roles/baselayout/tasks/partials/ccache/aix73.yml
ansible/roles/baselayout/vars/main.yml
ansible/roles/bootstrap/tasks/partials/aix.yml
ansible/roles/java-base/tasks/main.yml
ansible/roles/java-base/vars/main.yml
ansible/roles/jenkins-worker/tasks/partials/tap2junit/aix.yml
ansible/roles/jenkins-worker/tasks/partials/tap2junit/aix73.yml
ansible/roles/jenkins-worker/templates/aix.rc2.j2
ansible/roles/jenkins-worker/vars/main.yml
ansible/roles/package-upgrade/vars/main.yml
jenkins/scripts/select-compiler.sh

Replace AIX 7.1 VMs. Add set up for new AIX 7.3 VM.
Differences for AIX 7.3 from AIX 7.1/7.2 set up:
- `gcc-c+` package in [AIX Toolbox](https://www.ibm.com/support/pages/aix-toolbox-open-source-software-downloads-alpha) for AIX 7.3 is gcc 10. There are no earlier versions of gcc available for AIX 7.3 (we install `gcc6-c+` on AIX 7.2/7.1 but this is not available for 7.3 so we need to adjust the playbook accordingly).
- `ccache` doesn't exist in AIX toolbox (we are compiling it from source for AIX 7.2/7.1) but the toolbox does have a fork, `ccache-swig`, which this PR tries to use for AIX 7.3.
- Use Java 17 instead of 8 (since this is a new machine).
- AIX toolbox is migrating to `dnf` instead of `yum`. The AIX 7.3 instance we've been given appears to already have `dnf` installed.
Refs: …

ansible: AIX updates

---

jenkins/scripts/VersionSelectorScript.groovy

The Matrix Groovy Execution Strategy plugin appears to have an issue
on Java 11+ where string parameters are appearing as byte arrays
instead of strings. Use the new String() constructor instead of
toString() to ensure we get string repesentation of the parameter.
Refs: https://github.com/jenkinsci/matrix-groovy-execution-strategy-plugin/issues/20
Refs: https://github.com/nodejs/build/issues/2984#issuecomment-1227537524
We need this to unblock the Java update.

jenkins: add workaround for groovy script & Java 11+

---

jenkins/scripts/VersionSelectorScript.groovy

Guard against the `NODEJS_VERSION` parameter not being set, which
results in `parameters['NODEJS_VERSION']` being `null`.
Refs: https://ci.nodejs.org/job/node-compile-windows/46654/console
```
08:02:32 println "Node.js version: ${new String(parameters['NODEJS_VERSION'])}"
...
08:02:32 FATAL: Ambiguous method overloading for method java.lang.String#<init>.
08:02:32 Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
08:02:32 	[class [B]
08:02:32 	[class [C]
08:02:32 	[class java.lang.String]
08:02:32 groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method java.lang.String#<init>.
08:02:32 Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
08:02:32 	[class [B]
08:02:32 	[class [C]
08:02:32 	[class …
```

jenkins: guard potentially unset parameter

---

jenkins/scripts/VersionSelectorScript.groovy

This is a follow on to commit dce00d089e6266dd838eabec38d75e4f8dcd627e which doesn't work with the citgm-smoker-nobuild job where the default value is `v18` instead of `19.0.0` so it doesn't parse properly with the original solution. This almost certainly needs a bit of a rethink to get the value passed in in a consistent format if possible.
Fixes https://github.com/nodejs/build/issues/3023 (Subject to disclaimer in the last line of this description)
Looks to have broken the ability to run the citgm jobs. Once I fixed another issue in the citgm-smoker-nobuild job:
```
// SXA build#3023 // def verString = parameters['NODE_VERSION'].toString()
def verString = new String(parameters['NODE_VERSION'])
```
I hit this. I've patched the job to run from my branch just now.
NOTE: It is unclear yet …

Workaround for groovy script & Java 11+ in `citgm-smoker-nobuild`

---

ansible/inventory.yml

Update the name for the test CI server to reflect that it is running
on Ubuntu 22.04 instead of giving the impression it is running on
Ubuntu 14.04.
Refs: https://github.com/nodejs/build/issues/2984

ansible: update name for test CI server

---

doc/windows-visualstudio-supported-versions.md
jenkins/scripts/VersionSelectorScript.groovy

This removes rows for unsupported Node.js versions and removes support
for building addons with VS2015 starting with Node.js 19.0.0.

doc: update Windows and VS support tables

---

ansible/inventory.yml
ansible/roles/baselayout/vars/main.yml
ansible/roles/jenkins-worker/templates/systemd.service.j2

Add two new OSUOSL hosted arm64 release machines to replace the Equinix ones that are going away at the end of November 2022.
Updates the playbook for centos7 to drop devtoolset-6 which is no longer required since Node.js 12 went End-of-Life (Node.js 14 and 16 use devtoolset-8 and Node.js 18 and later are not built on centos7).
Refs: https://github.com/nodejs/build/issues/3028

ansible: add new OSUOSL arm64 release machines

---

ansible/inventory.yml

Remove from the inventory machines that were hosted at Packet/Equinix that have subsequently been migrated to other machines at Equinix and OSUOSL.
Refs: https://github.com/nodejs/build/issues/3028
Refs: https://github.com/nodejs/build/issues/2729

ansible: remove migrated Packet machines

---

ansible/roles/docker/templates/ubuntu1804_sharedlibs.Dockerfile.j2

`curl -sL https://zlib.net/zlib-1.2.12.tar.gz | tar zxv --strip=1` is 404

template: update zlib to 1.2.13

---

ansible/roles/metrics/files/index-generator/.gcloudignore
ansible/roles/metrics/files/index-generator/Dockerfile
ansible/roles/metrics/files/index-generator/index-generator.js
ansible/roles/metrics/files/index-generator/package.json

This is the small file that makes the simple website with links for
our metrics. It runs every time a new summary file is created
and replaces the `index.html` file at the root of the bucket

metrics: add index-generator file

---

ansible/inventory.yml
ansible/roles/docker/templates/ubuntu2004_sharedlibs.Dockerfile.j2

Refs: https://github.com/nodejs/build/issues/3028
---
Existing arm64 docker test hosts at Equinix are being migrated to a new data facility. This host at OSUOSL will hopefully tide us over until the migration completes, and afterwards be available as a fallback.

ansible: add new OSUOSL arm64 docker test host

---

ansible/group_vars/release.yml
ansible/group_vars/test.yml
ansible/roles/baselayout-windows/tasks/main.yml
ansible/roles/jenkins-worker-windows/tasks/main.yml

Node.js 14 is incompatible with Python 3.11. Pin Python 3 to 3.10.8.
Run Jenkins agent on Java 17.
---
Updated Windows CI hosts:
<details>
<summary>Outdated</summary>
We're using chocolatey to manage Python on the Windows machines and https://ci.nodejs.org/job/windows-update-reboot/ has updated the Windows machines to Python 3.11.0. Unfortunately, this has broken Node.js 14 builds:
- Firstly because of a hard version check: https://github.com/nodejs/node/pull/45191#issuecomment-1295858818
- Secondly, with the check removed building addons breaks due to the old version of node-gyp in npm 6: https://github.com/nodejs/node/pull/45231
So far it looks like the Node.js 14 build is only broken on 
- test-rackspace-win2012r2_vs2019-x64-4
- test-rackspace-win2012r2_vs2019-x64-5
even though other …

ansible: pin Python 3 to 3.10.8

---

doc/ssh.md

Removed empty space. 
If you are copy/pasting from github web is hard to detect the dead space in some editors. This dead space triggers [the error](https://github.com/nodejs/build/blob/main/ansible/plugins/library/ssh_config.py#L103) `Your ssh config lacks template stubs. Check README.md for instructions.`

fix: removed empty space

---

.github/workflows/push.yml

- Update Github actions runner from `ubuntu-latest` to `ubuntu-20.04`
- [See discussion around ubuntu versions](https://github.com/actions/setup-python/issues/543)
- [Fail detected in nodejs/build](https://github.com/nodejs/build/actions/runs/3519497549/jobs/5899537570)

fix: Anchored ubuntu version to support Python 2.7 in Github Actions

---

.github/workflows/push.yml

- Upgraded: `actions/setup-python@v1` -> `actions/setup-python@v4`
- Upgraded `actions/checkout@v2` -> `actions/checkout@v3`
- https://github.com/nodejs/build/pull/3086#issuecomment-1323683587

chore: upgrade github actions

---

ansible/roles/java-base/tasks/main.yml
ansible/roles/java-base/vars/main.yml
ansible/roles/jenkins-worker/vars/main.yml
ansible/roles/package-upgrade/tasks/partials/brew.yml

Refs: https://github.com/nodejs/build/issues/3030

ansible: install temurin JDK on macOS

---

ansible/roles/java-base/tasks/main.yml
ansible/roles/java-base/vars/main.yml
ansible/roles/jenkins-worker/vars/main.yml

Update smartos CI hosts to Java 11. Remove obsolete entries for older versions of smartos.
Refs: https://github.com/nodejs/build/issues/3030
---
Updated

ansible: update smartos hosts to Java 11

---

.github/dependabot.yml
.github/workflows/push.yml

Add Dependabot to update the Actions files. They are already mostly pinned to major versions, so there shouldn't be much noise from this.
Branch filter on the one job is to prevent double builds for the Dependabot branches

chore: add Dependabot for GitHub Actions

---

jenkins/scripts/VersionSelectorScript.groovy

This is preventing correct detection of when the RUN_ARM64_TESTS is checked in https://ci.nodejs.org/job/node-test-binary-windows-js-suites/  similar to the changes we had to make in  https://github.com/nodejs/build/pull/3019/files when updating the version of java on the server.
Without this change you get this error because the value is a byte array `[116, 114, 117, 101]`.
```
17:15:46 Skipping win10-arm64-COMPILED_BY-vs2019-arm64 because RUN_ARM64_TESTS is not selected
```
regardless of whether the box is checked.

Fix detection of RUN_ARM64_TESTS in Windows test jobs

---

.github/workflows/push.yml

- Drop support for Python 2.7 in Github actions (bf699f951d7f941f61b1b207649c4de78764b8c1)
This PR was originated in https://github.com/nodejs/build/pull/3086#issuecomment-1323683587 and the Python 2.7 drop should be confirmed in #2659
This PR is polluted with the payload for #3092, please focus the review on bf699f951d7f941f61b1b207649c4de78764b8c1 only.

chore: Removed python2.7 from gh actions

---

ansible/plugins/library/remmina_config.py
ansible/plugins/library/ssh_config.py

Current versions of Remmina uses XDG directories for its configuration file and data directory.
Refs: https://gitlab.com/Remmina/Remmina/-/wikis/Usage/Remmina-Usage-FAQ
---
Tested on Fedora 37 running in WSL 2 on Windows 10.

ansible: search XDG directories for Remmina config

---

jenkins/scripts/select-compiler.sh

Recently released shellcheck 0.9.0 adds a new check:
```
SC2317 (info): Command appears to be unreachable. Check usage (or
ignore if invoked indirectly).
```
Fix the one instance of this that is causing the CI to now fail with the updated version of shellcheck.
Refs: https://github.com/koalaman/shellcheck/commit/642ad8612597b28af4026bde289985583fddb69d

jenkins: fix shellcheck linter CI

---

jenkins/download-test.sh

If no matches for `NODE_VERSION` are found, bail out of the script. Previously if no matches were found the following rsync would attempt to download the entire `downloadDir`, e.g., for `release`, every release we've done!
---
See https://ci.nodejs.org/job/validate-downloads/2011/console which ran out of disk space trying to rsync everything in `release` because mirroring from www to unencrypted was broken (due to the IP change for unencrypted -- I've now updated the firewall on www for the unencrypted's new IP address) and the new versions were not mirrored to unencrypted.

jenkins: handle no matches in download-test.sh

---

ansible/roles/package-upgrade/files/install-homebrew.sh

The Ruby Homebrew installer is now disabled.
See https://raw.githubusercontent.com/Homebrew/install/HEAD/install
```
#!/usr/bin/ruby
abort <<EOS
Error: The Ruby Homebrew installer is now disabled and has been rewritten in
Bash. Please migrate to the following command:
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
EOS
```

ansible: update install-homebrew script

---

ansible/roles/package-upgrade/tasks/partials/brew.yml

Duplicated brew Upgrade installed packages step in order to allow failure due deprecation (`You are using macOS 10.14.\nWe (and Apple) do not provide support for this old version.`) in macos10.x but keep macos11 the same
- Fix https://github.com/nodejs/build/issues/3119#issuecomment-1359162400
I am not sure if there is a more elegant way to condition `ignore_errors` rather than duplicate tasks 😅

fix: deprecation errors in macos 10.x

---

ansible/inventory.yml
ansible/playbooks/jenkins/worker/create.yml

Update the second benchmark machine to Ubuntu 18.04.

ansible: upgrade test-nearform_intel-ubuntu1604-x64-2

---

README.md

I would like to add Stefan Stojanović (@StefanStojanovic) to the Build WG, giving him test level access. I can handle any task that requires higher access for now.
Stefan has been working with me on Node.js, focusing on Windows, and he has more bandwidth than I've had recently. I will help him ramp up and would we're aiming to have him increasingly help more.
He'll start by creating a small guide on how to provision a Windows machine for testing, to unblock https://github.com/nodejs/build/issues/3137 and allow other people to do it as well.

meta: add Stefan Stojanovic to test

---

ansible/inventory.yml

Updates "joyent" labeled machines with their updated IP addresses.
Refs: https://github.com/nodejs/build/issues/3108
Also renames the test machines with new label "equinix_mnx" to more accurately reflect where they are now hosted. We'll need to rename the release and infra machines too but I won't have time to do that this year.
---
Currently re-ansibling machines to pick up the name change (this list has the old names):

ansible: update IP addresses for "joyent" machines

---

ansible/roles/build-test-v8/tasks/partials/rhel8-ppc64.yml
ansible/roles/build-test-v8/tasks/partials/rhel8-s390x.yml
ansible/roles/build-test-v8/tasks/partials/rhel8-x64.yml

Recent upstream V8 changes now require at least Python 3.8 to run the V8 test runner.
Refs: https://github.com/nodejs/node-v8/issues/244#issuecomment-1401830840
Refs: https://chromium-review.googlesource.com/c/v8/v8/+/4181030
---
I've deployed this onto all of the RHEL 8 ppc64le, s390x and x64 test machines. (We don't currently run the V8 CI on the RHEL8 x64 machines because the builds on those take a lot longer than on the Nearform-hosted Intel machine(s).)

ansible: update V8 builders to Python 3.9

---

ansible/group_vars/release.yml
ansible/playbooks/jenkins/worker/upgrade-jar.yml

- jenkins: download release worker jar from ci-release
- jenkins: allow to upgrade jar of release CI workers

Fix update of release CI worker jar

---

ansible/playbooks/create-windows-custom-vm.yml
ansible/roles/baselayout-windows/tasks/main.yml
doc/create-windows-custom-vm.md

This PR adds a new playbook, based on `jenkins/worker/create.yml`, and a guide on how to use it to set up a custom Windows VM for building and testing Node.js.
This PR also removes python 2 from Windows machines, since it is no longer used, plus it comes up in the `PATH` variable before python 3.
Refs: https://github.com/nodejs/build/issues/3137

Playbook and guide for creating windows custom VM

---

ansible/www-standalone/tasks/nginx.yaml

Serve `.lib` files with `application/octet-stream` content-type.
Refs: https://github.com/nodejs/build/issues/3194

ansible: add lib as application/octet-stream type

---

ansible/MANUAL_STEPS.md
ansible/inventory.yml
ansible/roles/bootstrap/tasks/partials/win.yml
ansible/roles/visual-studio/tasks/partials/vs2019.yml

This PR contains a few changes for Windows machines in the CI:
- We've noticed there were problems running ansible against RackSpace Windows test machines. @joaocgreis investigated and fixed that. He also updated the manual steps guide so others do not run into this same issue.
- This PR also adds Windows 11 ARM64 machines to the inventory. This is a follow on PR for https://github.com/nodejs-private/secrets/pull/246 which already updated the secrets repo.
- Non-server Windows versions eg. Windows 10 and 11, are showing a **finish setting up device** screen after rebooting occasionally, and this was leaving newly added Windows 11 ARM64 machines offline after running [windows-update-reboot](https://ci.nodejs.org/view/All/job/windows-update-reboot/). That behavior is disabled now, and this …

Windows ansible updates

---

ansible/www-standalone/resources/config/nodejs.org

This PR introduces several Nginx changes that simplify the current configuration and fix current bugs.
- Merge HTTP and HTTPS `server` blocks for redirects
- Removes non-needed configuration from the default nodejs.org:80 server block
- Removes the nodejs.org:80 redirect to nodejs.org:443 server block in favor of a `return 301 rule`
- Removes legacy rules such as (/blog redirecting to blog.nodejs.org), which could cause a "too many redirects" error
- Fixes the blog.nodejs.org:80 configuration which caused "too many redirects" and was broken
- Removed broken server rules such as the newsletter.nodejs.org
- Fixed broken foundation.nodejs.org location rules to the respective links of openjsf.org:443
- Reorganised the file (first both 80/443 ports for nodejs.org then all the extras)
- Added …

chore(nginx): updated nodejs.org configuration

---

ansible/www-standalone/resources/config/nodejs.org

This PR adds no-cache for 404 pages

chore(404): no cache for 404

---

ansible/www-standalone/resources/config/nodejs.org

This PR updates the cache_file cache to `100000`, fixes rewrites by removing their `/` trailing slash, and remove unnecessary `try_files` from known failing conditions.

chore(nginx): improve try_files, fix rewrites, increase file cache

---

jenkins/scripts/select-compiler.sh

Hopefully fixes broken [node-test-node-addon-api-new jobs on AIX](https://ci.nodejs.org/job/node-test-node-addon-api-new/nodes=aix72-ppc64/).
[node-test-commit-aix](https://ci.nodejs.org/job/node-test-commit-aix/) unsets LIBPATH with this comment:
```console
unset LIBPATH
```
`select-compiler.sh` was previously unsetting LIBPATH prior to https://github.com/nodejs/build/pull/3205
https://github.com/nodejs/build/pull/3205/files#diff-9f85ac8aaf936da8062466648fef7b7f930a32362ff3d65e6ed74a8cf3cc4495L161

jenkins: unset LIBPATH on AIX in select-compiler.sh

---

ansible/www-standalone/resources/scripts/check-build-site.sh

After the switch to Next.js, `/home/www/nodejs/en/index.html` no longer exists.

www: update checked html page

---

README.md

I am interested to join the Build WG, for the purpose of eventually getting familiar enough with the infrastructure so that I can help handle issues.
CC @richardlau

meta: add MoLow to test

---

ansible/roles/baselayout/vars/main.yml

V8 CI requires libatomic.
---
e.g. https://ci.nodejs.org/job/node-test-commit-v8-linux/5239/nodes=rhel8-s390x,v8test=v8test/console
```console
13:42:18 FAILED: torque 
13:42:18 python3 "../../build/toolchain/gcc_link_wrapper.py" --output="./torque" -- g++ -pie -Werror -Wl,--fatal-warnings -Wl,--build-id -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -m64 -rdynamic -Wl,-z,defs -Wl,--as-needed -pie -Wl,--disable-new-dtags -Wl,-O2 -Wl,--gc-sections -o "./torque" -Wl,--start-group @"./torque.rsp"  -Wl,--end-group  -latomic -ldl -lpthread -lrt
13:42:18 /opt/rh/gcc-toolset-10/root/usr/bin/ld: cannot find -latomic
13:42:18 collect2: error: ld returned 1 exit status
```

ansible: add gcc-toolset-10-libatomic-devel on RHEL8

---

jenkins/scripts/windows/compile.cmd

This PR is a continuation of [WiX4 PR](https://github.com/nodejs/node/pull/45943) that implements a runtime detection of the WiX version used for the MSI (required because of the LTS versions). If WiX4 is detected, the MSI for Windows ARM64 is created.
We've created a temporary job for testing these changes before opening PR [here](https://ci.nodejs.org/view/All/job/joaocgreis-node-compile-windows/). As visible from runs, detection works as expected.
Refs: https://github.com/nodejs/node/pull/45943

Adding ARM64 Windows MSI to Jenkins

---

jenkins/scripts/VersionSelectorScript.groovy

After adding ARM64 Windows machines to CI and stabilizing the tests, it is time to complete https://github.com/nodejs/build/issues/3046 and enable the tests to run by default.
This PR makes it so, but only for Node.js 19 and above, as the tests are not stable on LTS versions.
This is currently in use in Jenkins. This was applied in https://github.com/nodejs/jenkins-config-test/compare/f94d4652ce4d902263f0967922f6a1482c8a48c4...3133da6f058c16b56e02370500e135c16fb79740 and I will revert the url changes once this lands.
Fixes: https://github.com/nodejs/build/issues/3046

jenkins: run ARM64 Windows tests on Node.js >=19

---

ansible/roles/docker/templates/rhel8.Dockerfile.j2
ansible/roles/docker/templates/rhel8_arm_cross.Dockerfile.j2
ansible/roles/docker/templates/ubi81.Dockerfile.j2
ansible/roles/docker/templates/ubuntu1804.Dockerfile.j2
ansible/roles/docker/templates/ubuntu1804_arm_cross.Dockerfile.j2
ansible/roles/docker/templates/ubuntu1804_sharedlibs.Dockerfile.j2

the default installed python version for these environments is 3.6.8, 
the minimal supported version for the latest `tap2junit` is 3.7
this forces the installation of a later version
ref: https://github.com/nodejs/build/issues/3268

ansible: use explicit python version on containers

---

ansible/roles/docker/templates/alpine311.Dockerfile.j2
ansible/roles/docker/templates/alpine312.Dockerfile.j2
ansible/roles/docker/templates/centos7.Dockerfile.j2
ansible/roles/docker/templates/debian10_armv7l.Dockerfile.j2
ansible/roles/docker/templates/rhel8.Dockerfile.j2
ansible/roles/docker/templates/rhel8_arm_cross.Dockerfile.j2
ansible/roles/docker/templates/ubi81.Dockerfile.j2
ansible/roles/docker/templates/ubuntu1604.Dockerfile.j2
ansible/roles/docker/templates/ubuntu1604_arm_cross.Dockerfile.j2
ansible/roles/docker/templates/ubuntu1804.Dockerfile.j2
ansible/roles/docker/templates/ubuntu1804_arm_cross.Dockerfile.j2
ansible/roles/docker/templates/ubuntu1804_sharedlibs.Dockerfile.j2
ansible/roles/docker/templates/ubuntu2004.Dockerfile.j2
ansible/roles/docker/templates/ubuntu2004_armv7l.Dockerfile.j2
ansible/roles/docker/templates/ubuntu2004_sharedlibs.Dockerfile.j2
ansible/roles/docker/vars/main.yml

Due to docker layer caching, it makes more sense to pin to a specific version than rebuild the entire image

ansible: use explicit tap2junit version on containers

---

ansible/roles/metrics/files/process-cloudflare/process-cloudflare.js
ansible/www-standalone/tools/metrics/download-counts.awk
ansible/www-standalone/tools/promote/expected_assets/v19.x

This change brings Windows ARM64 one step closer to being a tier 2 supported platform, as described in https://github.com/nodejs/node/pull/47233.
With these changes, Windows ARM64 assets will get picked when releasing the following versions of NodeJS. Please note that these changes are partial, the rest of the required changes (eg. modifying the release job) will be done by @joaocgreis.

Add Windows ARM64 assets to release

---

jenkins/scripts/VersionSelectorScript.groovy

Build official ARM64 releases only for Node.js >= 19.
Once https://github.com/nodejs/node/pull/47233 lands, I will apply the changes from https://ci-release.nodejs.org/job/joaocgreis-iojs+release/ to the main job.
This can land sooner because nothing changes unless the job is changed as well.
Refs: https://github.com/nodejs/build/pull/3262

jenkins: release ARM64 Windows for Node.js >= 19

---

ansible/roles/baselayout-windows/tasks/main.yml
ansible/roles/baselayout-windows/vars/main.yml
ansible/roles/baselayout/tasks/main.yml
ansible/roles/baselayout/vars/main.yml
ansible/roles/jenkins-worker/tasks/partials/tap2junit/aix.yml
ansible/roles/jenkins-worker/tasks/partials/tap2junit/aix73.yml
ansible/roles/jenkins-worker/tasks/partials/tap2junit/freebsd.yml
ansible/roles/jenkins-worker/tasks/partials/tap2junit/macos.yml
ansible/roles/jenkins-worker/tasks/partials/tap2junit/macos10.14.yml
ansible/roles/jenkins-worker/tasks/partials/tap2junit/pip.yml
ansible/roles/jenkins-worker/tasks/partials/tap2junit/smartos.yml
ansible/roles/jenkins-worker/tasks/partials/tap2junit/ubuntu.yml
ansible/roles/jenkins-worker/tasks/partials/tap2junit/ubuntu2204.yml
ansible/roles/jenkins-worker/vars/main.yml

Fixes: https://github.com/nodejs/build/issues/3268
Fixes: https://github.com/nodejs/node/issues/47048

ansible: use explicit tap2junit version

---

ansible/roles/docker/files/cc-selector.sh
ansible/roles/docker/templates/rhel8_arm_cross.Dockerfile.j2
jenkins/scripts/VersionSelectorScript.groovy

Update RHEL 8 container used for cross compiling for armv7. 
Add logic to select gcc 10 toolchain for Node.js 20 onwards. 
Install gcc-toolset-10 host compiler.
Refs: https://github.com/rvagg/rpi-newer-crosstools/pull/2
Refs: https://github.com/orgs/nodejs/discussions/45892
Refs: https://github.com/nodejs/node/issues/47067

ansible: update RHEL 8 cross compiler container

---

README.md

I would like to increase the level of access for Stefan Stojanović (@StefanStojanovic), to give him access to release servers and include him in both jenkins-admins teams.
Stefan will maintain the Windows release servers going forward and help with Windows issues as necessary.
cc @nodejs/build @nodejs/jenkins-admins @nodejs/jenkins-release-admins

meta: add Stefan Stojanovic to release and admins

---

ansible/inventory.yml
ansible/roles/build-test-v8/tasks/partials/rhel8-x64.yml
ansible/roles/build-test-v8/tasks/partials/ubuntu2204.yml

Fixes: https://github.com/nodejs/build/issues/3206

ansible: add `ninja-build` to x64 V8 builders

---

doc/meetings/build-wg-meeting-2023-04-11.md

close https://github.com/nodejs/build/issues/3297

docs: meeting minutes 2023-04-11

---

ansible/roles/jenkins-worker/tasks/partials/tap2junit/rhel8.yml

`tap2junit` 0.1.6 requires Python >=3.7.
Use the installed `python3` (currently Python 3.9) rather than `/usr/libexec/platform-python` which is Python 3.6.8.
Fixes: https://github.com/nodejs/build/issues/3306

ansible: fix tap2junit installation for RHEL 8

---

ansible/roles/jenkins-worker/meta/main.yml

When invoking dependent roles from the `jenkins-worker` role, do not hardcode `/home` as the user's directory may be in a different parent directory.

ansible: do not hardcode `/home`

---

jenkins/scripts/windows/compile.cmd

After promoting Windows on ARM64 to a tier 2 platform, as a part of the compilation job in the CI, the ARM64 MSI installer is created. The first node-test-commit-windows-fanned build that did this was 54061. Since then, I've been monitoring all ARM64 builds, and until now, there's been a bit over 750 (the last build checked is 54823).
I noticed that 15 builds, roughly 2%, failed when downloading the x64 node.exe used for generating the license file. Changes proposed here tend to minimize, if not remove errors by caching the x64 node.exe and updating it weekly.
I've already tested these changes in my [job that tests migrating to VS2022](https://ci.nodejs.org/view/All/job/mefi-node-compile-windows-vs2022/) (another topic for another day) and saw no issues.

jenkins: cache x64 node.exe for arm64 license file

---

ansible/inventory.yml
ansible/roles/baselayout/vars/main.yml
ansible/roles/java-base/vars/main.yml
ansible/roles/jenkins-worker/vars/main.yml
ansible/roles/package-upgrade/vars/main.yml
jenkins/scripts/select-compiler.sh

AIX 7.1 is no longer used in the CI once Node.js 14 reaches End-of-Life.
Refs: https://github.com/nodejs/build/issues/3325

ansible: remove AIX 7.1

---

ansible/roles/jenkins-workspace/tasks/main.yml

Fixes: https://github.com/nodejs/build/issues/3329

ansible: update node from 14 to 16

---

ansible/roles/jenkins-worker/templates/git-wrapper.j2

Tag `.git/config` as iso8859-1 to prevent it being interpreted as EBCDIC.
Refs: https://github.com/nodejs/build/issues/3320#issuecomment-1520565578

ansible: update `git-wrapper` for z/OS

---

tools/wwwspace/prune.sh

Script as described in https://github.com/nodejs/build/issues/3125
This is the script which will clear up the nightlies and v8-canary directories so they do not constantly increase the disk space. If we are happy with this logic we can determine how to run it - either
- As a part of the release process before or after copying new builds there
- Via a regular cron job
- Something else?

www: create script to free space by removing old builds

---

ansible/inventory.yml
ansible/roles/baselayout/vars/main.yml
ansible/roles/bootstrap/tasks/partials/fedora.yml

Refs: https://github.com/nodejs/build/issues/3350

ansible: replace old ubuntu1404 DO host with fedora38

---

doc/meetings/build-wg-meeting-2023-05-23.md

close https://github.com/nodejs/build/issues/3362

Added 2023-05-23 meeting notes

---

ansible/www-standalone/resources/scripts/build-site.sh

Temporarily switch to `node:lts-bullseye` while we investigate why the website build is broken with `node:lts`/`node:lts-bookworm`.
Refs: https://github.com/nodejs/build/issues/3382

www: use node:lts-bullseye in build-site.sh

---

ansible/inventory.yml

This PR cleans the Windows portion of the `inventory.yml` file partially. It removes the deleted machines and changes the renamed ones from Windows 10 to Windows 2022 (more details [here](https://github.com/nodejs/build/pull/2860)). More PRs similar to this one can be expected in the following period since I'll be working on updating the Windows test matrix.
After landing this, I'll make the necessary changes in the secrets repo to follow these ones.
Refs: https://github.com/nodejs/build/issues/3373

ansible: update windows VMs in inventory

---

doc/release-overview.md

Add failover www server and unofficial-build servers. 
Add relationships for Cloudflare CDN.
Use appropriate symbols for manual processes and storage.
Refs: https://github.com/nodejs/build/pull/3377#issuecomment-1585480554
--- 
Preview: https://github.com/nodejs/build/blob/richardlau-release-overview/doc/release-overview.md
I've tried to balance including stuff vs overcomplicating the diagram. In particular, anything that doesn't interact with build owned/managed infrastructure is omitted.
cc @nschonni

doc: add more stuff to release overview

---

ansible/roles/jenkins-workspace/tasks/main.yml

The new upload method for Coverity requires parsing a JSON response from the new Coverity API.
Refs: https://github.com/nodejs/build/issues/3343

ansible: install `jq` on `jenkins-workspace`

---

ansible/MANUAL_STEPS.md
ansible/playbooks/update-windows.yml

While creating new Windows machines for the CI, I noticed that the part of the `MANUAL_STEPS` regarding the removal of HTTP WinRM ports can be automated. As a result, this change was made.

ansible,doc,win: document update creds process

---

ansible/playbooks/create-windows-custom-vm.yml
ansible/playbooks/jenkins/worker/create.yml
ansible/roles/github-windows/tasks/main.yml

Added github-windows role. based on an already existing github role. It does the same job on Windows and is used in jenkins-worker/create.yml playbook.
Refs: https://github.com/nodejs/build/pull/3265

ansible: add role to update known_hosts on windows

---

jenkins/scripts/VersionSelectorScript.groovy

This PR enables using VS2022 machines in test CI.
The changes proposed here were tested for some time in [this job](https://ci.nodejs.org/view/All/job/mefi-node-compile-windows-vs2022/) and no issues were spotted. This is the first step in transitioning to using VS2022 for compiling and ultimately, for building releases. For the time being full compilation will be done with both VS2019 and VS2022 (we have the capacity for this), and VS2019 will later be used only for compiling the x64 version (similarly to how VS2017 was used).
Note to reviewers: I'd like to land this ASAP, thus not waiting ~48 hours as I usually do after the PR is approved. If you agree with this, feel free to land the changes yourself after approving them. Thanks in advance.

jenkins: add vs2022 to version selector script

---

ansible/www-standalone/resources/config/nodejs.org

This PR is the last piece from the series of PRs for improving our NGINX config. It does the following:
- Heavily documents our NGINX directives
- Tidies the rewrite rules from blog.nodejs.org
- Fixes a few minor rewrites not happening for static assets due to `^~ /static` location block
- Removes a few non-existing rewrites
- And some other very minor tweaks

chore(nginx): some minor fixes and documented the config

---

README.md

Run `ncu-team sync README.md`.
This includes elevating @UlisesGascon 's access to include `infra` and `release`.

doc: update team members with ncu-team sync

---

ansible/roles/build-test-v8/tasks/partials/centos7.yml
ansible/roles/build-test-v8/tasks/partials/rhel7-s390x.yml
ansible/roles/build-test-v8/tasks/partials/rhel8-ppc64.yml
ansible/roles/build-test-v8/tasks/partials/rhel8-s390x.yml

Ensure `httplib2` and `six` modules are installed for Python 3 on machines with the `build-test-v8` role.
Refs: https://github.com/nodejs/node/issues/48728
Refs: https://github.com/nodejs/node/pull/48710#issuecomment-1628953014

ansible: install V8 build deps for Python 3

---

ansible/www-standalone/resources/config/nodejs.org

Rules created in https://dash.cloudflare.com/07be8d2fbc940503ca1be344714cb0d1/nodejs.org/rules/redirect-rules
Example:

chore(nginx): move redirected subdomains to Cloudflare rules

---

ansible/www-standalone/resources/scripts/build-site.sh

Ignore npm install scripts. This makes the dependencies install faster
and avoids a crash that happens when Playwright attempts to install
browsers.

fix(website): optimize and fix build-site.sh

---

ansible/www-standalone/resources/scripts/build-site.sh

This PR omits the installation of `devDependencies` at all since we don't need them for a successful build. The CI on `nodejs.org` uses the same arguments (In case a PR breaks these, the CI checks on `nodejs.org` would prevent this from being deployed).
We also removed the funding and audit checks as they're not required during this webhook.

chore: only production dependencies and omit funding and audit checks

---

ansible/inventory.yml

Refs: https://github.com/nodejs/build/issues/3350

ansible: replace fedora34-x64-1 with fedora38-x64-2

---

jenkins/scripts/VersionSelectorScript.groovy

- Remove lines that only exclude EoL versions
- Reference currently supported versions everywhere

jenkins: cleanup VersionSelectorScript.groovy

---

jenkins/scripts/VersionSelectorScript.groovy

I got the list of existing labels from the configuration matrix sections in https://ci.nodejs.org/job/node-test-commit-linux/configure and https://ci-release.nodejs.org/job/iojs+release/configure

jenkins: remove outdated labels from VersionSelectorScript.groovy

---

GOVERNANCE.md

There is no Node.js foundation any more as far as I'm aware - so remove the word "foundation" following Node.js in the doc.

meta: doc nit - no foundation

---

doc/update-certificates.md

Fix "ceriticate"->"certificate".

doc: fix typo in web certificates docs

---

ansible/roles/baselayout/vars/main.yml
ansible/roles/docker/templates/centos7.Dockerfile.j2
ansible/roles/docker/templates/ubuntu1804_sharedlibs.Dockerfile.j2
ansible/roles/docker/templates/ubuntu2004_sharedlibs.Dockerfile.j2
jenkins/scripts/select-compiler.sh

Refs: https://github.com/nodejs/build/issues/3317

ansible,jenkins: install and use GCC 10 on ubuntu2004_sharedlibs

---

ansible/README.md

Just a minor change in the doc:
- Ensure that the macOS user is using Python 3 by default with Ansible and that is properly installed.
- Deprecate references to Python 2

Improve documentation regarding python3 in macOS

---

jenkins/scripts/select-compiler.sh

Debug builds are not suffixed with `_sharedlibs` so were not matching the intended case selection.
Refs: https://github.com/nodejs/build/pull/3485#issuecomment-1728060439
cc @targos

jenkins: fix arm64 debug build compiler selection

---

ansible/roles/docker/templates/ubuntu2004.Dockerfile.j2
ansible/roles/docker/templates/ubuntu2004_armv7l.Dockerfile.j2

Refs: https://github.com/nodejs/build/pull/3493#discussion_r1331916486
Refs: https://github.com/nodejs/build/pull/3485#discussion_r1324718608
---
Deployed to:

ansible: install gcc-10 in remaining Ubuntu 20.04 containers

---

ansible/www-standalone/ansible-playbook.yaml
ansible/www-standalone/tasks/cloufdflare.yaml
ansible/www-standalone/tools/promote/_promote.sh
ansible/www-standalone/tools/promote/promote_release.sh
ansible/www-standalone/tools/promote/resha_release.sh
ansible/www-standalone/tools/promote/settings
ansible/www-standalone/tools/promote/upload_to_cloudflare.sh

While I believe assets can be copied directly from Jenkins in many cases, I think it is better to start with this approach where everything is promoted from within the www server.
this still doesn't handle the latest soft links. see discussion https://github.com/nodejs/release-cloudflare-worker/issues/33

release: copy cloudflare assets when promoting

---

doc/windows-visualstudio-supported-versions.md
jenkins/scripts/VersionSelectorScript.groovy

Refs: https://github.com/nodejs/node/pull/49051
/cc @StefanStojanovic I think the test CI is ready for this, but the release CI isn't. Can you help with that?

jenkins,doc: update supported Visual Studio for v21

---

ansible/inventory.yml
ansible/roles/bootstrap/tasks/partials/linux-swap.yml
ansible/roles/bootstrap/tasks/partials/rhel8.yml
ansible/roles/bootstrap/vars/main.yml

Add task to the bootstrap role for creating and enabling a file based
swap area.
Adds 4Gb of swap to release-osuosl-rhel8-arm64-1.
Fixes: https://github.com/nodejs/build/issues/3520

ansible: add swap for release-osuosl-rhel8-arm64-1 

---

ansible/roles/user-create/tasks/main.yml

On IBM i group profiles are a subset of user profiles therefore
user profiles and group profiles can't have the same name
In this case I created group named grp and added the server_user to the group
This change was made to help with test failures that expect the test runner user profile to be part of a group.
Ref: https://github.com/libuv/libuv/issues/4143
CC 
@nodejs/platform-ibmi 
@richardlau

ansible: create group on ibm i

---

jenkins/scripts/windows/compile.cmd

It was noticed on a few occasions that x64 node.exe caching is error-prone. This happens due to issues with downloading the new node.exe which, if it goes bad, makes the machine unusable for arm64 compilation for a week. This improvement in caching logic removes that possibility, by validating the downloaded file's SHASUM and replacing the old one with it, only if it matches the SHASUM found in the official `SHASUMS256.txt` file.
Fixes: https://github.com/nodejs/build/issues/3504
Refs: https://github.com/nodejs/build/pull/3315

jenkins: improve x64 node.exe caching for arm64

---

jenkins/scripts/VersionSelectorScript.groovy

This will remove macOS 10.x release machines in Jenkins pipelines.
On November 1, 2023 macOS 10.x won't be able to notarize the binaries.
Related: https://github.com/nodejs/build/issues/3385#issuecomment-1729281269
Related: https://github.com/nodejs/node/pull/50291

jenkins: remove macOS 10.x release machines

---

ansible/inventory.yml

This will remove macOS 10.x release machines from the inventory
On November 1, 2023 macOS 10.x won't be able to notarize the binaries.
Related: https://github.com/nodejs/build/issues/3385#issuecomment-1729281269
Related: https://github.com/nodejs/node/pull/50291

Remove macOS 10.x release machines from inventory

---

README.md

Seems like https://ci-health.nodejs.org/#/job-summary is not working anymore. This remove the reference in the `README.md`

docs: removed old reference

---

ansible/inventory.yml
ansible/roles/baselayout/vars/main.yml

Refs: https://github.com/nodejs/build/issues/3317

ansible: replace DO ubuntu1604-x86 hosts with ubuntu2204-x64

---

ansible/www-standalone/tools/promote/upload_to_cloudflare.sh

As of now, symlinks are currently being copied into R2 as two completely separate directories. The release worker handles the symlinks manually though as of nodejs/release-cloudflare-worker#39. This means we can just ignore any symlinks when syncing with R2 since they should never be read from (e.g. the worker should never be trying to read nodejs/release/latest/ from the bucket, instead nodejs/release/v21.0.0).
cc @MoLow

ansible: don't copy symlinks to R2 buckets

---

ansible/MANUAL_STEPS.md

This will be the first step for https://github.com/nodejs/build/issues/3545. This step creates the kaychain profile `NODE_RELEASE_PROFILE` that later on will be used while notarizing the binaries. [Code reference](https://github.com/nodejs/node/blob/main/tools/osx-notarize.sh#L38).
This PR change is only for documentation. The updated machines were tested in a separate PR (https://github.com/nodejs/node/pull/50715) in the Node repo while updating the `xcrun notarytool submit` command in `/tools/osx-notarize.sh`
The following machines have been updated manually:
- Related: https://github.com/nodejs/build/issues/3545
- Secrets update: https://github.com/nodejs-private/secrets/pull/295

docs: add manual step for OSX Keychain profile

---

ansible/roles/docker/templates/debian11_armv7l.Dockerfile.j2
jenkins/scripts/VersionSelectorScript.groovy

Refs: https://github.com/nodejs/build/issues/3499

ansible: upgrade armv7l containers to Debian 11

---

jenkins/scripts/VersionSelectorScript.groovy

Remove debian8 as all machines were replaced.
Refs: https://github.com/nodejs/build/issues/3499

jenkins: skip debian10 for Node.js >=21

---

jenkins/scripts/VersionSelectorScript.groovy

We already have coverage for Ubuntu 20.04.
Refs: https://github.com/nodejs/build/issues/3317

jenkins: skip ubuntu1804-arm64 on Node.js >=21

---

ansible/inventory.yml

Refs: https://github.com/nodejs/build/issues/2933
Compared to the previous one, which had 12 containers, this only has 9 (can be changed later). I removed:
- test-digitalocean-ubuntu1604_container-x64-1
- test-digitalocean-ubuntu1804_container-x64-1
- test-digitalocean-ubuntu1804_arm_cross_container-x64-1
I'm running the playbook now.

ansible: replace DO Ubuntu 18.04 sharedlibs container (1) with 22.04

---

jenkins/scripts/select-compiler.sh

Refs: https://github.com/nodejs/build/issues/3317#issuecomment-1848998715
---
This needs a corresponding change in [node-test-commit-linux-containered](https://ci.nodejs.org/job/node-test-commit-linux-containered/) to call `select-compiler.sh` on the [ubi81_sharedlibs_openssl111fips_x64](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/) configuration.
e.g. Insert the following at the top of the script:
```console
export CCACHE_BASEDIR=$PWD
curl -sLO https://raw.githubusercontent.com/nodejs/build/main/jenkins/scripts/select-compiler.sh
. ./select-compiler.sh
```
Test build using `select-compiler.sh` from `main` (still defaults to gcc 8 as it falls through all conditionals): 
- …

jenkins: enable `select-compiler.sh` on UBI8

---

ansible/roles/jenkins-worker-windows/templates/jenkins.bat

This PR addresses issues with updating Temurin17 on Windows machines in the CI. The changes proposed here ensure that the Temurin17 upgrade is tried every time the machine is rebooted. This is the only time when this can safely be done because once the machine is connected to Jenkins, upgrading will break the connection and leave the machine hanging until someone manually restarts Jenkins or reboots the machine.
The second part of this fix is in `windows-update-reboot` job (to be done after this lands, but there is a test job used for working on the change [mefi-windows-update-reboot](https://ci.nodejs.org/view/housekeeping/job/mefi-windows-update-reboot/)). This job will no longer upgrade the Temurin17 chocolatey package but will detect if it is outdated and force a reboot in that case. …

ansible,win: fix temurin17 update breaking jenkins

---

ansible/roles/docker/templates/rhel8.Dockerfile.j2
ansible/roles/docker/templates/rhel8_arm_cross.Dockerfile.j2
ansible/roles/docker/templates/ubi81.Dockerfile.j2

Add the `gcc-toolset-10` version of `binutils` to all RHEL 8 based containers.
Refs: https://github.com/nodejs/build/issues/3595#issuecomment-1861284497
---
Untested.

ansible: add gcc-toolset-10-binutils

---

jenkins/scripts/VersionSelectorScript.groovy

While working on adding new Windows 10 and 11 machines to the CI I noticed that some configurations were getting excluded in the native add-on tests when they should be included. After some investigation, I narrowed it down to VS2019 machines. This change fixes that behavior as seen from tests done in this [temporary copied job](https://ci.nodejs.org/view/All/job/mefi-node-test-binary-windows-native-suites/).

jenkins: fix vs2019 exclusion for native suites job

---

doc/windows-visualstudio-supported-versions.md
jenkins/scripts/VersionSelectorScript.groovy

This is necessary for C++20 compat.
Refs: https://github.com/nodejs/node/pull/45427

jenkins,doc: remove support for building addons with VS2017

---

ansible/inventory.yml

This PR removes old Azure Windows machines and adds new ones (Windows 10 and 11). This is already changed in the CI and it's been working for some time without any issues.

ansible: update azure windows VMs in inventory

---

doc/jenkins-guide.md

- The Build repository issue is created by the Security release steward and not the Build WG.
- Clarify the CI may need to be locked down earlier than 24 hours ahead of the planned release date.
- Separate the steps for announcing the CI lock down from the steps to perform the CI lock down.
- Mention announcing the CI lock down to the #nodejs-core Slack channel.
- Reflect new location of theme settings in most recent versions of Jenkins.

doc: revise Security releases guide

---

ansible/roles/docker/tasks/partials/repo/ubuntu1804.yml
ansible/roles/unofficial-builds/tasks/main.yml
ansible/roles/unofficial-builds/vars/main.yml

Ref: https://github.com/nodejs/unofficial-builds/issues/119
This is going to have to be a good-enough-for-now solution. The box is an 18.04 and the latest Node.js I could get on it using this method is 16.x. But that works with dist-indexer and with the newer `npm exec` method, so the original thing is fixed. I didn't have time to experiment with running Node from a snap, which might have been a better solution here. But ultimately this thing needs to be upgraded from 18.04 and then other options open up. Probably just a `do-release-upgrade` in place I think. :shrug: works for now, will think about it later or next time it breaks.

ansible: update unofficial-builds scripts to run again, install newer node

---

ansible/roles/baselayout/vars/main.yml

Add gcc 12 and 13 to our RHEL 8 machines.
---
Semi-related to https://github.com/nodejs/build/issues/3630, this PR will add gcc-toolset-12 and gcc-toolset-13 to our RHEL 8 machines, which gives us the ability to do test builds with gcc 12 and/or gcc 13. It does not switch the compiler selection to build Node.js -- that will be done in a follow up PR.

ansible: add gcc-toolsets 12 and 13 to RHEL 8

---

ansible/inventory.yml

Remove test-softlayer-ubuntu1404-x64-1 which is in an IBM data center (SJC1) that is closing.
Replace with [test-ibm-ubuntu2204-x64-1](https://ci.nodejs.org/computer/test-ibm-ubuntu2204-x64-1/).
Refs: https://github.com/nodejs/build/issues/3279

ansible: migrate test-softlayer-ubuntu1404-x64-1

---

ansible/inventory.yml

Remove test-ibm-ubuntu1804-x64-2 which is in an IBM data center (SJC1) that is closing.
Replace with [test-ibm-ubuntu2204-x64-2](https://ci.nodejs.org/computer/test-ibm-ubuntu2204-x64-2/).
Refs: https://github.com/nodejs/build/issues/3279
---
I'm unable to create new Ubuntu 18.04 servers in IBM Cloud, so I've opted for another Ubuntu 22.04.

ansible: migrate test-ibm-ubuntu1804-x64-2

---

ansible/inventory.yml

Replaced with test-digitalocean-fedora39-x64-1
Refs: https://github.com/nodejs/build/issues/3350

ansible: upgrade test-digitalocean-fedora32-x64-1

---

jenkins/scripts/windows/buildpulse.cmd
jenkins/scripts/windows/modify-build-url.ps1
jenkins/scripts/windows/test.cmd

This commit adds initial BuildPulse support by optionally uploading test results there. If the machine is not configured to connect to BuildPulse, or if any condition is not met, the data will not be sent. If the upload fails, the test job will just continue.
For now, this is a PoC and only Windows machines can upload results. If we decide to move forward with it, other platforms will be added.
The current situation in the CI is that only the recently added Windows 10 and Windows 11 machines (8 in total) are configured to send the data. There is also this [copy of node-test-commit-windows-fanned](https://ci.nodejs.org/job/mefi-buildpulse-node-test-commit-windows-fanned/) which I used to test the flow while working on these changes.
Once this lands, we'll start gathering results from all …

jenkins,win: add buildpulse support

---

ansible/inventory.yml

Replace the [release-ibm-rhel8-x64-2](https://ci-release.nodejs.org/computer/release%2Dibm%2Drhel8%2Dx64%2D2/) hosted in SJC1 to a new server (hosted at DAL13).
Refs: https://github.com/nodejs/build/issues/3279

ansible: migrate release-ibm-rhel8-x64-2

---

ansible/inventory.yml
ansible/roles/baselayout/tasks/partials/repo/rhel9.yml
ansible/roles/baselayout/vars/main.yml
ansible/roles/bootstrap/tasks/partials/rhel9.yml
ansible/roles/java-base/vars/main.yml
ansible/roles/jenkins-worker/tasks/partials/tap2junit/rhel9.yml
ansible/roles/jenkins-worker/vars/main.yml
ansible/roles/package-upgrade/handlers/partials/rhel9.yml
ansible/roles/package-upgrade/vars/main.yml

Replace test-centos7-x64-1 which was hosted on IBM Cloud at SJC1 (which is closing) with a new IBM Cloud hosted server running RHEL 9.
Refs: https://github.com/nodejs/build/issues/3279

ansible: add test-ibm-rhel9-x64-1

---

ansible/roles/linux-perf/tasks/main.yml

This change ensures that perf is installed in alignment with the kernel version of the host machine. 
As suggested in #3515

ansible: install perf matching the kernel version

---

ansible/inventory.yml
jenkins/scripts/VersionSelectorScript.groovy
jenkins/scripts/select-compiler.sh

Since v16 went EoL, RHEL8 is used for all release lines.
TODO:
- Remove from secrets repo
- Delete DO droplet

ansible,jenkins: rm centos7-release-sources host

---

ansible/inventory.yml

Add swap memory to DigitalOcean hosted rhel8-x64 droplets so that they are similar to the IBM Cloud hosted ones.
Refs: https://github.com/nodejs/build/issues/3669

ansible: add swap to DigitalOcean rhel8-x64 VMs

---

ansible/inventory.yml
ansible/roles/baselayout/vars/main.yml

Refs: https://github.com/nodejs/build/pull/3663
---
Created with custom image `rhel-9.3-x86_64-kvm.qcow2` uploaded to DigitalOcean from https://access.redhat.com/downloads/content/rhel.

ansible: add test-digitalocean-rhel9-x64-1

---

ansible/inventory.yml

Closes: https://github.com/nodejs/build/issues/3681

ansible: upgrade test-digitalocean-ubuntu1804_docker-x64-2 to Ubuntu 22.04

---

ansible/roles/baselayout/vars/main.yml
ansible/roles/build-test-v8/files/gcc-bug-113960.patch
ansible/roles/build-test-v8/tasks/partials/rhel8-s390x.yml
ansible/roles/gn/vars/main.yml
jenkins/scripts/select-compiler.sh

- ansible: add libatomic-devel to gcc toolsets
- ansible: build newer version of gn
- jenkins: use gcc 12 on rhel8-s390x for Node.js 22
Refs: https://github.com/nodejs/build/issues/3630
Fixes: https://github.com/nodejs/build/issues/3335

use gcc 12 on rhel8-s390x for Node.js 22

---

jenkins/scripts/windows/buildpulse.cmd

During the last 2 weeks, BuildPulse PoC's been in place in a part of the Windows CI. I noticed that part of the builds were uploaded, but not processed. After investigating it, I learned those were the PR builds for which rebasing the feature branch on the master was required. The issue there was that `GIT_COMMIT` environment variable was not the SHA code of the commit being tested because of rebasing.
After discussing this issue with @siddhantdange, he proposed a change, which I tried and it works. That change is in this PR.
Pinging @nodejs/build for review,
Refs: https://github.com/nodejs/build/pull/3653

jenkins,win: fix buildpulse for rebased PRs

---

ansible/inventory.yml
ansible/roles/bootstrap/tasks/partials/debian12.yml

Adds 2GB swap to
- test-digitalocean-debian11-x64-1
- test-digitalocean-debian12-x64-1
- test-softlayer-debian12-x64-1
in an attempt to stabilize the CI after recent V8 updates.

ansible: add 2GB swap to debian x64 hosts

---

jenkins/scripts/VersionSelectorScript.groovy

The minimum supported gcc compiler for Node.js 20 is gcc 10.
Refs (from https://github.com/nodejs/node/pull/52793): https://ci.nodejs.org/job/node-test-commit-arm/52344/nodes=ubuntu1804-arm64/

jenkins: exclude ubuntu1804-arm64 for Node.js 20

---

jenkins/scripts/VersionSelectorScript.groovy

Required to enable C++20 support.
Refs: https://github.com/nodejs/node/pull/45427

jenkins: skip Alpine 3.18 on Node.js >=23

---

jenkins/scripts/VersionSelectorScript.groovy

Required if we want to backport C++20 support on Node.js 22.
Refs: https://github.com/nodejs/node/pull/52838

jenkins: skip Alpine 3.18 on Node.js >=22

---

jenkins/scripts/select-compiler.sh

Refs: https://github.com/nodejs/node/pull/52838
I think it makes sense as this is a lower version than the default one.

jenkins: always select gcc-11 on Debian 12

---

ansible/roles/baselayout-windows/tasks/main.yml

Windows ARM64 cross-compiled node.exe cannot be extracted from `.7z` file on Windows 11 because of the way the latest version of 7-zip (v23.01) packs it. This pins the `7zip` and `7zip.install` Chocolatey packages to the version that works.
This change is already applied to all machines that do compilation in both release and test CI (VS2019 and VS2022 machines in Rackspace)
Fixes: https://github.com/nodejs/build/issues/3695

ansible: pin 7-zip to 22.01

---

ansible/roles/java-base/tasks/main.yml

Pass an empty `body` when fetching AdoptOpenJDK metadata to prevent getting a 403 error from CloudFlare.
Fixes: https://github.com/nodejs/build/issues/3710

ansible: fix adoptopenjdk metadata fetch

---

ansible/roles/visual-studio/tasks/partials/vs2022.yml

This is a part of an effort to enable compilation with Clang on Windows. This commit enables building with ClangCL in the CI.
This change is already applied to all VS2022 machines in the test and release CI. Note, that changing `params` for the `win_chocolatey` doesn't trigger installing a new component, so I installed these components manually on the existing machines.
After everything is ready in the main repo, I'll rework Jenkins jobs and make changes needed to this repo to enable compiling and testing Clang compiled Node.js.
Fixes: https://github.com/nodejs/build/issues/3709

ansible: add ClangCL to VS2022

---

ansible/roles/baselayout/tasks/partials/repo/rhel8.yml
ansible/roles/build-test-v8/tasks/partials/rhel8-ppc64.yml
ansible/roles/build-test-v8/tasks/partials/rhel8-s390x.yml
ansible/roles/build-test-v8/tasks/partials/rhel8-x64.yml

Fixes: https://github.com/nodejs/build/issues/3718

ansible: install Python 3.9 on RHEL 8

---

ansible/MANUAL_STEPS.md
ansible/inventory.yml
ansible/playbooks/jenkins/worker/create.yml
ansible/roles/jenkins-workspace/tasks/main.yml

Supersedes https://github.com/nodejs/build/pull/3715 (I can't push to that, possibly because I rebased onto current main).
Closes: https://github.com/nodejs/build/issues/3713
Deployed onto [test-ibm-ubuntu2204-x64-3](https://ci.nodejs.org/computer/test%2Dibm%2Dubuntu2204%2Dx64%2D3/).

ansible: replace Ubuntu 18.04 Jenkins workspace with 22.04

---

jenkins/scripts/windows/ci-cleanup.cmd
jenkins/scripts/windows/node-compile-windows.cmd
jenkins/scripts/windows/test.cmd
jenkins/xml/citgm-smoker.xml

CI runs for PR https://github.com/nodejs/node/pull/52646 fail because the `embedtest.exe` is not packaged along with other binary files and it cannot be found by the test being enabled.
This PR changes Jenkins Windows scripts to treat `embedtest.exe` the same way as `cctest.exe`.
The only difference is that we check that `embedtest.exe` file exists.
It must unblock the PR https://github.com/nodejs/node/pull/52646.

jenkins: pack embedtest.exe for Windows builds

---

README.md

I would like to include Stefan Stojanovic (@StefanStojanovic) in the infra admin team.
Stefan has fully ramped up and taken all of my tasks related to Node.js. I believe he is fully prepared and his help will be valuable in maintaining the Windows infrastructure. With full access to infra, Stefan can create and delete Windows machines himself, debug Jenkins issues, and generally be proactive in maintaining the Windows machines.
I can remain on the team as a backup for a while longer, but given my level of involvement, I will eventually move to emeritus.
Stefan will need to be added to the @nodejs/build-infra team by someone with permission if this is approved. I can add him to the secrets repo folder and will check if I can create a Rackspace account for him.
cc @nodejs/build

meta: add Stefan Stojanovic to infra admins

---

jenkins/scripts/VersionSelectorScript.groovy

Refs: https://github.com/nodejs/node/pull/53184

jenkins: stop building on 32-bit Windows for Node.js 23

---

ansible/inventory.yml
ansible/plugins/inventory/nodejs_yaml.py
ansible/roles/baselayout/vars/main.yml
ansible/roles/jenkins-worker/tasks/partials/tap2junit/smartos.yml
ansible/roles/jenkins-worker/vars/main.yml

The four hosts are provisioned that will replace the smartos18/20 testing hosts.
I still need access to the test jenkins to get secrets to complete making these available to jenkins.

Ansible: updates to support smartos21/23 test hosts.

---

ansible/playbooks/jenkins/host/iptables.yml

ci-release had no iptables defined (but they were preserved in /etc/iptables/rules.v4)
This ensures that on reboot those rules get reloaded.

ansible: ensure iptables-persistent is installed on jenkins hosts

---

ansible/roles/docker/templates/ubuntu2204_sharedlibs.Dockerfile.j2

- [ansible: remove ICU 68 from sharedlibs containers](https://github.com/nodejs/build/commit/d5ee0b3221b68879aed6cd151f8cead92d2f964b) 
The earliest supported Node.js version we still build in the CI is 18.x.
For Node.js 18.x, the minimum supported version of ICU is 69.
- [ansible: add OpenSSL 3.2 to sharedlibs containers](https://github.com/nodejs/build/commit/719daecd26ab07f3bec7e50e6ab8b074ac165dd4)

ansible: update sharedlibs containers

---

ansible/roles/metrics/files/index-generator/Dockerfile
ansible/roles/metrics/files/process-cloudflare/Dockerfile
ansible/roles/metrics/files/summaries/Dockerfile

Refs: https://github.com/nodejs/build/issues/3697#issuecomment-2137861247
I went through the JavaScript source code run in these Dockerfiles, and verified that there are no Node.js APIs being used which were deprecated between Node.js 14.x and 20.x
cc @richardlau

ansible: update nodejs to 20 in Dockerfile

---

ansible/roles/metrics/files/process-cloudflare/process-cloudflare.js

Refs: https://github.com/nodejs/build/issues/3697#issuecomment-2177237274

metrics: skip empty lines in process cloudflare

---

ansible/roles/visual-studio/tasks/partials/vs2022.yml

This is a part of an effort to enable compilation with Clang on Windows. This commit allows for building with ClangCL in the CI.
This change is already applied to all VS2022 machines in the test and release CI. Note, that changing params for the win_chocolatey doesn't trigger installing a new component, so I installed these components manually on the existing machines.
Since the installation was done manually, the component I added in this PR was missing in Ansible. but was installed on the CI machines (previously I installed 2 components and only added 1 in Ansible).
Refs: https://github.com/nodejs/build/pull/3714
Refs: https://github.com/nodejs/build/issues/3709

ansible: add ClangCL to VS2022 fix

---

ansible/roles/metrics/files/process-cloudflare/package.json
ansible/roles/metrics/files/summaries/package.json
ansible/roles/metrics/files/summaries/summaries.js

Fixes: https://github.com/nodejs/build/issues/3782
Verified that `moment` and `Date` return same output if you're in GMT.
```js
import moment from 'moment' // v2.30.1
const today = new Date()
const momentDate = moment(today)
console.log(`date from moment: ${moment(momentDate, 'YYYYMMDD').subtract(1, 'days').format('YYYYMMDD')}`)
const yesterday = new Date().getTime() - (24 * 60 * 60 * 1000)
console.log(`date from Date: ${new Date(yesterday).toISOString().slice(0, 10).replace(/-/g, '')}`)
```
```console
date from moment: 20240624
date from Date: 20240624
```
The only difference I noticed is Node.js returns the Date in GMT, and moment returns the date in locale string.
It shouldn't be an issue, since the script is run at 12 PM GMT or 6 AM Central.

metrics: replace moment with JavaScript Date API

---

ansible/roles/metrics/files/process-cloudflare/process-cloudflare.js

Similar to https://github.com/nodejs/build/pull/3794
Docs: https://googleapis.dev/nodejs/storage/5.20.5/File.html#download-examples
```js
//-
// If the callback is omitted, we'll return a Promise.
//-
file.download().then(function(data) {
const contents = data[0];
});
```
Docs: https://googleapis.dev/nodejs/storage/5.20.5/File.html#save-examples
```js
//-
// If the callback is omitted, we'll return a Promise.
//-
file.save(contents).then(function() {});
```

metrics: convert processLogs callback into async-await

---

ansible/www-standalone/tools/promote/_resha.sh
ansible/www-standalone/tools/promote/settings
ansible/www-standalone/tools/promote/upload_to_cloudflare.sh

Note: nodejs/node#51394 should land before this does
Reference #3602
cc @targos @MoLow @ovflowd

ansible: promote release assets from staging r2 bucket

---

ansible/roles/jenkins-workspace/tasks/main.yml

The old NodeSource repository stopped updating and the version of Node.js installed from there is old (20.5.1). Update to use the new repository, which will install Node.js 20.15.0 at the time of this change.
Refs: https://github.com/nodesource/distributions/issues/1715
---
I spotted this while working on https://github.com/nodejs/build/pull/3803 (and made a similar update there for the github-bot role).
I've not deployed this yet -- we're planning on [replacing the Equinix machines](https://github.com/nodejs/build/issues/3597) which includes two of the three [`jenkins-workspace`](https://ci.nodejs.org/label/jenkins-workspace/) machines. (I can see there are entries in Jenkins for the replacements, but I don't know the IP addresses so can't Ansible them.)

ansible: update NodeSource repository setup

---

ansible/roles/metrics/files/index-generator/package.json
ansible/roles/metrics/files/process-cloudflare/package.json
ansible/roles/metrics/files/summaries/package.json

Verified that we don't use any APIs which are broken
---
Breaking changes:
* 6.x https://github.com/googleapis/nodejs-storage/blob/main/CHANGELOG.md#600-2022-05-24
* 7.x https://github.com/googleapis/nodejs-storage/blob/main/CHANGELOG.md#700-2023-08-03

metrics: bump @google-cloud/storage to 7.x

---

ansible/roles/metrics/files/summaries/summaries.js

Fixes: https://github.com/nodejs/build/issues/3808
---
To avoid any further bugs due to absence of unit tests, I deployed and verified that this fix works
```console
$ curl -X POST "https://produce-summaries-kdtacnjogq-uc.a.run.app/date/20240405" -H "Authorization: Bearer $(gcloud auth print-identity-token)"
```
The summary is created at https://storage.googleapis.com/access-logs-summaries-nodejs/nodejs.org-access.log.20240405.json

metrics: return failure for date route if it's not 8 digits

---

ansible/playbooks/jenkins/worker/create.yml

The `ansible/playbooks/jenkins/worker/create.yml` playbook runs some tasks at the end to remove Node.js and check there is no runnable `node` in the path. This is done on all `test` and `release` machines with the exception of the `jenkins-workspace` machines, which need a runnable `node` to run the linters.
Previously each `jenkins-workspace` machine was listed as an exclusion to `hosts`. This PR moves the exclusion into the tasks and checks if the host has an alias that begins `jenkins-workspace` (as all of our `jenkins-workspace` machines are defined). This will avoid one place that we have to remember to manually update every time we add/remove a `jenkins-workspace` machine.

ansible: dynamically exclude `jenkins-workspace`

---

backup/README.md
backup/backup_scripts/dist.sh
backup/rsnapshot.conf

The new backup server is a ubuntu2204 server, and the old server was a smartos15 server.
This updates the scripts to use the proper paths.
Additionally the new server's data is mounted on /data so the root folder has changed.

Updates backup scripts

---

ansible/roles/metrics/files/summaries/summaries.js

The download stats stopped getting populated in https://github.com/nodejs/build/issues/3697, likely as producing summaries took more than 1000 seconds. It likely happened as downloading and processing files took time.
This PR downloads files in batches of 50 each.
Tests show that time taken for producing summaries reduced from ~6 mins to ~26 seconds for `20240706` with negligible impact of CPU and memory consumption
---
From logs
```console
2024-07-07 04:00:03.059 PDT 20240706/
2024-07-07 04:06:19.196 PDT Upload complete: nodejs.org-access.log.20240706.json
```
Output: 
[nodejs.org-access.log.20240706.before.json](https://github.com/user-attachments/files/16121320/nodejs.org-access.log.20240706.before.json)
<details>
<summary>CPU usage: ~20%, memory usage: ~24%</summary>
</details>
From …

metrics: download processed-logs in batches of 50 each

---

ansible/plugins/library/remmina_config.py
ansible/plugins/library/ssh_config.py

- Use `/usr/bin/python` in the shebang to allow `ansible_python_interpreter` to work.
- Compare the template section before and after the change to avoid unnecessary
changes and to have a correct report in the playbook output.
Closes: https://github.com/nodejs/build/issues/3821

ansible: fix write-ssh-config modules

---

ansible/inventory.yml

Fedora 38 is EoL.
Closes: https://github.com/nodejs/build/issues/3820

ansible: rebuild fedora38-x64-2 host with Fedora 39

---

ansible/inventory.yml

Fedora 37 is EoL.
https://ci.nodejs.org/computer/test%2Ddigitalocean%2Dfedora40%2Dx64%2D1/

ansible: rebuild fedora37-x64-1 with Fedora 40

---

ansible/www-standalone/tools/promote/_resha.sh

The extra output from the `aws` commands is causing issues with the `release.sh` script from nodejs/node (which expects the only output to be the path to the `SHASUMS256.txt` file).
---
This is just a mirror of the current `_resha.sh` that is on the server after @targos @RafaelGSS and I live debugged this while trying to release Node.js 22.5.0.
The current [`tools/release.sh`](https://github.com/nodejs/node/blob/589b67aa1748974b24df4b4b7281e0cce4e915c7/tools/release.sh#L110-L120) is capturing the output of the sign command (`dist-sign`->`resha_release.sh`->`_resha.sh`) and was getting confused by the extra output from the `aws` commands.
Redirecting to `/dev/null` is going to make debugging issues with the r2 upload tricky, but for now this PR is keeping the repository in sync with what …

ansible: mirror _resha.sh changes

---

ansible/inventory.yml
ansible/roles/bootstrap/files/fedora40-resolv.conf
ansible/roles/bootstrap/tasks/main.yml
ansible/roles/bootstrap/tasks/partials/digitalocean/fedora40.yml

Replace test-digitalocean-fedora38-x64-1 with Fedora 40.
Update the Ansible scripts to fix the DNS settings on DigitalOcean-hosted Fedora 40 machines.
Refs: https://github.com/nodejs/build/issues/3350
Refs: https://github.com/nodejs/build/pull/3829#issuecomment-2227283376

ansible: replace test-digitalocean-fedora38-x64-1

---

ansible/inventory.yml

New backup server is established and running. This removes the old one.

ansible: remove equinix backup server

---

jenkins/scripts/windows/compile.cmd

This reverts commit 5d0639bd66ddf6e08c0ac08d68a5e4d7cffcee3e.
The change being reverted broke test jobs on Windows in the test CI.
This breaks all PR CI runs, so the first one to approve it from @nodejs/build should land it as well. As for the fix I'm reverting, I'll go back to the implementation to find the error and open a new PR once it's fixed.
Fixes: https://github.com/nodejs/build/issues/3848

Revert "jenkins: improve x64 node.exe caching for arm64 (#3842)"

---

jenkins/scripts/VersionSelectorScript.groovy

`gcc-12` is not available for this version.

jenkins: skip debian11 for Node.js >=23

---

jenkins/scripts/select-compiler.sh

Refs: https://github.com/nodejs/build/pull/3773

jenkins: select gcc12 on AIX for Node.js >=23

---

.github/workflows/orka-templates.yml
.gitignore
orka/templates/README.md
orka/templates/macos-11-arm-test.pkr.hcl
orka/templates/macos-11-intel-test.pkr.hcl

The main goal is to add support for Packer in Orka and validate the templates in future PRs. 
**Details**
- Add git rules to ignore `.env` files in `orka/` folder and subfolders
- Add the first Packer template to validate the workfow
- Add a GH pipeline to validate any change done in the templates (exclusively)
- Add basic documentation for using Packer with Orka
The template is working good enough for what is expected in this PR (communication, creation and CI validation)
This PR is part of the Orka plan described in https://github.com/nodejs/build/issues/3686#issuecomment-2278119351
The CI passed including the new pipeline [execution details](https://github.com/nodejs/build/actions/runs/10547529762/job/29220336802?pr=3872)
The CI won't handle the image publication, just the validation …

Add initial support for Packer in Orka

---

.github/workflows/orka-templates.yml
orka/templates/README.md
orka/templates/macos-13-arm-test.pkr.hcl
orka/templates/macos-13-intel-test.pkr.hcl
orka/templates/plugins.pkr.hcl
orka/templates/variables.pkr.hcl

- Updated documentation with the new environmental variables
- Added Packer template for Orka MacOS 13 ARM test
- Added Packer template for Orka MacOS 13 Intel test
- Updated CI to use all the expected environmental variables
- Related: https://github.com/nodejs/build/issues/3686
Currently the images do the following:
- Change the password of the default user
- Add SSH key access
- Disable SSH password authentication.
- Install Homebrew.
- Check Homebrew (Ignore errors because we are not using the last version of Xcode).
- Install dependencies using Homebrew. (git, automake, bash, libtool, cmake, python, and ccache)
**Dependencies installed**
- `autoconf 2.72`
- `automake 1.17`
- `bash 5.2.32`
- `blake3 1.5.4`
- `ca-certificates 2024-07-02`
- `ccache 4.10.2_1`
- `cmake 3.30.3`
- `fmt …

Add Packer support for MacOS 13 test images in Orka

---

ansible/inventory.yml
ansible/roles/bootstrap/tasks/partials/ubuntu2204.yml

Builds on 
- [test-digitalocean-ubuntu2204-x64-1](https://ci.nodejs.org/computer/test-digitalocean-ubuntu2204-x64-1/)
- [test-digitalocean-ubuntu2204-x64-2](https://ci.nodejs.org/computer/test-digitalocean-ubuntu2204-x64-2/)
have been failing, with the Jenkins agent being killed by the OOM killer. These machines have 4 GB RAM. Builds on the IBM hosted Ubuntu 22.04 x64 machines have been succeeding -- those also have 4 GB RAM but IBM provision those with 2 GB of swap. The DigitalOcean hosted machines have no swap -- this PR adds 2 GB of swap to bring them in line with the IBM hosted machines.

ansible: add swap to DigitalOcean Ubuntu 22.04

---

ansible/roles/docker/files/cc-selector.sh
ansible/roles/docker/templates/rhel9_arm_cross.Dockerfile.j2
jenkins/scripts/VersionSelectorScript.groovy

Refs: https://github.com/rvagg/rpi-newer-crosstools/pull/3
--- 
Ansible:

ansible: add rhel9_arm_cross containers

---

.github/workflows/orka-templates.yml
orka/templates/README.md
orka/templates/macos-13-arm-release.pkr.hcl
orka/templates/macos-13-intel-release.pkr.hcl

- Added new Orka templated for release images. They are very similar to the tests machines (see: https://github.com/nodejs/build/pull/3882)
- New environmental variables added (included ci and documentation)
- CI is now selective on what variables are passed based on the image name, to avoid validation errors.
- Related to https://github.com/nodejs/build/issues/3686#issuecomment-2278119351 and https://github.com/nodejs/build/pull/3891.
- Continuation of https://github.com/nodejs/build/pull/3882

Add Packer support for MacOS 13 release images in Orka

---

orka/templates/README.md

Related https://github.com/nodejs/build/issues/3686#issuecomment-2278119351

docs: add documentation for release images in Orka

---

orka/templates/macos-13-arm-release.pkr.hcl
orka/templates/macos-13-arm-test.pkr.hcl
orka/templates/macos-13-intel-release.pkr.hcl
orka/templates/macos-13-intel-test.pkr.hcl

This PR solves:
```
20:16:31 stderr: No ED25519 host key is known for github.com and you have requested strict checking.
20:16:31 Host key verification failed.
20:16:31 fatal: Could not read from remote repository.
```
Related to https://github.com/nodejs/build/issues/3686

Add GitHub host key to known hosts

---

ansible/roles/docker/templates/ubuntu2204_sharedlibs.Dockerfile.j2

Upstream OpenSSL releases are now hosted on GitHub. Update Dockerfile for the `ubuntu2204_sharedlibs` container to point to the new URLs and bump to the most recent available OpenSSL releases.
Refs: https://groups.google.com/a/openssl.org/g/openssl-announce/c/XyRfgxSWviM
---
Deployment:

ansible: update OpenSSL in sharedlibs containers

---

ansible/inventory.yml

Refs: https://github.com/nodejs/build/issues/2625
--- 
New servers are:
- [test-rackspace-debian12-x64-1](https://ci.nodejs.org/computer/test-rackspace-debian12-x64-1/)
- [test-rackspace-ubuntu2204-x64-1](https://ci.nodejs.org/computer/test-rackspace-ubuntu2204-x64-1/)
I had to replace 119.9.51.176 completely with a new server as it had a bad (maybe previous?) ssh key configured that I couldn't work out how to change in the Rackspace UI which meant that when it was reimaged I was not able to log into it.

ansible: replace Rackspace ubuntu1604-x64 machines

---

ansible/inventory.yml

Repurpose test-ibm-ubuntu2204-x64-2 as [test-ibm-rhel9-x64-2](https://ci.nodejs.org/computer/test-ibm-rhel9-x64-2/) to rebalance the number of machines per Linux distribution.

ansible: repurpose test-ibm-ubuntu2204-x64-2

---

orka/templates/macos-13-arm-release.pkr.hcl
orka/templates/macos-13-arm-test.pkr.hcl
orka/templates/macos-13-intel-release.pkr.hcl
orka/templates/macos-13-intel-test.pkr.hcl

- Ensure Homebrew environment is set up in the shell profile (01f78be)
- Add xz as dependency (8628fe3)
- Add xcode version information (26f4f34)
- Add tap2junit as dependency (a976199)
Related https://github.com/nodejs/build/issues/3686

Orka template updates

---

jenkins/scripts/VersionSelectorScript.groovy
jenkins/scripts/windows/compile.cmd

Since https://github.com/nodejs/node/pull/55249 landed, the main branch of the `node` repo supports compilation with ClangCL with PCH. MSVC and ClangCL compilation times are similar now, so we can start compiling (in some time testing, and eventually releasing) with ClangCL.
This PR adds support for compiling with ClangCL from v23. It also stops compiling v20 with VS2022 since it was temporary (we just never removed it before).
The labels we currently use in CI for VS2022 compilation are `win-vs2022` and `win-vs2022-arm64`. The format will stay the same, only `vs2022` will be replaced by `vs2022_clang`. The way I see it, this is the most consistent way of labeling it compared to what we already have in the CI, but if someone thinks differently we can discuss it.
I already added those …

build,win: compile with clang

---

doc/meetings/build-wg-meeting-2024-10-30.md

closes https://github.com/nodejs/build/issues/3942

Meeting notes 2024-10-30

---

ansible/www-standalone/tools/promote/upload_to_cloudflare.sh

Some non-mainline releases' src dirs differ from their dst dirs (i.e. v8-canary builds upload to `/home/staging/nodejs/custom` and then are promoted to `/home/dist/nodejs/v8-canary`. This wasn't being accounted for when we promoted files from the `dist-staging` bucket to the
`dist-prod` bucket.

ansible: don't assume the relative paths for staging & dist are the same

---

ansible/inventory.yml

Refs: https://github.com/nodejs/build/issues/3593

ansible: add test-digitalocean-freebsd13-x64-2

---

ansible/www-standalone/tools/promote/_resha.sh
ansible/www-standalone/tools/promote/settings
ansible/www-standalone/tools/promote/upload_to_cloudflare.sh

Open to suggestion for where the logs should go, this currently writes them to `/home/dist/nodejs/rclone` which requires the creation of that folder

ansible: use --log-file option for rclone

---

ansible/www-standalone/tools/promote/_resha.sh

Shasums for v8-canary builds were being uploaded to `nodejs/v8-canary/...` path in the `dist-staging` bucket instead of the `nodejs/custom/...` path. This makes them now be uploaded to the `nodejs/custom/...` path.

ansible: fix v8-canary SHASUMS256.txt

---

ansible/roles/bootstrap/files/gai.conf
ansible/roles/bootstrap/tasks/partials/linuxonecc/rhel9.yml
ansible/roles/bootstrap/tasks/partials/rhel8-s390x.yml

On some hosts, IPv6 connectivity is limited and may result in DNS lookups returning IPv6 addresses that the host is unable to reach. Add a config file for glibc's getaddrinfo function that configures IPv4 addresses to have higher precedence for such hosts.
Fixes: https://github.com/nodejs/build/issues/3950
---
Deploy status

ansible: add getaddrinfo config to prefer IPv4

---

GOVERNANCE.md

To avoid XY-style attacks, build-wg members should be highly trusted. Therefore, if they are not already Node.js collaborators, they should be approved by the TSC.

Add requirement that non-collaborator members be approved by the TSC

---

ansible/inventory.yml
ansible/roles/bootstrap/tasks/partials/fedora.yml

Note that I had to manually install an Ansible dependency before running the playbook because of https://github.com/ansible/ansible/issues/84206:
```
dnf install python3-libdnf5
```

ansible: add test-digitalocean-fedora41-x64-[12]

---

ansible/www-standalone/tasks/base.yaml

Update the version of Node.js used on the www server from Node.js 16 (16.20.2) to Node.js 22 (22.11.0).
Refs: https://github.com/nodejs/build/issues/3958#issuecomment-2493955665

ansible: update www Node.js version

---

ansible/inventory.yml
ansible/roles/baselayout/tasks/partials/repo/ibmi74.yml
ansible/roles/bootstrap/files/ibmi-git.sh
ansible/roles/bootstrap/tasks/partials/ibmi74.yml
ansible/roles/java-base/vars/main.yml
ansible/roles/jenkins-worker/vars/main.yml
jenkins/scripts/select-compiler.sh

Also update the IBM i 7.3 iinthecloud machines to IBM i 7.4.

ansible: Migrate IBM i to Java 17

---

ansible/inventory.yml
ansible/roles/baselayout/tasks/main.yml
ansible/roles/baselayout/vars/main.yml
ansible/roles/docker/vars/main.yml
ansible/roles/java-base/vars/main.yml
jenkins/scripts/VersionSelectorScript.groovy

Refs: https://github.com/nodejs/build/issues/3916
Depends on https://github.com/nodejs/build/pull/3981
After this is approved, I will:
- Remove the machines from Jenkins
- Remove the machines from the secrets repo
- Delete the VMs

ansible,jenkins: remove Debian 10 test hosts

---

ansible/inventory.yml
ansible/roles/baselayout/vars/main.yml
ansible/roles/java-base/vars/main.yml
ansible/roles/jenkins-worker/vars/main.yml

This may not work fully with our ssh configure script.
The smartos instances are vm's inside of a host hypervisor, as such we have to ssh proxy to get all the way into a shell.
There may also be strange ansible issues as a result of the hosts sharing, essentially, the same host IP address. I noticed that the jenkins secret from one host kept ending up on a different host, so Im not sure if ansible has something cached that uses the host IP as a key internally somewhere. 
If that becomes problematic we can adjust the internal IP's of the instances in the future to not conflict with each other.

ansible: add smartos test hosts and allow for smartos22

---

doc/release-overview.md

Website is now hosted on Vercel.
Add R2 object storage for staging/hosting of downloads. 
Remove unofficial-builds to simplify the overview (it still exists).
---
cc @nodejs/build-infra 
FYI @nodejs/releasers @nodejs/web-infra 
Direct link to view rendered page: https://github.com/richardlau/build/blob/release-overview/doc/release-overview.md

doc: update release overview

---

ansible/inventory.yml

Cleans up the old smartos nodes from ansible.

ansible: remove smartos18 and smartos20 release and test machines

---

ansible/roles/benchmarking/tasks/main.yml

The HEAnet mirror is no more. Change the repository URL for the R packages to Hetzner's mirror (Hetzner being the provider of our current `benchmark` machines).
---
This addresses this error from Ansible:
```console
TASK [package-upgrade : upgrade installed packages] *************************************************************************************************************************************************************
fatal: [test-hetzner-ubuntu2204-x64-1]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"}, "changed": false, "msg": "Failed to update apt cache: W:Updating from such a repository can't be done securely, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., E:The …
```

ansible: update CRAN repository URL

---

ansible/inventory.yml

Replace 
- test-osuosl-rhel9-ppc64_le-1
- test-osuosl-rhel9-ppc64_le-2
- test-osuosl-rhel9-ppc64_le-3
Add test-osuosl-rhel9-ppc64_le-4.
Fixes: https://github.com/nodejs/build/issues/3998

ansible: add new/replacement rhel9-ppc64le VMs

---

ansible/roles/visual-studio/files/ccache.conf
ansible/roles/visual-studio/tasks/main.yml

This PR adds `ccache` needed for Windows machines for compilation. This is already set on test CI compilation machines. `ccache.conf` might get updated over time if we reconfigure it.

ansible,win: add ccache

---

ansible/roles/docker/templates/alpine320.Dockerfile.j2
ansible/roles/docker/templates/alpine321.Dockerfile.j2
ansible/roles/docker/vars/main.yml

Closes: https://github.com/nodejs/build/issues/3988

ansible: add Alpine Linux 3.20 and 3.21

---

ansible/roles/docker/templates/ubuntu2204_sharedlibs.Dockerfile.j2
jenkins/scripts/VersionSelectorScript.groovy

Add OpenSSL 3.5.0-alpha1 to sharedlibs containers.
---
Adds new label [ubuntu2204_sharedlibs_openssl35_x64](https://ci.nodejs.org/label/ubuntu2204_sharedlibs_openssl35_x64/).
Deployment:

ansible: add openssl-3.5.0-alpha1 to containers

---

jenkins/scripts/node-test-commit-pre.sh

Add a check that the gitref being built has not been updated since the build was requested. Requires `COMMIT_SHA_CHECK` to be set to the SHA of the commit to build/test.

jenkins: add check for checked out commit

---

jenkins/scripts/node-test-commit-pre.sh

Only enforce the COMMIT_SHA_CHECK verification when:
- The org/repo is not nodejs/node (i.e. outside of our project).
- The org/repo is nodejs/node and the reference is for a pull request.
Refs: https://github.com/nodejs/build/pull/4046
---
This relaxes the check added in https://github.com/nodejs/build/pull/4046 to not apply for https://github.com/nodejs/node references that are not pull request references. This will reallow scheduled builds (e.g. daily test builds of `main` and the staging branches).
For pull request references, or requests to build references from other repositories, the check will still be enforced.

jenkins: relax check for trusted nodejs/node branches

---

ansible/roles/gn/tasks/main.yml
ansible/roles/gn/tasks/partials/rhel8-ppc64.yml
ansible/roles/gn/tasks/partials/rhel8-s390x.yml
ansible/roles/gn/tasks/partials/rhel8.yml
ansible/roles/gn/vars/main.yml

Install dependencies needed to build `gn` before attempting to build it.
Fixes: https://github.com/nodejs/build/issues/4059

ansible: fix build dependencies for `gn` role

---

.github/workflows/push.yml

We previously pinned this workflow to `ubuntu-20.04` to preserve Python 2.7 compatibility, but have since dropped Python 2.7 so can now unpin.
Refs: https://github.com/nodejs/build/pull/3086
Refs: https://github.com/nodejs/build/pull/3093
Refs: https://github.com/actions/runner-images/issues/11101
---
Spotted in https://github.com/nodejs/build/actions/runs/14339365721?pr=4064
> This is a scheduled Ubuntu 20.04 brownout. Ubuntu 20.04 LTS runner will be removed on 2025-04-15. For more details, see https://github.com/actions/runner-images/issues/11101
I had to bump Python up from 3.7 https://github.com/richardlau/build/pull/3#issuecomment-2787134456 (I initially accidentally opened this PR on my own fork instead of here).
According to https://devguide.python.org/versions/ Python 3.9 goes out …

chore: switch back to `ubuntu-latest`

---

ansible/roles/docker/templates/ubuntu2204_sharedlibs.Dockerfile.j2

Update the version of OpenSSL 3.5.0 in the sharedlibs containers from the OpenSSL 3.5.0-beta1 to the full release OpenSSL 3.5.0 version.
---
**Deployment**

ansible: update containers to OpenSSL 3.5.0 release

---

ansible/roles/gn/tasks/main.yml
ansible/roles/gn/vars/main.yml

Roll forward the version of `gn` used to build V8.
Clean git checkout before building.
Refs: https://github.com/nodejs/node/pull/57753#issuecomment-2789890327
---
**Deployment**

ansible: update `gn` on V8 build machines

---

jenkins/scripts/VersionSelectorScript.groovy

This change switches from MSVC to ClangCL for release builds from Node.js v24. It also stops MSVC compilation for v24+ in the test CI.
This PR is the last step needed to move to the ClangCL-produced binaries on Windows. Currently, we are compiling and testing ClangCL in the test CI alongside MSVC for v24, which creates a manageable bottleneck because of the doubled compilation and testing jobs run on each PR. With this change, we will stop MSVC compilation for v24+ in both test and release CI, meaning that ClangCL will become the only supported compiler for Node.js (I'll open a PR in node to document this).
I've tested the changes from this PR in 2 temporary jobs in [test CI](https://ci.nodejs.org/job/mefi-node-test-commit-windows-fanned/) and [release …

Moving to ClangCL on Windows for Node.js v24

---

ansible/inventory.yml
ansible/playbooks/create-rsync-unencrypted.yml
ansible/roles/nginx/templates/nodejs.org.conf.j2
ansible/roles/nginx/templates/unencrypted.conf.j2

This adds the new unencrypted host to the inventory.

Add unencrypted host, remove legacy equinix hosts

---

ansible/inventory.yml
ansible/roles/java-base/vars/main.yml

Refs: https://github.com/nodejs/build/issues/4109

build,test: add test-digitalocean-fedora42-x64-[12]

---

ansible/inventory.yml

Closes: https://github.com/nodejs/build/issues/4109

ansible: remove fedora40 hosts from inventory

---

ansible/inventory.yml
ansible/roles/baselayout/tasks/partials/ntp/systemd.yml
ansible/roles/docker/vars/main.yml
ansible/roles/github/tasks/main.yml

This adds the new azure nodes to the Inventory.
It also makes a couple of small ansible adjustments that make these work on Ubuntu24.04.

Add Azure nodes, fix ansible builds for Ubuntu24.04 hosts
