nodejs/build

- dist/dist-indexer/LICENSE
- dist/dist-indexer/README.md
- dist/dist-indexer/dist-indexer.js
- dist/dist-indexer/package.json
This thing will run each time there's a binary file update on the server
> Added dist-indexer application

- setup/www/README.md
- setup/www/host_vars/iojs-www.tmpl
- setup/www/resources/github-webhook.json
To happen in sync with a rename of the iojs/iojs.github.io project as per iojs/iojs.github.io#57
> Renames iojs/iojs.github.io -> iojs/website

- dist/update-download-stats.sh
parse last few log files each night and update /home/iojs/download-stats.json with new data
not the most elegant of scripts but it gets the job done (using 5 "programming" languages no less)
> program to calculate and update download stats

- doc/meetings/build-wg-meeting-2015-02-19.md
done in a bit of a rush, hopefully it's complete enough!
> add doc/meetings/build-wg-meeting-2015-02-19.md

- dist/dist-indexer/dist-indexer.js
V8 has changed where they are putting version macros, which is annoying but the new location make so much more sense. This change makes dist-indexer look in both locations.
> Dist indexer v8 update

- tools/dist/promote/README.md
- tools/dist/promote/_promote.sh
- tools/dist/promote/_resha.sh
- tools/dist/promote/promote_nightly.sh
- tools/dist/promote/promote_release.sh
- tools/dist/promote/resha_release.sh
- tools/dist/promote/settings
> added promotion scripts for web server

- tools/jenkins-status/jenkins-status.js
- tools/jenkins-status/package.json
this just digests the server status endpoint so I can quickly see what's not running properly
> added simple jenkins-status app

- setup/ansible-inventory
- setup/debian8/README.md
- setup/debian8/ansible-playbook.yaml
- setup/debian8/ansible-vars.yaml
- setup/debian8/host_vars/.gitignore
- setup/debian8/resources/jenkins.service
running on rackspace, systemd & ccache installed
> added debian 8 config

- setup/ansible-inventory
- setup/ubuntu14.04/ansible-vars.yaml
Add PPC LE machine to inventory
Not sure if I should be adding myself to setup/ubuntu14.04/ansible-vars.yaml but did want to be able to access the machines for debugging
> dist: add PPC LE machine

- setup/ubuntu15.04/ansible-vars.yaml
- setup/ubuntu15.04/resources/start.sh
This will be refactored soon but might as well add it for consistency.
> dist: use ccache for ubuntu15.04 slaves

- setup/www/resources/config/nodejs.org
See https://github.com/nodejs/new.nodejs.org/pull/227
> Update redirects for legacy images

- setup/www/tools/nightly-builder/build-required.js
- setup/www/tools/nightly-builder/latest-build.js
- setup/www/tools/nightly-builder/latest-commit.js
- setup/www/tools/nightly-builder/nightly-builder.js
- setup/www/tools/nightly-builder/test.js
- setup/www/tools/nightly-builder/trigger-build.js
> remove hard-coded git refs for nightly types, use cmdline

- README.md
> Update chat info

- backup/README.md
- backup/backup_scripts/benchmark_mysql.sh
- backup/backup_scripts/dist.sh
- backup/backup_scripts/iptables.sh
- backup/backup_scripts/remove_old.sh
- backup/rsnapshot.conf
Refs: https://github.com/nodejs/build/issues/308
> backup: add scripts, general info & configuration

- setup/www/resources/config/github-webhook.json
- setup/www/resources/config/libuv.org
- setup/www/resources/config/nodejs.org
- setup/www/resources/secrets/makesecrets.sh
- setup/www/tasks/site-setup.yaml
a few things I found after I accidentally ran this against the live site ...
> www fixups

- README.md
> Add Imran to our team

- setup/www/tools/nightly-builder/build-required.js
- setup/www/tools/nightly-builder/latest-commit.js
- setup/www/tools/nightly-builder/nightly-builder.js
- setup/www/tools/nightly-builder/package.json
- setup/www/tools/nightly-builder/trigger-build.js
this is in action and churning out nightlies already
> nightly-builder support for auth on ci-release

- setup/ansible-inventory
- setup/ubuntu16.04/README.md
- setup/ubuntu16.04/ansible-playbook.yaml
Also, minor nits to the playbook to fix remote_user (lets look at handling non-root users later) as well as enabling ntp.
> ubuntu16.04: add new slave

- ONBOARDING.md
Just getting this up here to get more eyeballs. I'll expand on each section incrementally.
> Initial outline for onboarding

- README.md
- setup/www/tools/dist-indexer/transform-filename.js
Also, a-z usernames.
refs #489.
> doc: update members

- setup/www/tools/dist-indexer/transform-filename.js
/cc @mhdawson, @evanlucas, @rvagg
> dist-indexer: add aix-ppc64 support

- setup/README.md
- setup/TESTING_LOCALLY.md
As briefly mentioned in the last WG meeting, while working in the github-bot setup, I got a local Vagrant setup working for running playbooks against. I thought that was really valuable when trying to learn Ansible basics, and it made it trivial to start from scratch after having tested a lot of different approaches.
Any feedback would be more than welcome!
> Created a small working with Ansible guide

- setup/www/resources/config/logrotate-nginx
fixes https://github.com/nodejs/build/issues/550
> Fix nginx logrotate script for www

- README.md
Thanks everyone for the up-votes!
Refs: #649
> doc: add Kunal Pathak to members

- doc/meetings/build-wg-meeting-2017-03-28.md
Add minutes for https://github.com/nodejs/build/issues/660
> Add WG minutes for meeting 2017-03-28

- setup/ansible-inventory
- setup/www/resources/config/nodejs.org
@mikeal @williamkapke pls review, is this what we're after for calendar access?
> www: redirect for calendar

- setup/www/resources/config/nodejs.org
URL for the debugging guide changed to match the other guides.
> Rewrite guide

- doc/meetings/build-wg-meeting-2017-04-18.md
Fixes: https://github.com/nodejs/build/issues/683
> Add WG minutes for meeting 2017-04-18

- doc/templates/build-wg-meeting-0000-00-00.md
- doc/templates/wg-meeting-issue-template.md
First draft of templates for meetings, feedback on any part of it welcome. I didn't want to leave placeholder URLs so it was obvious which URLs needed to be added, but 🤷‍♂️ . We could also have more `<!--` style comments, but then we have to delete them which is annoying
Refs: https://github.com/nodejs/build/issues/689
> Add minutes and issue template for wg meetings

- doc/templates/build-wg-meeting-2017-06-20.md
Fixes: https://github.com/nodejs/build/issues/766
> doc: add meeting minutes for 2017-06-20

- setup/windows/vcbt2015-ansible-playbook.yaml
Ref: https://github.com/nodejs/build/pull/764
Sorry I just sew it now.
> ansible: shorten windows link to vcbt2015

- doc/meetings/build-wg-meeting-2017-08-22.md
Fixes: https://github.com/nodejs/build/issues/837
As always, if you have corrections just push them to the branch.
> doc: add meeting minutes for 2017-08-22

- setup/ansible-tasks/git.yaml
- setup/github-bot/ansible-playbook.yaml
- setup/github-bot/ansible-vars.yaml
This is for @fishrock123 who is trying to get a rebase task working and we're seeing if it's an older version of git that's the problem. May as well got for the latest version.
> install latest version of git

- README.md
Resort members, add George and Michele. Michele's PR never got raised,
George's got closed without being landed.
Fixes: https://github.com/nodejs/build/issues/711
Refs: https://github.com/nodejs/build/pull/860
> doc: update members list in README

- setup/www/resources/scripts/sync-benchmarking.sh
- setup/www/tasks/site-setup.yaml
Fixes: https://github.com/nodejs/build/issues/896
> use lock when rsyncing benchmarking data

- doc/meetings/build-wg-meeting-2017-10-12.md
Fixes: https://github.com/nodejs/build/issues/902
cc/ @mhdawson @refack @joaocgreis @gdams please review.
Also if someone who's actually at the meeting could raise minutes that'd be ideal.
> doc: add meeting minutes for 2017-10-12

- doc/meetings/build-wg-meeting-2017-10-25.md
Fixes: https://github.com/nodejs/build/issues/939
@ev1stensberg feel free to review!
> doc: add meeting minutes for 2017-10-25

- .gitignore
- ansible/.gitignore
Also removes unneeded `**/` (ignore paths check subdirectories unless
they start with `/`).
> git: add package-lock.json to .gitignore

- doc/fixing-machines.md
Would be great to get some of these Tips & Tricks written down.
Refs: https://github.com/nodejs/build/issues/775#issuecomment-336473604
Reviews would be really helpful, I'm making half of this up as I go along...
> doc: add basic troubleshooting guide for machines

- jenkins/xml/citgm-smoker.xml
1. snapshot of citgm-smoker.xml
2. citgm-smoker explicit npm_cache
> CI: export citgm-smoker.xml

- setup/www/resources/config/nodejs.org
- Added Foundation redirects for `es` and `uk` localizations
- Added case studies and board meeting minutes
Ref: https://github.com/nodejs/nodejs.org/pull/1485
> Redirect intl Foundation links, case studies and board minutes

- README.md
I think it makes sense since I have access to the bot's secrets.
> doc: add joyeecheung to the github bot admins

- ansible/roles/docker/templates/alpine37.Dockerfile.j2
active in CI now, first run on master passed just fine, they'll run slow for a few days as the ccache across the 4 docker hosts warms up
> add alpine 3.7

- doc/meetings/build-wg-meeting-2017-12-05.md
This is the first meeting to use the new auto-generated template, so we
should see what needs adding.
Fixes: https://github.com/nodejs/build/issues/1028
> doc: add minutes for 2017-12-05

- doc/access.md
I'll add these as I get them :) .
@rvagg I got the invites for Packet and DigitalOcean, should I be expecting others, or are the other ones shared passwords?
> doc: note other accesses for nodejs_build_infra

- ONBOARDING.md
- README.md
- doc/meetings/build-wg-meeting-2015-11-10.md
- doc/meetings/build-wg-meeting-2017-03-28.md
- doc/meetings/build-wg-meeting-2017-06-20.md
- doc/meetings/build-wg-meeting-2017-08-22.md
- doc/meetings/build-wg-meeting-2017-10-12.md
- doc/meetings/build-wg-meeting-2017-10-25.md
- doc/process/joining_the_build_wg.md
- jenkins/pipelines/post-build-status-update.jenkinsfile
> Fix GitHub's capital "H", GitHub instead of Github

- doc/meetings/build-wg-meeting-2018-03-20.md
Fixes: https://github.com/nodejs/build/issues/1183
> doc: add minutes for meeting 2018-03-20

- ansible/roles/nginx/templates/nodejs.org.conf.j2
Ref: https://github.com/nodejs/nodejs.org/pull/1610
> nginx: Redirect old inspector docs

- setup/www/tasks/tools.yaml
The "nightlies" were triggered at 1,2,3 __PM__ EST (10,11AM 12PM PST).
I suggest:
* moving them to 07:00UTC = 00:00PST = 03:00EST
* Spacing them 2 hour apart
> cron: reschedule nightlies

- ansible/roles/docker/tasks/main.yml
- ansible/roles/docker/templates/alpine36.Dockerfile.j2
- ansible/roles/docker/templates/alpine37.Dockerfile.j2
- ansible/roles/docker/templates/jenkins.service.j2
Fixes: https://github.com/nodejs/build/issues/1186
Rolling this out now across the cluster...
cc @santigimeno @bnoordhuis @cjihrig
> docker: add libtool and automake to alpine

- doc/jenkins-guide.md
I am VERY happy to get all of this out of my head! Bash commands galore
with information on how to debug and manage our Jenkins clusters.
> doc: add jenkins guide

- README.md
fix the link in the README for joining the group
> Davidwkaiser patch 3

- doc/ssh.md
@maclover7 only now I was able to review the docs you added. Thanks for taking the trouble to add them! This is only a couple of nits in the SSH access doc.
> doc: SSH access minor fixes

- doc/ansible-testing.md
As discussed in today's special Build WG meeting.
>  doc: update ansible_testing guide

- doc/meetings/project-meeting-2018-06-19.md
Fixes: https://github.com/nodejs/build/issues/1330
Copy pasted from https://docs.google.com/document/d/12ZyOGLl0xmqRBin71SVGJHAohgOMKMFHyxyISFKFshE/edit?usp=sharing
> doc: add meeting docs for special project meeting

- README.md
Closes: https://github.com/nodejs/build/issues/1308
> doc: add Matheus Marchini to members

- ansible/roles/java-base/tasks/main.yml
- ansible/roles/jenkins-worker/templates/upstart.j2
This fixes one of the issues that @maclover7 mentioned on the build WG call.
> switch ppcle to use newer java8 version

- ONBOARDING.md
Adds more concrete steps to the onboarding guide for the WG. This is
updated with the information I used to onboard @mmarchini.
> doc: update ONBOARDING.md

- jenkins/scripts/VersionSelectorScript.groovy
Fixes: https://github.com/nodejs/build/issues/1290
> jenkins: no debian8-x86 for node 10

- ansible/inventory.yml
- ansible/roles/baselayout/vars/main.yml
- doc/non-ansible-configuration-notes.md
Add doc regarding libsmartsshd.so removal and need to add authorized_keys entry
Ref https://github.com/nodejs/build/issues/1439
> ansible: new test-joyent-smartos17-x64-1 ip address

- jenkins/scripts/VersionSelectorScript.groovy
Refs: https://github.com/nodejs/build/issues/885
Refs: https://github.com/nodejs/build/issues/1499
> ci: no ubuntu1?04-32 since node 10

- setup/aix61/manualBootstrap.md
Add step for installing newer compiler on AIX
> doc: add step for adding newer compiler

- ansible/inventory.yml
> added infra-digitalocean-ubuntu1804-x64-1 gzemnid

- doc/jenkins-guide.md
System diff: https://ci.nodejs.org/jobConfigHistory/showDiffFiles?name=config&timestamp1=2018-11-25_16-21-47&timestamp2=2018-11-26_10-28-03
CSS Diff: https://ci.nodejs.org/jobConfigHistory/showDiffFiles?name=org.codefirst.SimpleThemeDecorator&timestamp1=2018-09-08_19-18-43&timestamp2=2018-11-26_10-44-31
H/T: @joyeecheung
> doc: add system message on lock-down

- setup/www/resources/config/nodejs.org
Fixes: https://github.com/nodejs/nodejs.org/issues/1952
> nginx: Update locale list for language fallback

- README.md
often, I work to debug test failures in CI. And in many cases the issues are reproducible only in CI systems in which case I would request for temporary access.
Having part of the team will help
- not waiting for long time before access is granted
- stabilizing CI on a timely basis.
Thanks in advance.
> doc: add gireeshpunathil to members

- ansible/inventory.yml
- setup/aix61/manualBootstrap.md
> update manualBootstrap.md for AIX

- ansible/roles/baselayout/tasks/main.yml
- ansible/roles/baselayout/vars/main.yml
- ansible/roles/java-base/tasks/main.yml
- ansible/roles/jenkins-worker/tasks/main.yml
- ansible/roles/jenkins-worker/tasks/partials/tap2junit/aix.yml
- ansible/roles/jenkins-worker/templates/aix.rc2.j2
- ansible/roles/jenkins-worker/vars/main.yml
- ansible/roles/package-upgrade/vars/main.yml
> initial ansible support for aix71

- jenkins/scripts/VersionSelectorScript.groovy
Refs: https://github.com/nodejs/build/issues/1583
> ci: Skip centOS6 for node >= 12

- ansible/roles/docker/templates/ubuntu1604_sharedlibs.Dockerfile.j2
Refs: https://github.com/nodejs/node/pull/26209#issuecomment-472047076
cc @sam-github
> docker: upgrade to openssl-1.1.1b for sharedlibs

- ansible/inventory.yml
See: https://github.com/nodejs/build/pull/1723#issuecomment-475717268
> ansible: add ubuntu1404-ppc64_le-4 to inventory

- ansible/inventory.yml
See: https://github.com/nodejs/build/pull/1739#issuecomment-482115248
> ansible: remove non-existent ubuntu1404-ppc64_le-3

- ansible/roles/jenkins-worker/tasks/main.yml
Pre-req for https://github.com/nodejs/build/pull/1754, which updates select-compiler.sh to use these tools.
> install devtools-6 on rhel-s390x

- README.md
> doc: add sam-github to members

- ansible/inventory.yml
Fixes: https://github.com/nodejs/build/issues/1810
> ansible: remove macOS10.08 & .09 workers

- setup/www/tools/metrics/plot.gp
From https://github.com/nodejs/build/issues/1814
Makes a couple improvements:
- More colors
- Repeating dark grey for low-value lines
- Moves the legend to the left
- Couple more countries
> metrics improvements

- ansible/roles/jenkins-worker/templates/jenkins_manifest.xml.j2
- ansible/roles/jenkins-worker/vars/main.yml
> ansible: partial revert of d2d58ca2, reduce JOBS for smartos to 2

- setup/aix61/manualBootstrap.md
See: https://github.com/nodejs/build/issues/1798#issuecomment-503274689
> doc: update aix ramdisk manual setup

- doc/jenkins-guide.md
see https://github.com/nodejs/build/issues/1798#issuecomment-504577167
> Add note about not restarting AIX machines

- ansible/roles/jenkins-worker/tasks/main.yml
So `libuv` multicast join tests pass.
Refs: https://github.com/libuv/libuv/pull/2185
> fedora27-x64: allow multicast with firewalld

- README.md
> doc: add bnoordhuis to members

- ansible/inventory.yml
- ansible/roles/jenkins-worker/tasks/main.yml
do not merge yet, original machine still not taken offline or out of CI, need to sort out the Wheezy issue #1867
(also has a dangling commit for fedora that I need to sort out still, will clean this up before merge)
>  ansible: reprovisioned armv7 scaleway machine 

- setup/aix61/manualBootstrap.md
https://github.com/nodejs/tap2junit
https://pypi.org/project/tap2junit
Also add instructions for __pip2 install tap2junit__ and __pip3 install tap2junit__
> Document the new repo for tap2junit

- .github/workflows/push.yml
tap2junit can be added once https://github.com/nodejs/admin/issues/413 is resolved.
> GitHub Actions: Comment out requirements.txt for now

- jenkins/scripts/coverage/generate-index-html.py
Fixes; https://github.com/nodejs/build/issues/1932
Refs: https://github.com/nodejs/nodejs.org/pull/2544
> Update path to style sheet for coverage.nodejs.org

- setup/www/resources/config/nodejs.org
Redirect `/layouts/css/styles.css` to `/static/css/styles.css`
**This is untested!**
Fixes #1932 and similar issues.
/CC @rvagg @richardlau @addaleax
> Update nodejs.org config

- ansible/ansible.cfg
Ref: https://github.com/nodejs-private/secrets/pull/48
> ansible: add 'home=/User' var for macos

- ansible/roles/docker/templates/ubuntu1804_sharedlibs.Dockerfile.j2
Ref: https://github.com/nodejs/build/issues/1970
ooops
> ansible: fix ubuntu1804 docker image to _use_ 1804

- ansible/ansible.cfg
- ansible/inventory.yml
- ansible/roles/baselayout/vars/main.yml
- ansible/roles/bootstrap/tasks/partials/fedora.yml
> ansible: add fedora30, remove fedora26

- ansible/roles/jenkins-worker/tasks/main.yml
Finishes the job of https://github.com/nodejs/build/pull/1879
> ansible: remove firewalld entirely from ansible

- jenkins/scripts/select-compiler.sh
Fixes: https://github.com/nodejs/build/issues/1992
> jenkins: use /bin/sh syntax in select-compiler.sh

- ansible/www-standalone/tasks/base.yaml
- ansible/www-standalone/tasks/nginx.yaml
Ref: https://github.com/nodejs/build/issues/1993
live on primary server, secondary server hasn't been touched
> www: tune system for i/o perf

- ansible/inventory.yml
> ansible: test-joyent-ubuntu1804 move

- doc/non-ansible-configuration-notes.md
Move anchor links to the bottom as well
> fix: Remove CentOS 5 config notes

- ansible/roles/java-base/tasks/main.yml
> ansible: `=` -> `==` for os check

- README.md
People tend to [assume](https://github.com/nodejs/build/issues/2005#issuecomment-546570070) I'm already a member of this WG so let's make it official 😄.
For the record, I work for IBM and have been working on Node.js ever since we started porting to ppcbe Linux back in 2013. To set expectations, I have more experience in the Jenkins job configuration side of things compared to machine setup/maintenance.
> doc: add richardlau to members

- ansible/www-standalone/resources/config/nodejs.org
- ansible/www-standalone/tasks/base.yaml
Ref: https://github.com/nodejs/build/issues/1993
> www: more nginx tuning for static-file sending

- ansible/inventory.yml
Ref: https://github.com/nodejs/build/issues/2026
> ansible: reprovision two scaleway test machines

- ansible/inventory.yml
See: https://github.com/nodejs/build/pull/2014
> ansible: remove smartos test machines

- ansible/plugins/inventory/nodejs_yaml.py
Describe what it is that is being looked for (a git checkout of
nodejs-private/secrets), and the locations that are automatically
searched.
> ansible: make warnings about secrets informative

- ansible/aix61-standalone/manualBootstrap.md
Document changes made in https://github.com/nodejs/build/issues/1380#issuecomment-554452704
> ansible: edit aix manualBootstrap.md to contain SSH instructions

- ansible/inventory.yml
See: https://github.com/nodejs/build/pull/2012
> ansible: remove nonexistent freebsd machines

- README.md
> doc: add myself to release admins

- jenkins/scripts/VersionSelectorScript.groovy
Refs: https://github.com/nodejs/build/issues/2084#issuecomment-563378847
cc @joaocgreis
> jenkins: exclude testing on vs2019 on Node.js < 10

- README.md
> doc: add myself to build WG member list

- jenkins/scripts/VersionSelectorScript.groovy
Add the gt operator to VersionSelectionScript.
> jenkins: add gt operator to VersionSelectionScript

- jenkins/scripts/VersionSelectorScript.groovy
- 13.x: test and release only on AIX7.1
- 10.x and above: test on AIX7.1
> jenkins: 13.x release on aix7.1, all tests on 7.1

- jenkins/scripts/VersionSelectorScript.groovy
Also remove testing/releasing 12.x on AIX61
> jenkins: Allow releasing 12.x on AIX71

- OFFBOARDING.md
- ONBOARDING.md
Ive added an OFFBOARDING.md which contains a checklist for offboarding
members. Ive also updated ONBOARDING.md to have similar checklists for
adding members and also removed some duplicate information
Let me know if you have any suggestions/ if ive missed anything from the
checklists.
Ive tried to write the document in a style so that it can just be copied pasted into
an issue for the on/offboarding of the member
> doc: add OFFBOARDING.md and update ONBOARDING.md

- doc/node-test-commit-matrix.md
- jenkins/pipelines/llnode-pipeline.jenkinsfile
- jenkins/scripts/VersionSelectorScript.groovy
- jenkins/xml/citgm-smoker.xml
Only seems referenced by < Node 8
> chore: Remove ppcbe Ubuntu

- doc/jenkins-guide.md
I can never remember the exact CLI syntax, so it's nice to have precooked lines documented.
> refresh incantations

- GOVERNANCE.md
tiny pr, but looking at the calender i've gotten the timings for the working groups meetings wrong.
> doc: correct meeting timings on GOVERNANCE

- doc/jenkins-guide.md
Needs additional information, but as a start, note the Windows administrative maintenance jobs on CI.
> add minimal Windows troubleshooting

- README.md
Result of running `ncu-team sync README.md`.
> doc: sync teams from github to README

- ansible/www-standalone/resources/config/nodejs.org
Fixes: https://github.com/nodejs/build/issues/2194
would appreciate nginx config sanity checking before I try putting this on the server.
> www: redirects for renamed openjsf content

- .github/workflows/stale.yml
In #2196  I forgot to change the message, so I suggest removing the count of days.
> workflows: remove the incorrect day counts

- doc/jenkins-guide.md
Refs: https://github.com/nodejs/build/issues/2215#issuecomment-597332383
> doc: add how to restart Jenkins agent on AIX

- doc/jenkins-guide.md
Fixes: https://github.com/nodejs/build/issues/2230
> doc: add steps to fix read-only fs

- README.md
Fixes: https://github.com/nodejs/build/issues/2286
> Add @richardlau to release secrets and jenkins

- doc/meetings/build-wg-meeting-2020-04-14.md
Signed-off-by: Michael Dawson <michael_dawson@ca.ibm.com>
> doc: add minutes for meeting 14 April 2020

- ansible/roles/jenkins-worker/tasks/main.yml
I'm working on resurrecting https://github.com/nodejs/build/pull/1476 but as a GitHub Actions workflow. 
Current yamllint failures are mostly whitespace and I'll deal with those in a separate PR but this is the one non-whitespace issue found.
cc @AshCripps @sam-github
> ansible: avoid duplicate keys

- README.md
Closes: https://github.com/nodejs/build/issues/2301
> doc: add AshCripps to jenkins-release-admins

- ansible/roles/baselayout/vars/main.yml
- ansible/roles/jenkins-worker/tasks/main.yml
cmake is packaged, but its a 2.x version which can't build libuv, so
build from src.
> ansible: install cmake on rhel7 from src

- ansible/roles/baselayout/tasks/main.yml
- ansible/roles/baselayout/vars/main.yml
Fixes: https://github.com/nodejs/build/issues/2321 as well as installing cmake3
> ansible: install cmake3 on centos7_ppc64

- OFFBOARDING.md
- README.md
Refs: https://github.com/nodejs/build/issues/2339
> doc: move sam-github to emiriti

- README.md
manually sync with [the gpg list](https://github.com/nodejs-private/secrets/tree/master/build/release/.gpg)
> doc: add AshCripps to build-release README

- doc/meetings/build-wg-meeting-2020-07-07.md
Signed-off-by: Michael Dawson <michael_dawson@ca.ibm.com>
> doc: add minutes for meeting 7 July 2020

- ansible/MANUAL_STEPS.md
Add a set of instructions to validate the apple certs are still in date
> doc: document validating apple certificates

- doc/meetings/build-wg-meeting-2020-09-08.md
fixes: https://github.com/nodejs/build/issues/2427
> doc: add minutes for 2020-09-08 meeting

- README.md
refs: https://github.com/nodejs/build/issues/2390
> doc: update team members with ncu-team sync

- ansible/inventory.yml
- ansible/roles/baselayout/tasks/ccache.yml
- ansible/roles/baselayout/tasks/main.yml
- ansible/roles/bootstrap/tasks/partials/aix.yml
Our current AIX7.1 machines are on a service contract which expires at the end of the year. This PR will add 2 new test machines and a release machine to replace. im also going to try and add some ansible tweaks to remove some of the metric &%^*load of manual steps we have for AIX.
> ansible: Add new aix7.1 machines

- ansible/roles/jenkins-worker/templates/aix.rc2.j2
- ansible/roles/jenkins-worker/vars/main.yml
> ansible: set JOBS to 6 on AIX

- doc/meetings/build-wg-meeting-2020-12-01.md
> doc: add minutes for meeting 1 dec 2020

- ansible/inventory.yml
- ansible/roles/baselayout/tasks/ccache.yml
- ansible/roles/baselayout/vars/main.yml
- ansible/roles/bootstrap/tasks/partials/aix.yml
- ansible/roles/jenkins-worker/tasks/partials/tap2junit/aix.yml
- jenkins/scripts/VersionSelectorScript.groovy
Add three new AIX72 will now be used for building node in CI.
@nodejs/build-infra can I get `140.211.9.131` and `140.211.9.101` adding to the test CI firewall and `140.211.9.77` added to the release CI
> Add new AIX72 machines

- ansible/inventory.yml
- jenkins/scripts/VersionSelectorScript.groovy
Refs: https://github.com/nodejs/build/issues/2552
> ansible: remove smartos 15 and 16 from inventory

- .github/workflows/shellcheck.yml
Setup the CI to see if this makes sense to add here before trying to fix any of the things it's flagging.
> chore: Add Shellcheck CI action

- ansible/roles/baselayout/vars/main.yml
Refs: https://github.com/nodejs/build/issues/2507
> ansible: add Python 3 to LinuxONE hosts

- ansible/inventory.yml
- ansible/roles/jenkins-worker/vars/main.yml
More permanent fix of https://github.com/nodejs/build/issues/2566
> ansible: set machine specific JOBS on AIX

- doc/meetings/build-wg-meeting-2021-03-16.md
closes: https://github.com/nodejs/build/issues/2562
> doc: add minutes for 2021-03-16 meeting

- doc/meetings/build-wg-meeting-2021-01-12.md
> doc: add minutes for meeting 13 Jan 2021

- ansible/roles/metrics/files/process-cloudflare/package.json
- ansible/roles/metrics/files/process-cloudflare/summaries.js
- ansible/roles/metrics/files/summaries/.gcloudignore
- ansible/roles/metrics/files/summaries/Dockerfile
- ansible/roles/metrics/files/summaries/package.json
- ansible/roles/metrics/files/summaries/summaries.js
This pr adds `summaries.js` which takes an entires days (the day before) processed logs and produced a summation of all the downloads for that day.
<details>
<summary>Example output hidden in details:</summary>
<br>
```
{
bytes: 20874017783579,
total: 2409726,
country: {
US: 1632659,
AU: 22700,
GB: 32812,
IE: 93722,
DE: 130847,
PT: 1670,
NL: 98602,
TN: 1134,
BG: 948,
MX: 2861,
LV: 933,
FR: 37339,
BR: 16543,
JP: 19280,
NZ: 1076,
TH: 2278,
IN: 33332,
NO: 1738,
CL: 1034,
CA: 18474,
CN: 86016,
SE: 5288,
AR: 2281,
ES: 5674,
KR: 8533,
TR: 3783,
TW: 3409,
PL: 8560,
FI: 6016,
SG: 12137,
CH: 7329,
BE: 10345,
RU: 9037,
IL: 3647,
ID: 8475,
AT: 4677,
ZA: 1714,
DO: 207,
KE: 648,
XX: 797,
CO: 1976,
SK: 704,
EC: 504,
MA: 994,
HK: 6708,
CZ: 3314,
CR: 332,
PK: 4277,
VN: 5807,
IT: 3930,
NI: 58,
BY: 1330, …
```
> Adding summaries to the download metrics

- backup/backup_scripts/remove_old.sh
Synced the version of the `remove_old.sh` script in this repository
with the one currently deployed on the backup server.
```
ssh backup cat /root/backup_scripts/remove_old.sh > remove_old.sh
```
> backup: sync remove_old.sh with deployed version

- ansible/roles/docker/templates/ubuntu1804_sharedlibs.Dockerfile.j2
Refs: https://github.com/nodejs/node/pull/38451
> ansible: update to OpenSSL 3.0.0-alpha15+quic

- ansible/roles/baselayout/tasks/partials/repo/centos7.yml
- ansible/roles/baselayout/vars/main.yml
fixes: https://github.com/nodejs/build/issues/2587
> ansible: fix centos7 x64 ansible errors

- README.md
fixes: https://github.com/nodejs/build/issues/2617
fixes: https://github.com/nodejs/build/issues/2655
> doc: update teams with ncu-team sync

- doc/meetings/build-wg-meeting-2021-06-29
- doc/meetings/build-wg-meeting-2021-06-29.md
closes: https://github.com/nodejs/build/issues/2690
> doc: add minutes for 29-06-21

- .github/workflows/stale.yml
refs: https://github.com/nodejs/build/issues/2405#issuecomment-872846318
> actions: update stale workflow

- ansible/inventory.yml
- ansible/playbooks/jenkins/worker/create.yml
refs: https://github.com/nodejs/build/issues/2650
> inv: decomission `infra-softlayer-ubuntu1404-x64-2`

- ansible/MANUAL_STEPS.md
- ansible/ansible.cfg
- ansible/inventory.yml
- ansible/plugins/inventory/nodejs_yaml.py
- ansible/roles/baselayout/tasks/partials/repo/ibmi73.yml
- ansible/roles/baselayout/vars/main.yml
- ansible/roles/java-base/tasks/main.yml
- ansible/roles/jenkins-worker/tasks/main.yml
- ansible/roles/jenkins-worker/tasks/partials/tap2junit/ibmi.yml
- ansible/roles/jenkins-worker/templates/ibmi_start.j2
- ansible/roles/jenkins-worker/vars/main.yml
- ansible/roles/package-upgrade/tasks/partials/yum.yml
- jenkins/scripts/select-compiler.sh
Also change current host to ibmi73 from ibmi72.
Opening as draft until we can verify that it works with the CI properly, but the playbook currently runs cleanly against the newly-added rzkh host
> Upgrade playbooks for GCC 10 on IBM i and add new host

- ansible/inventory.yml
- ansible/roles/baselayout/vars/main.yml
- ansible/roles/jenkins-worker/tasks/main.yml
- ansible/roles/jenkins-worker/tasks/partials/tap2junit/centos7.yml
Looks like the other two need rebuilding so will also handle that in this PR
> ansible: add new plinux machines

- jenkins/scripts/select-compiler.sh
Fixes: https://github.com/nodejs/build/issues/2746
> jenkins: add compiler selection for Ubuntu 1804 on ARM

- ansible/inventory.yml
- ansible/roles/baselayout/vars/main.yml
Refs: https://github.com/nodejs/build/issues/2752
> ansible: add release-equinix-centos7-arm64-1

- ansible/www-standalone/resources/config/github-webhook.json.j2
- ansible/www-standalone/resources/scripts/build-site.sh
To support rename of default branch from master -> main
> chore: Update nodejs.org webhook branch

- ansible/www-standalone/resources/config/nodejs.org
Refs: https://github.com/nodejs/nodejs.org/pull/4280
> update redirect for security page

- ansible/inventory.yml
Refs: https://github.com/nodejs/build/issues/2729
Refs: https://github.com/nodejs/build/issues/2820#issuecomment-986946761
> ansible: add test-equinix-ubuntu2004_docker-arm64-2

- doc/jenkins-guide.md
We don't use IRC anymore (do we?).
> chore: IRC -> Slack

- ansible/inventory.yml
closes: https://github.com/nodejs/build/issues/2823
> ansible: update orka IPs

- doc/meetings/build-wg-meeting-2022-01-25.md
> doc: add minutes for meeting Jan 25 2022

- ansible/www-standalone/resources/config/logrotate-github-webhook
Ref: https://github.com/nodejs/build/issues/2760#issuecomment-1056027274
> fix: make github-webhook.log on www publicly readable

- ansible/inventory.yml
Moving our LinuxONE self-provisioned machines into a new "Node.js"
project. The previous ones were under a project named with Richard's
email address and the project cannot be renamed.
> ansible: update RHEL 8 s390x inventory

- README.md
Removing IRC reference which wasn't removed as part of https://github.com/nodejs/build/issues/2687
> doc: replace IRC reference with Slack

- ansible/README.md
I tried running from ansible directory and got errors I had to
track down. Clarify which directory you should run
the commands from.
> doc: clarify how to run ansible commands

- ansible/inventory.yml
> ansible: add initial AIX 73 machine

- ansible/www-standalone/tools/promote/expected_assets/v18.x
- jenkins/scripts/VersionSelectorScript.groovy
Refs: https://github.com/nodejs/node/issues/42690
Refs: https://github.com/nodejs/node/pull/43266#issuecomment-1142442304
> Restore 32-bit Windows Node.js 18 builds

- ansible/www-standalone/resources/config/iojs.org
- ansible/www-standalone/resources/config/nodejs.org
Fixes nginx off-by-slash misconfiguration.
Thank you to Nobuhiro Nagai from N.F.Laboratories for reporting this vulnerability.
Refs: https://hackerone.com/reports/1631350
Refs: https://i.blackhat.com/us-18/Wed-August-8/us-18-Orange-Tsai-Breaking-Parser-Logic-Take-Your-Path-Normalization-Off-And-Pop-0days-Out-2.pdf
---
This has been deployed on the live server.
> ansible: update nginx config

- doc/meetings/build-wg-meeting-2022-07-12.md
> doc: add minutes for July 12 2022

- doc/resources.md
A titled
The link does not work anymore.
> Remove node-builder herokuapp

- README.md
Ref: https://github.com/nodejs/build/issues/3041
> chore: add sxa to build-infra lists

- ansible/roles/awx/tasks/main.yml
- doc/node-test-commit-matrix.md
- jenkins/pipelines/http-parser-test.jenkinsfile
- jenkins/pipelines/llnode-pipeline.jenkinsfile
- jenkins/pipelines/node-linter.jenkinsfile
- jenkins/pipelines/node-test-pull-request-lite-pipeline.jenkinsfile
- jenkins/scripts/common/getNode.sh
- jenkins/scripts/coverage/generate-index-html.py
- jenkins/xml/citgm-smoker.xml
Follow up of https://github.com/nodejs/build/pull/2986, This pr update the rest default branch to main.
> chore: update default branch to main

- ansible/roles/package-upgrade/tasks/partials/brew.yml
Refs: https://github.com/nodejs/build/pull/3130#discussion_r1096664079
> ansible: fix syntax on ignore_errors condition

- ansible/www-standalone/resources/config/nodejs.org
This PR fixes the server errors we're getting when 404'ing these paths.
> chore(try-files): try files instead of error

- ansible/MANUAL_STEPS.md
- ansible/inventory.yml
- ansible/roles/baselayout/tasks/partials/ccache/aix.yml
- ansible/roles/baselayout/tasks/partials/ccache/aix73.yml
- ansible/roles/baselayout/vars/main.yml
- ansible/roles/jenkins-worker/tasks/partials/tap2junit/aix.yml
- ansible/roles/jenkins-worker/templates/aix.rc2.j2
- jenkins/scripts/select-compiler.sh
Adding some new AIX 7.2 VMs hosted in IBM Cloud.
https://ci.nodejs.org/computer/test-ibm-aix72-ppc64_be-1/ has been set up with these changes.
WIP while adding the remaining hosts and testing.
> ansible: add new AIX 7.2 machines from IBM

- doc/jenkins-guide.md
Refs: https://github.com/nodejs/TSC/issues/1340
> doc: update link to collaborators discussion page

- ansible/inventory.yml
Refs: https://github.com/nodejs/build/issues/2656
> ansible: upgrade test-nearform_intel-ubuntu1804 to 2204

- ansible/inventory.yml
- doc/node-test-commit-matrix.md
- jenkins/scripts/VersionSelectorScript.groovy
Refs: https://github.com/nodejs/build/issues/3102
> ansible: remove Raspberry Pi 1 from inventory

- ansible.cfg
- ansible/inventory.yml
- ansible/plugins/inventory/nodejs_yaml.py
- doc/node-test-commit-matrix.md
Refs: https://github.com/nodejs/build/issues/3102
> ansible: remove remaining Raspberry Pis from inventory

- ansible/inventory.yml
This allows to fold the sections properly in VSCode.
Before:
After:
> ansible: indent yaml comments in inventory

- ansible/playbooks/jenkins/worker/create.yml
- ansible/plugins/inventory/nodejs_yaml.py
- tools/host-map/host-map.mjs
Refs: https://github.com/nodejs/build/pull/3330#issuecomment-1529024717
> ansible: remove packent server

- README.md
Related: https://github.com/nodejs/build/issues/3087#issuecomment-1504058565
> Add Ulises Gascon to Jenkins Admin list

- doc/windows-visualstudio-supported-versions.md
> doc: update supported versions of Visual Studio

- ansible/roles/baselayout/vars/main.yml
- ansible/roles/jenkins-worker/vars/main.yml
- ansible/roles/package-upgrade/tasks/partials/brew.yml
Ref: https://github.com/nodejs/build/pull/3327#issuecomment-1532685660
> Remove legacy macos references in Ansible roles

- jenkins/scripts/VersionSelectorScript.groovy
Ref: https://github.com/nodejs/build/pull/3327#issuecomment-1532683118
> Deleted version selector for macos10.14

- ansible/inventory.yml
close https://github.com/nodejs/build/issues/3087
> Removed macos10.14 machines from Orka in the Inventory

- ansible/MANUAL_STEPS.md
> doc: remove outdated manual steps for Xcode

- ansible/inventory.yml
Related: https://github.com/nodejs/build/issues/3240
**Machine status:**
The machine is a new macOS version for us in Orka. I didn't Ansible the machine and it won't be added to jenkins yet.
> feat: added macos12-x64-1

- ansible/roles/docker/templates/alpine315.Dockerfile.j2
- ansible/roles/docker/templates/alpine318.Dockerfile.j2
Refs: https://github.com/nodejs/build/issues/3349
> ansible: upgrade Alpine containers to 3.15 and 3.18

- ansible.cfg
Refs: https://github.com/ansible/ansible/issues/78600
> ansible: fix ssh_connection options for OpenSSH 9.0

- doc/meetings/build-wg-meeting-2023-07-04.md
> Added 2023-07-04 meeting notes

- ansible/www-standalone/resources/config/nodejs.org
> chore(nginx): add $http_host to nodejs.org logs

- README.md
I've removed myself from the build and jenkins-admins teams.
Someone should be sure to do the things in the OFFBOARDING.md checklist too.
> Remove me from the build team

- jenkins/scripts/VersionSelectorScript.groovy
Refs: https://github.com/nodejs/node/pull/49164
> jenkins: skip osx1015 from Node.js 21

- doc/jenkins-guide.md
Improved documentation to include the PR reference when we are doing an embargo in Jenkins
> add reference to PR in the Jenkins guide

- ansible/roles/docker/templates/ubuntu1804_sharedlibs.Dockerfile.j2
- ansible/roles/docker/templates/ubuntu2004_sharedlibs.Dockerfile.j2
- ansible/roles/docker/templates/ubuntu2204_sharedlibs.Dockerfile.j2
Refs: https://github.com/v8/v8/commit/d9715adf895e9acfbaf17ae05b18f2b2467ca322
> ansible: add ICU 73 to `sharedlibs` images

- ansible/www-standalone/tasks/base.yaml
refs https://github.com/nodejs/nodejs-latest-linker/pull/12#discussion_r1342889635
> ansible: update www server node version

- README.md
After talking to several TSC members, I'm opening this self-nomination pull request:
I am interested in joining the Build WG to help with the current effort of understanding the infrastructure that's causing issues with our current setup. I'm also interested in getting familiar with our CI and solving outages and help improving them.
cc @MoLow @richardlau
> meta: add anonrig to build

- jenkins/scripts/windows/compile.cmd
This reverts commit 646ff04d28bf7a0b7654da643b039a2d53673521.
The change being reverted broke the basic sanity check in the [node-compile-windows-debug job](https://ci.nodejs.org/job/node-compile-windows-debug/) in test CI.
This breaks all PR CI runs, so the first one to approve it from @nodejs/build should land it as well. As for the fix I'm reverting, I'll go back to the implementation to find the error and open a new PR once it's fixed.
> Revert "jenkins: improve x64 node.exe caching for arm64 (#3514)"

- ansible/MANUAL_STEPS.md
I made some changes while working on https://github.com/nodejs/build/issues/3550
> Improve manual steps for macOS

- doc/meetings/build-wg-meeting-2023-11-29.md
> Add 2023-11-29 meeting notes

- ansible/roles/baselayout/tasks/main.yml
- ansible/roles/bootstrap/tasks/main.yml
- ansible/roles/build-test-v8/tasks/main.yml
- ansible/roles/docker/tasks/main.yml
- ansible/roles/jenkins-worker/tasks/main.yml
- ansible/roles/package-upgrade/handlers/main.yml
- ansible/roles/package-upgrade/tasks/main.yml
- ansible/roles/read-secrets/tasks/main.yml
- ansible/www-standalone/ansible-playbook.yaml
Closes: https://github.com/nodejs/build/issues/3127
Note that I'm not sure at all that it's the correct fix (also see inline comments).
> ansible: use include_tasks instead of include

- ansible/inventory.yml
- ansible/roles/bootstrap/tasks/partials/debian11.yml
Refs: https://github.com/nodejs/build/issues/3499#issuecomment-1847392611
---
Test build: https://ci.nodejs.org/job/node-test-commit-linux/55293/nodes=debian11-x64/console
> ansible: add swap to test-rackspace-debian11-x64-1

- jenkins/scripts/VersionSelectorScript.groovy
Refs: https://github.com/nodejs/build/issues/3593
> jenkins: skip freebsd12 on Node.js >=22

- ansible/inventory.yml
- ansible/playbooks/jenkins/worker/create.yml
- ansible/plugins/inventory/nodejs_yaml.py
- ansible/roles/benchmarking/tasks/main.yml
- ansible/roles/benchmarking/vars/main.yml
- ansible/roles/linux-perf/vars/main.yml
This PR updates the ansible to build perf and updates the packages for the benchmarking jobs.
> Hetzner-role-updates

- ansible/roles/docker/templates/alpine319.Dockerfile.j2
Test run: https://ci.nodejs.org/job/node-test-commit-linux-targos-alpine319/nodes=alpine-latest-x64-test/1/
> ansible: add Alpine 3.19

- ansible/inventory.yml
- ansible/plugins/inventory/nodejs_yaml.py
- tools/host-map/host-map.mjs
Refs: https://github.com/nodejs/build/issues/3638
To do after merging:
> ansible: remove Nearform CI machines

- doc/meetings/build-wg-meeting-2024-04-23.md
closed https://github.com/nodejs/build/issues/3689
> docs: meeting notes for 2024-04-23

- jenkins/scripts/select-compiler.sh
Refs: https://github.com/nodejs/build/pull/3701
> jenkins: select GCC 11 on Debian 12

- doc/meetings/build-wg-meeting-2024-05-15.md
close https://github.com/nodejs/build/issues/3716
> Add meeting notes for 2024-05-15

- doc/meetings/build-wg-meeting-2024-06-04.md
> Meeting notes for 2024-06-04

- ansible/roles/metrics/files/process-cloudflare/package.json
- ansible/roles/metrics/files/process-cloudflare/process-cloudflare.js
Fixes: https://github.com/nodejs/build/issues/3784
Test code in https://github.com/nodejs/build/issues/3784#issuecomment-2190714334
> metrics: replace strftime with JavaScript Date API

- ansible/roles/metrics/files/index-generator/index-generator.js
- ansible/roles/metrics/files/index-generator/package.json
- ansible/roles/metrics/files/process-cloudflare/package.json
- ansible/roles/metrics/files/process-cloudflare/process-cloudflare.js
- ansible/roles/metrics/files/summaries/package.json
- ansible/roles/metrics/files/summaries/summaries.js
Fixes: https://github.com/nodejs/build/issues/3792
> metrics: replace body-parser with native express.json()

- ansible/roles/metrics/files/index-generator/index-generator.js
- ansible/roles/metrics/files/summaries/summaries.js
Docs: https://googleapis.dev/nodejs/storage/5.20.5/File.html#save-examples
```js
//-
// If the callback is omitted, we'll return a Promise.
//-
file.save(contents).then(function() {});
```
> metrics: convert file.save from callback to promise

- ansible/roles/metrics/files/summaries/summaries.js
Fixes: https://github.com/nodejs/build/issues/3780
> metrics: allow passing specific date to generate summaries for

- ansible/roles/metrics/files/summaries/summaries.js
Fixes: https://github.com/nodejs/build/issues/3799
Test code in https://github.com/nodejs/build/issues/3799#issuecomment-2203089392
> metrics: add a separate route to process summary for specific date

- ansible/inventory.yml
- ansible/playbooks/jenkins/worker/create.yml
Adds the new mnx workspace machines to the inventory and worker roles.
> anisible: Add jenkins workspace machines

- ansible/inventory.yml
Migration to new hosts complete. Removing the old ones so we can decommission the hosts..
> ansible: remove equinix workspace machines

- ansible/inventory.yml
- ansible/roles/bootstrap/tasks/partials/rhel9-s390x.yml
- ansible/roles/jenkins-worker/tasks/main.yml
- jenkins/scripts/select-compiler.sh
Decommission centos7-ppc64le and rhel7-s390x machines. Create new RHEL 9 test CI replacements.
Add 2 GB swap to all ppc64le and s390x machines.
> ansible: update ppc64le and s390x machines

- ansible/roles/metrics/files/summaries/summaries.js
Fixes: https://github.com/nodejs/build/issues/3810
---
Tested by deploying, and re-running counts for `20240425` and `20240426` in parallel.
These dates had summaries created from previous iteration of produce summaries, before the refactoring had begun.
From logs
```console
2024-07-06 16:41:28.812 PDT 20240426/
2024-07-06 16:41:37.012 PDT 20240425/
2024-07-06 16:48:36.519 PDT Upload complete: nodejs.org-access.log.20240426.json
2024-07-06 16:50:03.611 PDT Upload complete: nodejs.org-access.log.20240425.json
```
Ran the test code from https://github.com/nodejs/build/issues/3810#issue-2393770418 to verify the numbers
```console
20240425: 5367285
20240426: 4942371
```
```console
20240425: 5367285
20240426: 4942371
```
> metrics: store summary counts for specific date in cache key

- ansible/roles/baselayout/vars/main.yml
- jenkins/scripts/select-compiler.sh
Refs: https://github.com/nodejs/node/pull/53728
> ansible,jenkins: revert to default gcc-12 on debian12

- ansible/roles/baselayout/vars/main.yml
- ansible/roles/docker/templates/ubuntu2204_sharedlibs.Dockerfile.j2
> ansible: install gcc-12 on ubuntu2204

- orka/templates/README.md
Related https://github.com/nodejs/build/issues/3686#issuecomment-2278119351 and https://github.com/nodejs/build/pull/3874
> docs: add support for new images in Orka

- jenkins/scripts/select-compiler.sh
> jenkins: select gcc-12 on RHEL for Node.js 23

- doc/orka-vpn.md
Add documentation to setup Orka VPN connection in Jenkins Servers.
- Related https://github.com/nodejs/build/issues/3686
- closes https://github.com/nodejs/build/issues/3883
> docs: add Orka setup steps for Jenkins

- jenkins/scripts/select-compiler.sh
> jenkins: select gcc 12 on Ubuntu 22.04 for Node.js 23

- jenkins/logcompresser.sh
We'll manually add this to a daily crontab on ci.nodejs.org
> feat: Add log compression script to reduce jenkins disk size

- jenkins/scripts/select-compiler.sh
Refs: https://github.com/nodejs/build/pull/3907
> jenkins: select gcc12 for Node 23 on IBM i

- jenkins/logcompresser.sh
Minor tweaks to make the compression script work.
> feat: adjust compresser script to work with print0 and paths

- doc/meetings/build-wg-meeting-2024-09-18.md
closes: https://github.com/nodejs/build/issues/3912
> docs: add meeting notes 2024-09-18

- doc/meetings/build-wg-meeting-2024-10-09.md
Closes https://github.com/nodejs/build/issues/3926
> Meeting notes 2024-10-09

- ansible/inventory.yml
- ansible/playbooks/jenkins/host/create.yml
- ansible/playbooks/jenkins/host/iptables.yml
Refs: https://github.com/nodejs/build/issues/3852
> anisble: update ci-release server

- ansible/roles/baselayout/vars/main.yml
> ansible: install gcc12 on IBM i

- jenkins/scripts/VersionSelectorScript.groovy
Refs: https://github.com/nodejs/build/issues/3593
Refs: https://github.com/nodejs/node/issues/54576
> jenkins: skip freebsd13 on Node.js >=22

- ansible/www-standalone/tools/promote/_promote.sh
- ansible/www-standalone/tools/promote/_resha.sh
- ansible/www-standalone/tools/promote/resha_release.sh
It needs it after https://github.com/nodejs/build/pull/3953
> ansible: pass srcdir to _resha script

- ansible/inventory.yml
- ansible/roles/baselayout/tasks/main.yml
Refs: https://github.com/nodejs/build/issues/3593
> ansible: remove FreeBSD 12

- doc/release-overview.md
Commit 3a455b246c9a8ad79cbffdad15f4bdfac1b2adac moved the `release-post/index.mjs` file. This PR adjusts sources to changes.
> doc: update `release-post/index.mjs` reference

- ansible/inventory.yml
This resolves: https://github.com/nodejs/jenkins-alerts/issues/1335
> ansible: upgrade rzkh machine to IBM i 7.4

- ansible/inventory.yml
Rebuilding the new hosts, adding them to the inventory here.
> ansible: add new uncompromised smartos hosts

- jenkins/scripts/node-test-commit-pre.sh
> fix: improve support for commit validation in MacOS

- ansible/www-standalone/tools/promote/expected_assets/v23.x
Refs: https://github.com/nodejs/node/pull/57016
> Add `node-config-schema.json` to expected files in v23.x

- ansible/MANUAL_STEPS.md
Update the smartos manual steps.
> Docs: Update SmartOS manual steps

- ansible/inventory.yml
Replace
- test-ibm-rhel8-s390x-4
- test-linuxonecc-rhel9-s390x-1
> ansible: replace some LinuxOne machines

- ansible/www-standalone/tools/promote/expected_assets/v24.x
- jenkins/scripts/VersionSelectorScript.groovy
Refs: https://github.com/nodejs/node/pull/58071
> ansible,jenkins: drop support for armv7 in Node.js 24

- doc/meetings/build-wg-meeting-2025-05-08.md
> doc: add minutes for meeting May 8 2025

- doc/meetings/build-wg-meeting-2025-06-19.md
Closes https://github.com/nodejs/build/issues/4094
> Meeting-2025-06-19

- doc/meetings/build-wg-meeting-2025-07-10.md
Closes https://github.com/nodejs/build/issues/4101.
> jul-10-2025

- doc/meetings/build-wg-meeting-2025-07-31.md
Closes https://github.com/nodejs/build/issues/4112.
> 2025-07-31 minutes

- doc/meetings/build-wg-meeting-2025-08-21.md
Closes https://github.com/nodejs/build/issues/4125
> 2025-08-21 meeting notes
